import type { SeedProduct } from "./catalog.seed";

// ─────────────────────────────────────────────────────────────
// CATEGORY 2 — BEDS & BEDROOM  (27 products)
// ─────────────────────────────────────────────────────────────
export const BEDS_BEDROOM: SeedProduct[] = [
  // ── Upholstered Beds (6) ──────────────────────────────────────
  {
    sku: "MOD-BED-001", slug: "aurelia-king-boucle-bed",
    name: "Aurelia King Upholstered Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Modulas Originals", price: 345000, compareAtPrice: 415000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm White", "Slate Grey", "Sage", "Caramel"],
    dimensions: { width: 198, height: 138, depth: 220, unit: "cm" }, weightKg: 98,
    isConfigurable: true, isFeatured: true, stockQty: 7, leadTimeDays: 35,
    seoTitle: "Aurelia King Boucle Upholstered Bed — Modulas Luxury Bedroom",
    seoDescription: "Fluted boucle headboard king bed on solid oak frame. Optional hydraulic storage base. 4 colourways. India's finest bedroom furniture.",
    tags: ["bestseller", "subcategory:upholstered-beds"],
    description: "A fluted boucle headboard that commands the room without demanding attention. The Aurelia's proportions are calibrated for the master bedroom.",
    metadata: {
      fullDescription: "The Aurelia Bed is the most loved piece in the Modulas bedroom range — and for good reason. Its headboard is formed from individually tailored boucle panels, sewn in a vertical fluted pattern that catches light and shadow differently through the day. The solid oak platform frame sits 28 cm above the floor — low enough to create a relaxed aesthetic, high enough for under-bed storage. An optional hydraulic gas-lift base converts the entire platform into 800 litres of concealed storage.",
      features: [
        "Fluted boucle headboard — individually tailored panels",
        "Solid oak platform frame — 28 cm floor clearance",
        "Optional hydraulic gas-lift storage — 800 L capacity",
        "Available in Single, Double, Queen, and King",
        "Headboard height 138 cm — generous for reading in bed",
        "Matching nightstands and wardrobe available",
        "10-year structural frame guarantee",
      ],
      care: "Vacuum boucle headboard weekly. Spot-clean with foam upholstery cleaner. Oil oak legs annually.",
      warranty: "10-year frame. 3-year fabric. 5-year hydraulic mechanism (if fitted).",
      rating: 4.9, reviewCount: 214,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Aurelia King Bed in Warm White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Aurelia — fluted headboard detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BED-002", slug: "opulent-queen-velvet-bed",
    name: "Opulent Queen Velvet Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Atelier Series", price: 295000, currency: "INR",
    material: "Velvet", finishOptions: ["Dusty Rose", "Sage Green", "Midnight Blue", "Champagne", "Charcoal"],
    dimensions: { width: 168, height: 145, depth: 215, unit: "cm" }, weightKg: 86,
    isConfigurable: true, isFeatured: false, stockQty: 9, leadTimeDays: 28,
    seoTitle: "Opulent Queen Velvet Upholstered Bed — Atelier Series Modulas",
    seoDescription: "Queen velvet upholstered bed with deep-buttoned headboard. 5 colourways. Solid walnut legs. Free delivery and assembly pan-India.",
    tags: ["new", "subcategory:upholstered-beds"],
    description: "Deep button-tufting in velvet across a tall 145 cm headboard — the Opulent Queen makes the bed the unambiguous centrepiece of the room.",
    metadata: {
      fullDescription: "The Opulent Queen's headboard height of 145 cm makes a deliberate statement — in a bedroom, the bed should be the focal point, and this one is unambiguous about that intention. The button tufting is set in a diamond grid, each button individually positioned by hand, with velvet that is pulled taut enough to create crisp diamond shapes without distorting the pile direction.",
      features: [
        "145 cm tall deep-button tufted headboard",
        "Hand-set diamond tufting — individually positioned buttons",
        "5 velvet colourways — 480 gsm crush-resistant pile",
        "Solid walnut tapered legs",
        "Optional drawer base — 4 under-bed drawers",
        "Available Queen and King",
        "Slatted timber base included — no box spring needed",
      ],
      care: "Brush velvet headboard with soft-bristle brush. Do not steam the button tufting. Spot-clean with velvet foam cleaner.",
      warranty: "10-year frame. 3-year velvet.",
      rating: 4.8, reviewCount: 128,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Opulent Queen Bed in Dusty Rose Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Opulent — button tufting detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BED-003", slug: "imperial-king-divan-bed",
    name: "Imperial King Divan Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Heritage Collection", price: 485000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Cognac", "Black", "Taupe", "Bordeaux"],
    dimensions: { width: 198, height: 120, depth: 220, unit: "cm" }, weightKg: 118,
    isConfigurable: false, isFeatured: true, stockQty: 3, leadTimeDays: 56,
    seoTitle: "Imperial King Leather Divan Bed — Heritage Collection Modulas",
    seoDescription: "Full-grain leather king divan bed. Fully upholstered base and headboard. Hand-built at Modulas Jaipur Atelier. Lifetime frame warranty.",
    tags: ["premium", "limited", "subcategory:upholstered-beds"],
    description: "The Imperial is a bed without a single exposed surface. Every centimetre — headboard, base, and legs — is wrapped in full-grain leather, hand-stitched at the Jaipur Atelier.",
    metadata: {
      fullDescription: "A divan bed fully upholstered in full-grain leather is a rare and considered choice — and the Imperial delivers it with the craft and restraint that Heritage Collection demands. The base is a platform divan — solid and uncompromising — upholstered in the same leather as the headboard, with concealed storage drawers on both sides. The legs are hidden behind a leather plinth, giving the bed the appearance of floating above the floor.",
      features: [
        "Full-grain leather — headboard, base, and plinth",
        "Hand-stitched seams — Heritage Jaipur Atelier",
        "Concealed storage drawers — both sides of base",
        "120 cm headboard — proportioned for a king-size room",
        "Slatted sprung base — suitable for all mattress types",
        "Lifetime frame guarantee",
        "Matching leather bench and nightstands available",
      ],
      care: "Condition leather surfaces every 3 months. Wipe with dry microfibre cloth. Avoid placing near heat sources.",
      warranty: "Lifetime frame. 10-year leather.",
      rating: 4.9, reviewCount: 42,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Imperial King Leather Divan in Cognac", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Imperial — leather base plinth detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BED-004", slug: "atelier-queen-linen-bed",
    name: "Atelier Queen Linen Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Atelier Series", price: 248000, currency: "INR",
    material: "Belgian Linen", finishOptions: ["Natural", "Warm Stone", "Blush", "Soft Blue"],
    dimensions: { width: 168, height: 118, depth: 215, unit: "cm" }, weightKg: 78,
    isConfigurable: true, isFeatured: false, stockQty: 11, leadTimeDays: 28,
    seoTitle: "Atelier Queen Belgian Linen Upholstered Bed — Modulas",
    seoDescription: "Queen bed in Belgian linen with arched headboard. 118 cm headboard height. Solid oak legs. Slatted base included. Ships in 28 days.",
    tags: ["subcategory:upholstered-beds"],
    description: "An arched Belgian linen headboard that softens the bedroom with its quiet, natural texture. The Atelier Queen is serene by design.",
    metadata: {
      fullDescription: "The Atelier Queen's arched headboard brings a softness that square and rectangular headboards cannot achieve. The arch is cut from a single curved MDF former, then padded with 5 cm of memory foam and wrapped in Belgian linen. The natural linen texture is highly responsive to ambient light — warm in the morning, cool in the evening — creating a headboard that subtly changes character through the day.",
      features: [
        "Arched headboard — single curved former, linen-wrapped",
        "5 cm memory foam headboard padding",
        "Belgian linen — 4 natural colourways",
        "Solid oak legs — natural oil finish",
        "Slatted sprung base included",
        "Available Double, Queen, and King",
        "Matching nightstands and linen wardrobe available",
      ],
      care: "Dry-clean linen headboard cover. Spot-clean with damp cloth. Oil oak legs annually.",
      warranty: "10-year frame. 2-year linen.",
      rating: 4.7, reviewCount: 156,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Atelier Queen Linen Bed in Natural", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Atelier — arch headboard detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BED-005", slug: "sapphire-king-panel-bed",
    name: "Sapphire King Panel Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Modulas Originals", price: 318000, currency: "INR",
    material: "Velvet", finishOptions: ["Ink Blue", "Forest Green", "Graphite", "Burgundy"],
    dimensions: { width: 198, height: 155, depth: 220, unit: "cm" }, weightKg: 104,
    isConfigurable: true, isFeatured: false, stockQty: 6, leadTimeDays: 35,
    seoTitle: "Sapphire King Velvet Panel Bed — Modulas Luxury Bedroom",
    seoDescription: "King panel velvet bed with 155 cm padded headboard. 4 rich colourways. Optional storage base. Kiln-dried frame. India-wide delivery.",
    tags: ["premium", "subcategory:upholstered-beds"],
    description: "The Sapphire King's 155 cm headboard makes a statement in deep jewel-tone velvet — a bedroom piece with true presence.",
    metadata: {
      fullDescription: "The Sapphire Panel Bed is designed for the bedroom that takes its role seriously as a sanctuary. The full-width panelled headboard — 155 cm tall and the full width of the king frame — is upholstered in a single piece of velvet with piped edges and a 6 cm deep-foam pad behind it. The result is an enveloping back support for those who read or work in bed, and a dramatic visual centrepiece when the room is unoccupied.",
      features: [
        "155 cm full-width panelled headboard",
        "6 cm deep-foam padding — genuinely supportive",
        "Piped headboard edges — precision tailoring",
        "480 gsm velvet in 4 jewel tones",
        "Optional hydraulic storage base — 750 L",
        "Solid oak frame throughout",
        "Available Queen and King",
      ],
      care: "Brush velvet with soft-bristle brush. Spot-clean with velvet cleaner. Do not steam.",
      warranty: "10-year frame. 3-year velvet. 5-year hydraulic (if fitted).",
      rating: 4.8, reviewCount: 87,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Sapphire King Bed in Ink Blue Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Sapphire — panel headboard side view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BED-006", slug: "signature-queen-bed",
    name: "Signature Queen Tufted Bed", categorySlug: "bedroom", subcategorySlug: "upholstered-beds",
    brand: "Modulas Originals", price: 275000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Oatmeal", "Slate", "Warm Sand", "Blush"],
    dimensions: { width: 168, height: 128, depth: 215, unit: "cm" }, weightKg: 84,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 28,
    seoTitle: "Signature Queen Boucle Tufted Bed — Modulas",
    seoDescription: "Queen boucle bed with horizontal tufted headboard. 128 cm height. Slatted oak base. 4 colourways. Pairs with Signature nightstands.",
    tags: ["subcategory:upholstered-beds"],
    description: "Horizontal tufting across a boucle headboard — a modern take on a classic technique. The Signature Queen balances precision with warmth.",
    metadata: {
      fullDescription: "Where most tufted beds use diamond or button formats, the Signature employs horizontal channel tufting — rows of stitching running the full width of the headboard in a 12 cm repeat. The result is a graphic quality that reads as modern but references the tailoring heritage of traditional upholstery. The boucle fabric is pre-treated to prevent pile compression around the channels.",
      features: [
        "Horizontal channel-tufted headboard — full width",
        "12 cm channel repeat — precise and graphic",
        "Anti-pile-compression boucle treatment",
        "128 cm headboard height",
        "Solid oak slatted base — no box spring required",
        "Available Double, Queen, King",
        "Pairs with Signature nightstands",
      ],
      care: "Vacuum boucle with soft brush attachment. Spot-clean channels with foam cleaner.",
      warranty: "10-year frame. 3-year boucle.",
      rating: 4.7, reviewCount: 101,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Signature Queen Bed in Oatmeal Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Signature — channel tufting detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Bed Frames (5) ────────────────────────────────────────────
  {
    sku: "MOD-FRM-001", slug: "celeste-platform-bed-frame",
    name: "Celeste Solid Oak Platform Bed", categorySlug: "bedroom", subcategorySlug: "bed-frames",
    brand: "Modulas Originals", price: 195000, compareAtPrice: 235000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural Oil", "Whitened Oak", "Dark Smoked"],
    dimensions: { width: 168, height: 28, depth: 215, unit: "cm" }, weightKg: 72,
    isConfigurable: true, isFeatured: true, stockQty: 12, leadTimeDays: 21,
    seoTitle: "Celeste Solid Oak Platform Bed Frame — Modulas Bedroom",
    seoDescription: "Solid oak platform bed frame in 3 finishes. 28 cm floor clearance. No box spring needed. Ships in 21 days pan-India.",
    tags: ["bestseller", "sale", "subcategory:bed-frames"],
    description: "Solid oak with nothing hidden — the Celeste Platform shows every grain, every joint, and every decision made in its construction.",
    metadata: {
      fullDescription: "The Celeste Platform is the purest expression of the Modulas design philosophy — premium materials, honest construction, no concealment. The solid oak frame is assembled with traditional mortise-and-tenon joinery (no screws in the structural joints), and the surface is finished with a penetrating oil that feeds the wood rather than sitting on top of it. The result is a frame that will outlast trends and age into something increasingly beautiful.",
      features: [
        "Solid oak throughout — no MDF or plywood",
        "Mortise-and-tenon structural joinery",
        "Penetrating oil finish — 3 colourways",
        "28 cm floor clearance — ample under-bed storage",
        "Integrated slat base — no box spring required",
        "Available Double, Queen, King, and Super King",
        "10-year structural guarantee",
      ],
      care: "Wipe with a dry cloth. Re-oil once per year with teak or Danish oil. Avoid excess moisture.",
      warranty: "10-year frame guarantee.",
      rating: 4.8, reviewCount: 189,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Celeste Platform Bed in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Celeste — mortise and tenon joint detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-FRM-002", slug: "regal-king-canopy-bed",
    name: "Regal King Canopy Bed", categorySlug: "bedroom", subcategorySlug: "bed-frames",
    brand: "Heritage Collection", price: 545000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Dark Walnut", "Natural Walnut", "Ebonised"],
    dimensions: { width: 198, height: 220, depth: 225, unit: "cm" }, weightKg: 142,
    isConfigurable: false, isFeatured: true, stockQty: 2, leadTimeDays: 56,
    seoTitle: "Regal King Canopy Bed in Solid Walnut — Heritage Collection Modulas",
    seoDescription: "Solid walnut four-poster canopy bed. 220 cm posts. Hand-turned details. Heritage Collection — small batch, made in India.",
    tags: ["premium", "limited", "subcategory:bed-frames"],
    description: "Four solid walnut posts rising to 220 cm — the Regal Canopy is the bed that transforms a bedroom into a chamber.",
    metadata: {
      fullDescription: "The Regal Canopy Bed is made in batches of four at the Modulas Jaipur Atelier. Each post is turned from a single piece of solid American black walnut — the natural grain pattern ensuring that no two posts are identical. The canopy rail sits at 200 cm, with a secondary rail at 220 cm for draped fabric (not included). The headboard is a solid slatted panel in the same walnut as the frame.",
      features: [
        "Solid American black walnut throughout — no veneers",
        "Hand-turned posts — unique grain per post",
        "220 cm canopy rail — drape-ready",
        "Slatted solid walnut headboard panel",
        "Traditional mortise-and-tenon joinery",
        "Integrated centre support rail",
        "Made in batches of 4 — limited availability",
      ],
      care: "Wipe with dry cloth. Re-oil with walnut oil or Danish oil annually. Tighten joinery if needed after first year.",
      warranty: "Lifetime frame guarantee.",
      rating: 5.0, reviewCount: 28,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Regal Canopy Bed in Dark Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Regal — walnut post detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-FRM-003", slug: "serenity-low-platform-bed",
    name: "Serenity Low Platform Bed", categorySlug: "bedroom", subcategorySlug: "bed-frames",
    brand: "Atelier Series", price: 165000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural", "Whitened", "Smoked"],
    dimensions: { width: 168, height: 18, depth: 215, unit: "cm" }, weightKg: 62,
    isConfigurable: true, isFeatured: false, stockQty: 15, leadTimeDays: 21,
    seoTitle: "Serenity Low Platform Bed in Solid Oak — Atelier Series Modulas",
    seoDescription: "Ultra-low 18 cm platform bed in solid oak. Japandi design. No headboard — pairs with any wall art or wall-mounted panel. Ships in 21 days.",
    tags: ["new", "subcategory:bed-frames"],
    description: "At 18 cm, the Serenity sits as close to the floor as a platform bed can — a Japandi-inspired frame that makes the mattress the hero.",
    metadata: {
      fullDescription: "The Serenity Low Platform was designed for those who find solace in simplicity. Inspired by the Japanese practice of low sleeping, this frame positions the mattress just 18 cm above the floor — creating a bedroom that feels grounded, calm, and spacious. The solid oak is finished in a whitened wash that references Scandinavian minimalism while working equally well with darker, richer bedroom palettes.",
      features: [
        "18 cm ultra-low profile — Japandi inspiration",
        "Solid oak — whitened, natural, or smoked finish",
        "No headboard — intentionally headboard-free design",
        "Reinforced slat base — suits all mattress types",
        "Available Double, Queen, King",
        "Pairs with Serenity floor-lamp and nightstands",
        "10-year structural guarantee",
      ],
      care: "Wipe with dry cloth. Oil annually.",
      warranty: "10-year frame.",
      rating: 4.6, reviewCount: 73,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Serenity Low Platform Bed in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Serenity — ultra-low profile from side", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-FRM-004", slug: "eclipse-walnut-bed-frame",
    name: "Eclipse Solid Walnut Bed", categorySlug: "bedroom", subcategorySlug: "bed-frames",
    brand: "Atelier Series", price: 285000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut"],
    dimensions: { width: 168, height: 48, depth: 215, unit: "cm" }, weightKg: 88,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 35,
    seoTitle: "Eclipse Solid Walnut Platform Bed Frame — Atelier Series Modulas",
    seoDescription: "Solid walnut bed frame with slatted headboard panel. 48 cm platform height. Queen and King sizes. 15-year frame guarantee.",
    tags: ["premium", "subcategory:bed-frames"],
    description: "Solid walnut — every panel, every slat, every leg. The Eclipse is a commitment to material honesty at the scale of a king-size bed.",
    metadata: {
      fullDescription: "The Eclipse uses solid American black walnut for every component — the platform rails, the slatted headboard panel, the side rails, and the tapered legs. The slatted headboard is a particularly considered detail: 12 vertical slats with 2 cm gaps between them create a screen-like effect that is distinctive from the front and transparent from behind, allowing the wall behind to remain visible. This works particularly well in rooms with panelled or coloured walls.",
      features: [
        "100% solid American black walnut — no veneers",
        "Slatted headboard — 12 vertical slats, 2 cm gap",
        "48 cm platform height — conventional under-bed clearance",
        "Tapered solid walnut legs",
        "Reinforced slat base — no box spring needed",
        "Available Queen and King",
        "15-year frame guarantee",
      ],
      care: "Dust regularly. Oil with walnut oil once per year. Avoid direct sun exposure to prevent uneven fading.",
      warranty: "15-year frame.",
      rating: 4.8, reviewCount: 64,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Eclipse Walnut Bed in Natural Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Eclipse — slatted headboard detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-FRM-005", slug: "dawn-platform-double-bed",
    name: "Dawn Platform Double Bed", categorySlug: "bedroom", subcategorySlug: "bed-frames",
    brand: "Modulas Originals", price: 148000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural", "White", "Smoked"],
    dimensions: { width: 148, height: 32, depth: 205, unit: "cm" }, weightKg: 56,
    isConfigurable: false, isFeatured: false, stockQty: 20, leadTimeDays: 14,
    seoTitle: "Dawn Platform Double Bed in Solid Oak — Modulas",
    seoDescription: "Solid oak double platform bed. 148 cm wide. 3 finishes. Ships in 14 days. Entry-level luxury — full Modulas quality at an accessible price.",
    tags: ["subcategory:bed-frames"],
    description: "The Dawn is Modulas's most accessible solid-oak bed — no compromises on material or construction, just a more restrained specification.",
    metadata: {
      fullDescription: "The Dawn Platform is the entry point to the Modulas bedroom range — and it maintains the standards that define the collection. Solid oak (not oak veneer), mortise-and-tenon joinery, and a penetrating oil finish. The headboard is a simple curved panel — solid oak on a solid oak frame — without fabric or additional material layers. It is the bed for those who want quality without embellishment.",
      features: [
        "Solid oak — full thickness, not veneer",
        "Mortise-and-tenon joinery at key structural points",
        "Curved solid oak headboard panel",
        "32 cm floor clearance",
        "Slat base included — no box spring needed",
        "Available Double only — optimised for the specification",
        "10-year structural guarantee",
      ],
      care: "Wipe with dry cloth. Oil annually. Tighten joinery after first 6 months.",
      warranty: "10-year frame.",
      rating: 4.6, reviewCount: 245,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Dawn Platform Double Bed in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Dawn — curved oak headboard", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Storage Beds (4) ────────────────────────────────────────────
  {
    sku: "MOD-STB-001", slug: "monarch-king-storage-bed",
    name: "Monarch King Storage Bed", categorySlug: "bedroom", subcategorySlug: "storage-beds",
    brand: "Modulas Originals", price: 398000, compareAtPrice: 465000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm White", "Slate", "Sage", "Terracotta"],
    dimensions: { width: 198, height: 132, depth: 220, unit: "cm" }, weightKg: 124,
    isConfigurable: true, isFeatured: true, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Monarch King Hydraulic Storage Bed in Boucle — Modulas",
    seoDescription: "King hydraulic lift storage bed in boucle. 900 L storage capacity. Fluted headboard. Free white-glove delivery and assembly.",
    tags: ["bestseller", "sale", "subcategory:storage-beds"],
    description: "The Monarch King solves the bedroom's greatest challenge — where to put everything — with 900 litres of hydraulic storage beneath a boucle fluted headboard.",
    metadata: {
      fullDescription: "The Monarch is Modulas's most practical bedroom piece — a king-size storage bed with a hydraulic gas-lift mechanism that raises the entire mattress platform to reveal 900 litres of storage beneath. The mechanism is rated for 50,000 lift cycles — at two lifts per day, that is nearly 70 years of daily use. The boucle headboard is the same fluted design as the Aurelia, available in four colourways.",
      features: [
        "Hydraulic gas-lift — 900 L storage beneath mattress",
        "50,000-cycle rated lift mechanism",
        "Fluted boucle headboard — 132 cm height",
        "Solid oak frame and platform",
        "Dual-side access — lift from either side",
        "Available Queen and King",
        "White-glove delivery and assembly included",
      ],
      care: "Lubricate hydraulic mechanism every 2 years with furniture-grade grease. Vacuum boucle headboard monthly.",
      warranty: "10-year frame. 5-year hydraulic mechanism. 3-year fabric.",
      rating: 4.9, reviewCount: 176,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Monarch King Storage Bed in Warm White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Monarch — hydraulic lift open view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-STB-002", slug: "crest-queen-drawer-bed",
    name: "Crest Queen Drawer Bed", categorySlug: "bedroom", subcategorySlug: "storage-beds",
    brand: "Atelier Series", price: 298000, currency: "INR",
    material: "Velvet", finishOptions: ["Midnight Blue", "Graphite", "Forest Green", "Champagne"],
    dimensions: { width: 168, height: 128, depth: 215, unit: "cm" }, weightKg: 108,
    isConfigurable: true, isFeatured: false, stockQty: 7, leadTimeDays: 28,
    seoTitle: "Crest Queen Drawer Storage Bed in Velvet — Atelier Series Modulas",
    seoDescription: "Queen velvet bed with 4 under-bed drawers. Soft-close drawer slides. 128 cm tufted headboard. Ships in 28 days.",
    tags: ["subcategory:storage-beds"],
    description: "Four soft-close drawers beneath a velvet tufted headboard — the Crest Queen keeps the bedroom clear without sacrificing any visual quality.",
    metadata: {
      fullDescription: "The Crest Queen uses a drawer-base storage system rather than a hydraulic lift — four large soft-close drawers (two on each side) that slide out on full-extension runners for complete access to the back of each drawer. This system is preferable in rooms where the mattress cannot be lifted due to overhead space constraints or physical limitations.",
      features: [
        "4 large soft-close drawers — full-extension runners",
        "Two drawers each side — complete access",
        "Velvet tufted headboard — 128 cm",
        "Solid frame — no flex or rattle",
        "Drawers lined in a pale grey cotton",
        "Available Queen and King",
        "Matching Crest nightstands available",
      ],
      care: "Wipe drawer interiors with damp cloth. Vacuum velvet headboard. Apply drawer lubricant annually.",
      warranty: "10-year frame and drawer mechanism. 3-year velvet.",
      rating: 4.7, reviewCount: 93,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Crest Queen Drawer Bed in Midnight Blue", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Crest — open drawer view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-STB-003", slug: "storage-king-ottoman-bed",
    name: "Santorini King Ottoman Bed", categorySlug: "bedroom", subcategorySlug: "storage-beds",
    brand: "Modulas Originals", price: 425000, currency: "INR",
    material: "Belgian Linen", finishOptions: ["Warm Stone", "Oatmeal", "Soft Grey", "Taupe"],
    dimensions: { width: 198, height: 126, depth: 222, unit: "cm" }, weightKg: 132,
    isConfigurable: true, isFeatured: false, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Santorini King Ottoman Storage Bed in Linen — Modulas",
    seoDescription: "King ottoman storage bed in Belgian linen. End-lift mechanism — lifts from foot. 850 L storage. 126 cm arched linen headboard.",
    tags: ["new", "subcategory:storage-beds"],
    description: "The Santorini's end-lift ottoman mechanism — lifting from the foot of the bed — is the most ergonomic storage solution in the Modulas range.",
    metadata: {
      fullDescription: "Most hydraulic storage beds lift from the side — requiring the user to stand beside the bed to access storage. The Santorini uses an end-lift mechanism: the mattress platform lifts from the foot of the bed, like a lid, giving complete access to 850 litres of storage from a natural standing position at the end of the bed. The Belgian linen arched headboard mirrors the Atelier Queen design.",
      features: [
        "End-lift hydraulic mechanism — lifts from foot of bed",
        "850 L storage — full accessibility from bed end",
        "Belgian linen arched headboard — 126 cm",
        "Solid oak platform frame",
        "Gas-strut rated 50,000 cycles",
        "Available Queen and King",
        "White-glove delivery included",
      ],
      care: "Lubricate gas-strut mechanism every 2 years. Vacuum linen headboard. Spot-clean with damp cloth.",
      warranty: "10-year frame. 5-year gas-strut. 2-year linen.",
      rating: 4.8, reviewCount: 58,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Santorini King Ottoman Bed in Warm Stone", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Santorini — end-lift mechanism open", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-STB-004", slug: "nova-queen-lift-bed",
    name: "Nova Queen Hydraulic Lift Bed", categorySlug: "bedroom", subcategorySlug: "storage-beds",
    brand: "Atelier Series", price: 275000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Cloud White", "Pebble", "Warm Sand"],
    dimensions: { width: 168, height: 122, depth: 215, unit: "cm" }, weightKg: 108,
    isConfigurable: true, isFeatured: false, stockQty: 9, leadTimeDays: 28,
    seoTitle: "Nova Queen Hydraulic Lift Storage Bed — Atelier Series Modulas",
    seoDescription: "Queen hydraulic storage bed in boucle. 780 L storage. 122 cm padded headboard. Side-lift mechanism. Free assembly pan-India.",
    tags: ["subcategory:storage-beds"],
    description: "780 litres of hydraulic storage beneath a padded boucle headboard. The Nova Queen is the most practical bed in the Atelier range.",
    metadata: {
      fullDescription: "The Nova Queen is designed for the bedroom that has no space to waste. Its hydraulic side-lift mechanism raises the full mattress platform in a single, smooth motion, revealing 780 litres of storage — enough for seasonal bedding, suitcases, and everything that needs to be close but out of sight. The boucle padded headboard is simple and clean — the storage function is the defining feature here.",
      features: [
        "Hydraulic side-lift — smooth, one-hand operation",
        "780 L storage — full-depth access",
        "Padded boucle headboard — 122 cm",
        "Solid beech platform frame",
        "40,000-cycle rated lift mechanism",
        "Available Queen and King",
        "Assembly included with delivery",
      ],
      care: "Lubricate mechanism every 18 months. Vacuum headboard monthly.",
      warranty: "8-year frame. 4-year hydraulic. 2-year fabric.",
      rating: 4.6, reviewCount: 112,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Nova Queen Storage Bed in Cloud White", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Nova — storage compartment open", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Wardrobes (4) ──────────────────────────────────────────────
  {
    sku: "MOD-WRD-001", slug: "haven-oak-wardrobe",
    name: "Haven 2-Door Oak Wardrobe", categorySlug: "bedroom", subcategorySlug: "wardrobes",
    brand: "Modulas Originals", price: 385000, currency: "INR",
    material: "Solid Oak & Smoked Glass", finishOptions: ["Natural Oak", "Painted White", "Smoked Oak"],
    dimensions: { width: 120, height: 220, depth: 60, unit: "cm" }, weightKg: 118,
    isConfigurable: true, isFeatured: true, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Haven 2-Door Solid Oak Wardrobe — Modulas Bedroom Furniture",
    seoDescription: "Solid oak 2-door wardrobe with smoked glass inserts. 220 cm height. Bespoke interior fittings available. 3 finishes. India-wide delivery.",
    tags: ["bestseller", "subcategory:wardrobes"],
    description: "A wardrobe with the confidence to show what is inside — smoked glass doors that reveal, rather than conceal, the interior organisation.",
    metadata: {
      fullDescription: "The Haven Wardrobe challenges the assumption that wardrobes should be opaque. Its smoked glass door panels reveal the interior in soft silhouette — enough to locate items quickly, not enough to expose disorder. The solid oak frame is available in three finishes, and the interior can be configured with hanging rails, shelves, and pull-out drawers to a bespoke specification at the point of order.",
      features: [
        "Solid oak frame — not MDF or chipboard",
        "Smoked glass door panels — reveal-without-expose",
        "Bespoke interior configuration — shelves, rails, drawers",
        "220 cm height — full ceiling clearance in standard rooms",
        "Soft-close hinges throughout",
        "Integrated LED interior lighting (optional)",
        "3 exterior finishes — coordinate with bed range",
      ],
      care: "Wipe glass with glass cleaner. Oil oak frame annually. Lubricate hinges if they develop squeaks.",
      warranty: "10-year frame. 5-year hinge and fitting.",
      rating: 4.8, reviewCount: 87,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Haven Wardrobe in Natural Oak with smoked glass", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Haven — interior organisation detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WRD-002", slug: "cascade-sliding-wardrobe",
    name: "Cascade Sliding Wardrobe", categorySlug: "bedroom", subcategorySlug: "wardrobes",
    brand: "Modulas Originals", price: 545000, currency: "INR",
    material: "Solid Oak & Mirrored Glass", finishOptions: ["Natural Oak / Mirror", "White / Mirror", "Graphite / Mirror"],
    dimensions: { width: 180, height: 224, depth: 65, unit: "cm" }, weightKg: 162,
    isConfigurable: true, isFeatured: false, stockQty: 3, leadTimeDays: 56,
    seoTitle: "Cascade Sliding Door Wardrobe with Mirror — Modulas Bedroom",
    seoDescription: "180 cm sliding wardrobe with integrated full-length mirror doors. Solid oak frame. Bespoke interior. Soft-close top-hung sliding system.",
    tags: ["premium", "subcategory:wardrobes"],
    description: "Sliding doors with full-length mirror panels that open the room visually while concealing every inch of the wardrobe interior.",
    metadata: {
      fullDescription: "The Cascade uses a top-hung sliding door system — the doors glide on an overhead rail rather than a floor track, eliminating the floor channel that collects dust and creates a trip hazard. The full-length mirror doors multiply the light in any bedroom and make the space feel significantly larger. The interior is available in multiple configurations, including the option for a pull-out valet pole, LED lighting, and velvet-lined jewellery drawers.",
      features: [
        "Top-hung sliding doors — no floor track",
        "Full-length mirror panels — room-expanding",
        "Bespoke interior — rails, shelves, pull-out drawers, LED",
        "Optional velvet-lined jewellery drawer",
        "Optional pull-out valet pole",
        "Solid oak frame",
        "Soft-close door buffers",
      ],
      care: "Polish mirror with glass cleaner. Wipe oak with dry cloth. Clean door tracks quarterly.",
      warranty: "10-year frame. 7-year sliding mechanism.",
      rating: 4.7, reviewCount: 62,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Cascade Sliding Wardrobe with mirror doors", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Cascade — interior shelving detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WRD-003", slug: "prestige-three-door-wardrobe",
    name: "Prestige 3-Door Wardrobe", categorySlug: "bedroom", subcategorySlug: "wardrobes",
    brand: "Atelier Series", price: 448000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Dark Walnut", "Natural Walnut"],
    dimensions: { width: 150, height: 220, depth: 60, unit: "cm" }, weightKg: 138,
    isConfigurable: true, isFeatured: false, stockQty: 4, leadTimeDays: 49,
    seoTitle: "Prestige 3-Door Solid Walnut Wardrobe — Atelier Series Modulas",
    seoDescription: "3-door solid walnut wardrobe, 150 cm wide, 220 cm tall. Centre mirror option. Soft-close hinges. Bespoke interior. Ships in 49 days.",
    tags: ["premium", "subcategory:wardrobes"],
    description: "Solid walnut across three doors — the Prestige Wardrobe carries the weight of its material with elegance and precision.",
    metadata: {
      fullDescription: "The Prestige 3-Door Wardrobe is built in solid American black walnut — not walnut veneer over MDF. Its three-door configuration allows for a dedicated mirror panel in the centre (optional) flanked by solid walnut panels on either side. The interior is divided into two hanging zones and a central shelved section with four drawers at the base.",
      features: [
        "Solid American black walnut — full thickness",
        "Optional centre mirror panel",
        "Two hanging zones + central shelved section",
        "Four internal drawers at base — dovetail joinery",
        "Soft-close hinges — German-engineered",
        "220 cm height",
        "Bespoke interior configuration on request",
      ],
      care: "Oil walnut doors annually with Danish oil. Wipe with dry cloth. Lubricate hinges if required.",
      warranty: "10-year frame. 5-year hinge and fitting.",
      rating: 4.8, reviewCount: 45,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Prestige 3-Door Walnut Wardrobe", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Prestige — dovetail drawer detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WRD-004", slug: "luxe-walk-in-wardrobe-unit",
    name: "Luxe Walk-In Wardrobe System", categorySlug: "bedroom", subcategorySlug: "wardrobes",
    brand: "Heritage Collection", price: 895000, currency: "INR",
    material: "Solid Oak & Velvet Lining", finishOptions: ["Natural Oak", "Painted White"],
    dimensions: { width: 240, height: 220, depth: 55, unit: "cm" }, weightKg: 210,
    isConfigurable: true, isFeatured: false, stockQty: 1, leadTimeDays: 84,
    seoTitle: "Luxe Walk-In Wardrobe System — Heritage Collection Modulas",
    seoDescription: "Bespoke walk-in wardrobe system in solid oak. Velvet-lined drawers, LED lighting, pull-out rails, shoe display. Modulas Heritage Collection.",
    tags: ["premium", "limited", "subcategory:wardrobes"],
    description: "Not a wardrobe — a dressing room within a room. The Luxe Walk-In System transforms any large bedroom alcove into a personal atelier.",
    metadata: {
      fullDescription: "The Luxe Walk-In Wardrobe System is Modulas's most ambitious bedroom product — a complete 240 cm wide, 220 cm tall solid oak storage installation that functions as a walk-in dressing room. The standard configuration includes: a full-length hanging zone on the left, a double-hang zone for shirts and jackets on the right, four velvet-lined jewellery drawers, a pull-out valet pole, shoe display shelves with lighting, a central island unit (optional), and integrated LED strip lighting throughout.",
      features: [
        "240 cm width — full walk-in dressing room",
        "Full-height and double-height hanging zones",
        "4 velvet-lined jewellery drawers",
        "Illuminated shoe display shelves",
        "Pull-out valet pole",
        "Integrated LED strip lighting",
        "Optional island unit with additional drawers",
        "Bespoke to room dimensions — survey included",
      ],
      care: "Annual survey by Modulas technician recommended. Oil oak surfaces yearly. Wipe LED strips with dry cloth.",
      warranty: "Lifetime frame. 10-year fitting and mechanism.",
      rating: 5.0, reviewCount: 12,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Luxe Walk-In Wardrobe System in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Luxe — interior dressing room view", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Nightstands (4) ─────────────────────────────────────────────
  {
    sku: "MOD-NST-001", slug: "elara-walnut-nightstand",
    name: "Elara Walnut Nightstand", categorySlug: "bedroom", subcategorySlug: "nightstands",
    brand: "Modulas Originals", price: 58000, currency: "INR",
    material: "Solid Walnut & Cane", finishOptions: ["Natural Walnut", "Ebonised Walnut"],
    dimensions: { width: 52, height: 58, depth: 42, unit: "cm" }, weightKg: 14,
    isConfigurable: false, isFeatured: true, stockQty: 24, leadTimeDays: 14,
    seoTitle: "Elara Walnut & Cane Nightstand — Modulas Bedroom Furniture",
    seoDescription: "Solid walnut nightstand with cane drawer front. Integrated wireless charging pad. 52 cm wide, 58 cm tall. Ships in 14 days.",
    tags: ["bestseller", "subcategory:nightstands"],
    description: "Solid walnut with a cane-front drawer and an integrated wireless charging pad. The Elara anticipates the modern bedroom's needs.",
    metadata: {
      fullDescription: "The Elara Nightstand was designed to answer the two things every bedside table needs to do: store the essentials and charge the phone. Its single drawer has a cane-weave front that adds texture without weight, and the top surface conceals a Qi-standard wireless charging pad that keeps the surface clear of cables. The solid walnut body is joined with traditional drawer joinery — dovetail at the drawer, mortise-and-tenon at the frame.",
      features: [
        "Integrated Qi wireless charging pad — flush with surface",
        "Cane-weave drawer front",
        "Dovetail drawer joinery",
        "Solid walnut body — natural or ebonised",
        "Single shelf behind drawer",
        "Sold individually or as a pair with 5% discount",
        "Matches Elara bed frame range",
      ],
      care: "Oil walnut annually. Wipe wireless charging pad with dry cloth — do not use liquids. Clean cane with a soft brush.",
      warranty: "5-year frame. 2-year charging mechanism.",
      rating: 4.8, reviewCount: 267,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Elara Walnut Nightstand — natural finish", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Elara — wireless charging pad and cane detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-NST-002", slug: "soleil-floating-nightstand",
    name: "Soleil Floating Nightstand", categorySlug: "bedroom", subcategorySlug: "nightstands",
    brand: "Atelier Series", price: 42000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural Oak", "Whitened", "Smoked"],
    dimensions: { width: 45, height: 22, depth: 35, unit: "cm" }, weightKg: 7,
    isConfigurable: false, isFeatured: false, stockQty: 35, leadTimeDays: 10,
    seoTitle: "Soleil Floating Bedside Shelf — Atelier Series Modulas",
    seoDescription: "Wall-mounted solid oak floating nightstand. 45 cm wide. Invisible French cleat mount. 3 finishes. Suitable for low platform beds.",
    tags: ["new", "subcategory:nightstands"],
    description: "A floating solid oak bedside shelf that clears the floor entirely — ideal for low platform beds and for bedrooms where every centimetre counts.",
    metadata: {
      fullDescription: "The Soleil is Modulas's most minimal bedside solution — a single solid oak slab mounted to the wall on a concealed French cleat. The mounting system is invisible from the front, creating the appearance of a floating shelf. At 45 × 35 cm, it provides sufficient surface area for a lamp, phone, book, and glass of water — which is all a bedside table truly needs to do.",
      features: [
        "Solid oak — single-slab surface",
        "Concealed French cleat — invisible from front",
        "45 × 35 cm surface — sufficient for essentials",
        "3 oak finishes",
        "Suitable for walls with timber stud or masonry",
        "All fixings and instruction included",
        "Available as a pair — 5% discount",
      ],
      care: "Wipe with dry cloth. Oil annually. Do not place wet items directly on surface.",
      warranty: "5-year structural.",
      rating: 4.7, reviewCount: 184,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Soleil Floating Nightstand in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Soleil — wall-mounted view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-NST-003", slug: "mirage-two-drawer-nightstand",
    name: "Mirage 2-Drawer Nightstand", categorySlug: "bedroom", subcategorySlug: "nightstands",
    brand: "Modulas Originals", price: 68000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut"],
    dimensions: { width: 55, height: 62, depth: 45, unit: "cm" }, weightKg: 18,
    isConfigurable: false, isFeatured: false, stockQty: 18, leadTimeDays: 14,
    seoTitle: "Mirage 2-Drawer Solid Walnut Nightstand — Modulas",
    seoDescription: "Solid walnut 2-drawer nightstand. Dovetail drawers, soft-close. 55 cm wide, 62 cm tall. Pairs with Mirage bed and wardrobe range.",
    tags: ["subcategory:nightstands"],
    description: "Two deep drawers in solid walnut — the Mirage Nightstand stores significantly more than its proportions suggest.",
    metadata: {
      fullDescription: "The Mirage 2-Drawer Nightstand prioritises storage without sacrificing proportion. Its two drawers — both with full-extension soft-close runners — are unusually deep at 38 cm, making them genuinely useful for more than small items. The solid walnut body uses dovetail joinery at the drawers and mortise-and-tenon at the frame — traditional techniques that add structural integrity and visible craftsmanship.",
      features: [
        "Two full-extension soft-close drawers",
        "38 cm drawer depth — unusually generous",
        "Dovetail drawer and mortise-and-tenon frame joinery",
        "Solid walnut — no veneers",
        "55 cm wide — proportioned for a king-size bed",
        "Sold individually or as a pair",
        "Matches Mirage bed and wardrobe",
      ],
      care: "Oil walnut annually. Lubricate drawer runners with wax if needed.",
      warranty: "10-year frame. 5-year drawer mechanism.",
      rating: 4.8, reviewCount: 119,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Mirage 2-Drawer Nightstand in Natural Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Mirage — drawer open view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-NST-004", slug: "duo-marble-nightstand",
    name: "Duo Marble-Top Nightstand", categorySlug: "bedroom", subcategorySlug: "nightstands",
    brand: "Atelier Series", price: 85000, currency: "INR",
    material: "Marble & Solid Brass", finishOptions: ["Calacatta White / Brass", "Green Marble / Black", "Grey Marble / Brass"],
    dimensions: { width: 48, height: 55, depth: 38, unit: "cm" }, weightKg: 16,
    isConfigurable: false, isFeatured: false, stockQty: 12, leadTimeDays: 21,
    seoTitle: "Duo Marble Top Bedside Table — Atelier Series Modulas",
    seoDescription: "Marble-topped nightstand on solid brass frame. 3 marble and metal combinations. 48 cm wide. Single shelf. Ships in 21 days.",
    tags: ["premium", "subcategory:nightstands"],
    description: "A honed marble top on a solid brass hairpin frame — the Duo brings the language of the living room into the bedroom.",
    metadata: {
      fullDescription: "The Duo Nightstand introduces a materials palette more typically associated with a coffee table — honed marble and solid brass — into the bedroom. Its hairpin brass frame keeps the visual weight low, allowing the marble top to be the defining element. Three combinations are available: Calacatta White with brushed brass, Green Marble with matte black steel, and Grey Marble with brushed brass.",
      features: [
        "Honed marble top — 2 cm thick, pre-sealed",
        "Solid brass or matte steel hairpin frame",
        "Single lower shelf in matching marble",
        "48 cm width — appropriate for queen and king",
        "Available in 3 material combinations",
        "Marble care kit included",
        "Sold individually or as a pair",
      ],
      care: "Wipe marble with dry cloth. Re-seal annually. Polish brass with a soft dry cloth.",
      warranty: "5-year structural. 2-year marble sealing.",
      rating: 4.7, reviewCount: 78,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Duo Marble Nightstand — Calacatta and Brass", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Duo — marble surface and brass frame detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Dressers & Vanities (4) ─────────────────────────────────────
  {
    sku: "MOD-VAN-001", slug: "lumiere-vanity-dresser",
    name: "Lumière Vanity Dresser", categorySlug: "bedroom", subcategorySlug: "dressers-vanities",
    brand: "Atelier Series", price: 185000, currency: "INR",
    material: "Solid Oak & Mirror", finishOptions: ["Natural Oak", "Painted White"],
    dimensions: { width: 110, height: 145, depth: 45, unit: "cm" }, weightKg: 68,
    isConfigurable: true, isFeatured: false, stockQty: 9, leadTimeDays: 28,
    seoTitle: "Lumière Vanity Dresser with Mirror — Atelier Series Modulas",
    seoDescription: "Solid oak vanity dresser with integrated full-length mirror. LED halo lighting option. 4 drawers. 110 cm wide. Ships in 28 days.",
    tags: ["new", "subcategory:dressers-vanities"],
    description: "A full-length mirror and four generous drawers in solid oak — the Lumière Vanity turns the daily ritual of getting dressed into something worth doing slowly.",
    metadata: {
      fullDescription: "The Lumière Vanity is designed around the mirror — the most important element of any dressing table. Its full-length mirror panel (110 × 80 cm) is set in a solid oak surround that sits proud of the drawer unit below, creating a visual separation between the dressing mirror and the storage drawers. Optional LED halo lighting around the mirror frame gives even, shadow-free illumination for makeup application.",
      features: [
        "Full-length 110 × 80 cm mirror — oak surround",
        "Optional LED halo lighting — even, shadow-free",
        "4 drawers — dovetail joinery, soft-close",
        "Solid oak throughout",
        "Central drawer lined in velvet",
        "Available with or without matching stool",
        "Matching Haven wardrobe available",
      ],
      care: "Clean mirror with glass cleaner. Oil oak annually. Wipe LED frame with dry cloth.",
      warranty: "8-year frame. 2-year LED.",
      rating: 4.8, reviewCount: 104,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Lumière Vanity Dresser in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Lumière — LED mirror lighting detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-VAN-002", slug: "vogue-mirrored-chest",
    name: "Vogue Mirrored 6-Drawer Chest", categorySlug: "bedroom", subcategorySlug: "dressers-vanities",
    brand: "Modulas Originals", price: 148000, compareAtPrice: 178000, currency: "INR",
    material: "Lacquered MDF & Mirror Glass", finishOptions: ["Mirror / Gold", "Mirror / Silver", "Mirror / Black"],
    dimensions: { width: 90, height: 110, depth: 42, unit: "cm" }, weightKg: 62,
    isConfigurable: false, isFeatured: false, stockQty: 14, leadTimeDays: 21,
    seoTitle: "Vogue Mirrored 6-Drawer Chest — Modulas Bedroom Furniture",
    seoDescription: "6-drawer mirrored chest of drawers with bevelled glass and metal trim. 3 colourways. Doubles dressing room space visually.",
    tags: ["sale", "subcategory:dressers-vanities"],
    description: "Six drawers behind a mirrored facade — the Vogue Chest multiplies the room's light while providing substantial clothing storage.",
    metadata: {
      fullDescription: "The Vogue Mirrored Chest draws from the Art Deco tradition of the mirrored bedroom — a look that fell out of fashion and has returned stronger than ever in contemporary luxury interiors. Each drawer front is a bevelled mirror panel set in a metal frame (gold, silver, or black, depending on colourway). The drawers themselves are deep and wide — the top two are velvet-lined for delicate items.",
      features: [
        "6 mirrored drawer fronts — bevelled glass",
        "Metal frame trim — 3 colourways",
        "Top 2 drawers velvet-lined",
        "Full-extension soft-close runners",
        "Anti-tip wall anchor included",
        "90 cm wide — proportioned for a double or queen bedroom",
        "Matching mirrored side tables available",
      ],
      care: "Clean mirror panels with glass cleaner. Wipe metal frame with dry cloth. Avoid abrasive cleaners on mirror surface.",
      warranty: "5-year frame. 3-year runner mechanism.",
      rating: 4.6, reviewCount: 138,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Vogue Mirrored Chest in Mirror/Gold", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Vogue — bevelled glass drawer detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-VAN-003", slug: "clarity-vanity-table-set",
    name: "Clarity Vanity Table & Stool", categorySlug: "bedroom", subcategorySlug: "dressers-vanities",
    brand: "Atelier Series", price: 128000, currency: "INR",
    material: "Solid Oak & Boucle", finishOptions: ["Natural Oak / Ivory", "White Oak / Blush", "Smoked Oak / Stone"],
    dimensions: { width: 95, height: 78, depth: 48, unit: "cm" }, weightKg: 34,
    isConfigurable: false, isFeatured: false, stockQty: 10, leadTimeDays: 21,
    seoTitle: "Clarity Vanity Table and Stool Set — Atelier Series Modulas",
    seoDescription: "Solid oak vanity table and boucle stool set. Separate mirror available. 95 cm wide, 3 drawers. Ships together in 21 days.",
    tags: ["subcategory:dressers-vanities"],
    description: "A vanity table and boucle stool sold together — the Clarity Set is a complete dressing solution that coordinates naturally with the Atelier bed range.",
    metadata: {
      fullDescription: "The Clarity Vanity Table is designed to be paired with a wall mirror or a freestanding mirror rather than having an integrated one — giving flexibility in use and proportions. The solid oak table has three drawers (one large central, two narrow side drawers), and the matching boucle stool sits at the ideal height for use at the 78 cm table surface. The stool is upholstered in the same boucle fabrics as the Atelier sofa range.",
      features: [
        "Solid oak vanity table — 3 drawers",
        "Matching boucle stool — same fabric as Atelier sofas",
        "78 cm table height — comfortable seating position",
        "Designed for use with a separate or wall mirror",
        "3 fabric/frame combinations",
        "Sold as a set — table and stool",
        "Matching Atelier bed and nightstand available",
      ],
      care: "Oil oak annually. Spot-clean boucle stool with foam cleaner.",
      warranty: "5-year table frame. 3-year stool.",
      rating: 4.7, reviewCount: 93,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Clarity Vanity Table and Stool in Natural Oak/Ivory", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Clarity — stool and drawer detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-VAN-004", slug: "marble-top-dresser",
    name: "Marble-Top Dresser", categorySlug: "bedroom", subcategorySlug: "dressers-vanities",
    brand: "Heritage Collection", price: 245000, currency: "INR",
    material: "Marble & Solid Walnut", finishOptions: ["Calacatta / Walnut", "Grey Marble / Walnut", "Black Marble / Walnut"],
    dimensions: { width: 105, height: 88, depth: 48, unit: "cm" }, weightKg: 88,
    isConfigurable: false, isFeatured: false, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Marble-Top Dresser in Walnut — Heritage Collection Modulas",
    seoDescription: "Honed marble-top dresser on solid walnut frame. 4 dovetail drawers. Heritage Collection — limited production. 105 cm wide.",
    tags: ["premium", "limited", "subcategory:dressers-vanities"],
    description: "A honed marble surface on a solid walnut body — the Heritage Marble Dresser needs no mirror to make a statement.",
    metadata: {
      fullDescription: "The Heritage Marble Dresser references the great chest-of-drawers of the Georgian period — broad, confident, and built to outlast its owner. The honed marble top (2.5 cm thick) rests on a solid walnut body with four deep drawers in dovetail joinery. Three marble and walnut combinations are available: Calacatta White for luminous interiors, Grey Bardiglio for dramatic rooms, and Black Nero Marquina for maximalist spaces.",
      features: [
        "2.5 cm honed marble top — 3 marble options",
        "Solid walnut body — no MDF or veneer",
        "4 dovetail-joinery drawers",
        "Full-extension soft-close drawer runners",
        "Solid walnut bun feet",
        "Marble care kit and chalk wax included",
        "Heritage Collection — made in small batches",
      ],
      care: "Wipe marble with dry cloth immediately after use. Re-seal annually. Oil walnut body yearly.",
      warranty: "Lifetime frame. 5-year drawer mechanism. 1-year marble sealing.",
      rating: 4.9, reviewCount: 37,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85", altText: "Marble-Top Dresser in Calacatta/Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Marble Dresser — marble edge detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Bedroom Benches (2) ─────────────────────────────────────────
  {
    sku: "MOD-BNC-001", slug: "ivory-bedroom-bench",
    name: "Ivory Upholstered Bedroom Bench", categorySlug: "bedroom", subcategorySlug: "bedroom-benches",
    brand: "Modulas Originals", price: 68000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Ivory", "Stone", "Blush", "Charcoal"],
    dimensions: { width: 120, height: 48, depth: 38, unit: "cm" }, weightKg: 18,
    isConfigurable: false, isFeatured: false, stockQty: 22, leadTimeDays: 14,
    seoTitle: "Ivory Upholstered Bedroom Bench in Boucle — Modulas",
    seoDescription: "120 cm bedroom bench in boucle with solid oak legs. Ideal at the foot of any bed. 4 colourways. Ships in 14 days.",
    tags: ["subcategory:bedroom-benches"],
    description: "The finish that completes a bed. A boucle-upholstered bedroom bench on solid oak legs — the detail that turns a bedroom into a suite.",
    metadata: {
      fullDescription: "The Ivory Bedroom Bench is designed to sit at the foot of the bed and do three things well: look like it belongs there, provide a surface to sit on while dressing, and hold clothing laid out for the next day. At 120 cm, it proportions correctly with queen and king beds alike. The boucle upholstery coordinates with the Aurelia, Signature, and Atelier bed ranges.",
      features: [
        "120 cm length — proportioned for queen and king",
        "Boucle upholstery in 4 colourways",
        "High-density foam — retains shape",
        "Solid oak legs — tapered",
        "Non-slip felt base pads",
        "Coordinates with all Modulas bed upholstery",
        "Available 90 cm version for double beds",
      ],
      care: "Vacuum boucle with soft brush. Spot-clean with foam cleaner.",
      warranty: "5-year structural.",
      rating: 4.7, reviewCount: 198,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Ivory Bedroom Bench at foot of bed", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=85", altText: "Ivory Bench — boucle and leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BNC-002", slug: "leather-bedroom-bench",
    name: "Heritage Leather Bedroom Bench", categorySlug: "bedroom", subcategorySlug: "bedroom-benches",
    brand: "Heritage Collection", price: 95000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Cognac", "Black", "Tan", "Bordeaux"],
    dimensions: { width: 115, height: 48, depth: 42, unit: "cm" }, weightKg: 22,
    isConfigurable: false, isFeatured: false, stockQty: 8, leadTimeDays: 21,
    seoTitle: "Heritage Full-Grain Leather Bedroom Bench — Modulas",
    seoDescription: "Full-grain leather bedroom bench on solid walnut legs. Heritage Collection. 115 cm wide. 4 leather colourways.",
    tags: ["premium", "subcategory:bedroom-benches"],
    description: "Full-grain leather, solid walnut legs — the Heritage Leather Bench brings the same material quality as the Heritage Chesterfield to the foot of the bed.",
    metadata: {
      fullDescription: "The Heritage Leather Bench is the complement to the Imperial King or Heritage bed frames. Its full-grain leather upholstery is cut from the same hide selection as the Heritage Chesterfield sofa — ensuring that when paired, they share the same leather character. The solid walnut legs are tapered and match the walnut bun feet across the Heritage Collection.",
      features: [
        "Full-grain leather — same source as Heritage sofas",
        "Solid walnut tapered legs",
        "High-resilience foam core",
        "Hand-stitched leather seams",
        "115 cm width — proportioned for king",
        "Leather care kit included",
        "Part of Heritage Collection — coordinates across range",
      ],
      care: "Condition leather every 3 months. Wipe with dry cloth after use.",
      warranty: "5-year structural. 5-year leather.",
      rating: 4.8, reviewCount: 54,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=85", altText: "Heritage Leather Bench in Cognac", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=900&q=85", altText: "Heritage Bench — leather and walnut leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },
];
