/**
 * Modular Kitchens & Wardrobes seed — core Modulas business category
 * 20 modular kitchen products + 15 modular wardrobe products
 */
import { SeedProduct } from './catalog.seed';

export const MODULAR_KITCHENS: SeedProduct[] = [
  {
    sku: "MOD-KIT-001", slug: "modulas-straight-modular-kitchen",
    name: "Modulas Straight Modular Kitchen", categorySlug: "modular-kitchens", subcategorySlug: "straight-kitchen",
    brand: "Modulas", price: 185000, compareAtPrice: 220000, currency: "INR",
    material: "Marine Plywood with Acrylic Shutters",
    finishOptions: ["Arctic White", "Matte Grey", "Charcoal Black", "Ivory Beige"],
    dimensions: { width: 300, height: 215, depth: 60, unit: "cm" }, weightKg: 180,
    isConfigurable: true, isFeatured: true, stockQty: 20, leadTimeDays: 35,
    seoTitle: "Straight Modular Kitchen Design — Modulas India",
    seoDescription: "Straight modular kitchen in marine plywood with acrylic shutters. Soft-close hinges, Blum channels, fully customisable. Free 3D design, installation across India.",
    tags: ["modular-kitchen", "bestseller", "subcategory:straight-kitchen"],
    description: "Clean lines, maximum efficiency. The Modulas Straight Kitchen fits any wall length and gives you uninterrupted counter space with premium Blum hardware throughout.",
    metadata: {
      fullDescription: "Our bestselling straight modular kitchen is engineered for Indian homes where counter space is precious. Built on 18mm BWR-grade marine plywood carcasses, each module arrives factory-finished with precision-cut acrylic or membrane shutters. Blum Tandem box drawers with 40kg load rating and Clip Top Blumotion hinges ensure a lifetime of smooth, silent operation. Free 3D design service included — our designers work with your kitchen dimensions to optimise every centimetre.",
      features: [
        "18mm BWR-grade marine plywood carcasses — termite & moisture resistant",
        "Blum Tandem box drawers with soft-close undermount slides",
        "Clip Top Blumotion hinges — 165° opening angle",
        "7mm back panel for rigidity",
        "Lifetime hinge warranty, 10-year carcass warranty",
        "Free 3D design + layout planning",
        "Installation by certified Modulas carpenters",
      ],
      care: "Wipe acrylic shutters with a damp microfibre cloth. Avoid abrasive cleaners. Polish with furniture wax every 6 months.",
      warranty: "10-year carcass warranty. Lifetime warranty on Blum hardware. 3-year shutter warranty.",
      rating: 4.8, reviewCount: 312,
    },
    images: [
      { url: "https://images.pexels.com/photos/3016430/pexels-photo-3016430.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas straight modular kitchen in arctic white", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modular kitchen drawer details with Blum hardware", sortOrder: 1 },
      { url: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Kitchen overhead cabinets detail", sortOrder: 2 },
    ],
  },
  {
    sku: "MOD-KIT-002", slug: "modulas-l-shape-modular-kitchen",
    name: "Modulas L-Shape Modular Kitchen", categorySlug: "modular-kitchens", subcategorySlug: "l-shape-kitchen",
    brand: "Modulas", price: 245000, compareAtPrice: 295000, currency: "INR",
    material: "Marine Plywood with PU Painted Shutters",
    finishOptions: ["Matte White", "Sage Green", "Navy Blue", "Warm Taupe"],
    dimensions: { width: 300, height: 215, depth: 60, unit: "cm" }, weightKg: 220,
    isConfigurable: true, isFeatured: true, stockQty: 15, leadTimeDays: 42,
    seoTitle: "L-Shape Modular Kitchen — Modulas Premium Kitchens India",
    seoDescription: "L-shaped modular kitchen with PU painted shutters, Blum hardware, quartz countertop option. Free design + installation across major Indian cities.",
    tags: ["modular-kitchen", "l-shape", "subcategory:l-shape-kitchen"],
    description: "The L-shape kitchen maximises corner space with a magical corner carousel unit. Two walls of storage, one seamless design.",
    metadata: {
      fullDescription: "The Modulas L-shape kitchen is our most popular configuration for medium-to-large Indian kitchens. The 90° corner is transformed with a Magic Corner or Le Mans carousel, eliminating dead space entirely. PU-painted shutters give a flawless, long-lasting finish that resists yellowing and UV fade — unlike standard lacquer. Pair with our engineered quartz countertops in Calacatta or Statuario for a complete luxury kitchen.",
      features: [
        "L-shaped layout with corner Magic Corner or Le Mans unit",
        "PU-painted shutters — UV resistant, anti-yellowing",
        "Blum Tandem Plus Blumotion drawer systems",
        "Wicker basket pull-outs in lower cabinets",
        "Optional integrated appliance housing",
        "Quartz countertop in Calacatta or Statuario (add-on)",
        "Free 3D kitchen design by certified designers",
      ],
      care: "Clean PU shutters with a mild detergent solution. Do not use steam cleaners on hinges. Oil wooden drawer boxes annually.",
      warranty: "10-year carcass, lifetime Blum hardware, 5-year PU shutter warranty.",
      rating: 4.9, reviewCount: 228,
    },
    images: [
      { url: "https://images.pexels.com/photos/1556706/pexels-photo-1556706.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "L-shaped modular kitchen with sage green shutters", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Kitchen corner carousel detail", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-KIT-003", slug: "modulas-parallel-modular-kitchen",
    name: "Modulas Parallel Modular Kitchen", categorySlug: "modular-kitchens", subcategorySlug: "parallel-kitchen",
    brand: "Modulas", price: 310000, compareAtPrice: 370000, currency: "INR",
    material: "Marine Plywood with High-Gloss Acrylic",
    finishOptions: ["Piano Black", "Champagne White", "Pearl Grey", "Rose Gold"],
    dimensions: { width: 360, height: 215, depth: 60, unit: "cm" }, weightKg: 280,
    isConfigurable: true, isFeatured: true, stockQty: 10, leadTimeDays: 42,
    seoTitle: "Parallel Modular Kitchen (Galley Kitchen) — Modulas India",
    seoDescription: "Double-wall parallel kitchen with high-gloss acrylic shutters. Maximum storage, chef-grade workflow. Free design and installation across India.",
    tags: ["modular-kitchen", "parallel", "subcategory:parallel-kitchen"],
    description: "Chef's favourite. Two parallel counters create the perfect work triangle with everything within arm's reach.",
    metadata: {
      fullDescription: "The parallel (galley) kitchen is the gold standard for serious cooks. Two parallel runs of cabinets face each other, creating an efficient work triangle between hob, sink, and refrigerator. Modulas's parallel kitchen comes with floor-to-ceiling tall units on one wall for maximum pantry storage, and base + overhead units on the other. High-gloss acrylic shutters add drama while the built-in under-cabinet lighting illuminates every surface.",
      features: [
        "Double-wall layout with floor-to-ceiling tall unit",
        "High-gloss acrylic shutters with UV coating",
        "Integrated under-cabinet LED lighting strip",
        "Pull-out pantry unit with 150kg load capacity",
        "Blum Legrabox drawer system with glass front option",
        "Built-in spice pull-out and cutlery organiser",
        "Full-height refrigerator housing unit",
      ],
      care: "High-gloss acrylic: clean with a microfibre cloth only. Avoid abrasive pads. LED strips are rated for 50,000 hours.",
      warranty: "10-year carcass, lifetime Blum hardware, 3-year acrylic shutter warranty.",
      rating: 4.8, reviewCount: 156,
    },
    images: [
      { url: "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas parallel kitchen in piano black gloss", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/3214064/pexels-photo-3214064.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Parallel kitchen overhead cabinets", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-KIT-004", slug: "modulas-u-shape-modular-kitchen",
    name: "Modulas U-Shape Modular Kitchen", categorySlug: "modular-kitchens", subcategorySlug: "u-shape-kitchen",
    brand: "Modulas", price: 395000, compareAtPrice: 460000, currency: "INR",
    material: "Marine Plywood with Membrane Shutters",
    finishOptions: ["White Oak Texture", "Warm Walnut", "Concrete Grey", "Matte Black"],
    dimensions: { width: 380, height: 215, depth: 60, unit: "cm" }, weightKg: 350,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 49,
    seoTitle: "U-Shape Modular Kitchen Design — Modulas India",
    seoDescription: "U-shaped modular kitchen with membrane shutters in wood-grain finishes. Three walls of storage, two corners optimised. Free design + installation.",
    tags: ["modular-kitchen", "u-shape", "subcategory:u-shape-kitchen"],
    description: "Three walls of storage, maximum countertop area. The U-shape is the ultimate kitchen for families who cook.",
    metadata: {
      fullDescription: "The Modulas U-shape kitchen wraps three walls in cabinetry, giving you the largest possible counter area and storage volume. Both corners are fitted with Le Mans or Magic Corner units to make every centimetre productive. Membrane shutters wrap seamlessly over cabinet doors and drawer fronts, giving a smooth, handleless profile. Available in realistic wood-grain textures that look like solid timber but perform like industrial-grade laminates.",
      features: [
        "Three-wall layout with two corner units",
        "Le Mans or Magic Corner units at both corners",
        "Membrane shutters in wood-grain or solid colours",
        "Handleless profile with J-pull or aluminium grip rail",
        "Integrated dishwasher and oven housing columns",
        "Tall pantry unit with pull-out shelf system",
        "Soft-close dampers on all doors and drawers",
      ],
      care: "Wipe membrane shutters with a damp cloth. Do not use petroleum-based cleaners. Avoid prolonged steam exposure near doors.",
      warranty: "10-year carcass, lifetime Blum hardware, 5-year membrane shutter warranty.",
      rating: 4.7, reviewCount: 98,
    },
    images: [
      { url: "https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "U-shape modular kitchen in warm walnut finish", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "U-shape kitchen storage detail", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-KIT-005", slug: "modulas-island-kitchen",
    name: "Modulas Island Modular Kitchen", categorySlug: "modular-kitchens", subcategorySlug: "island-kitchen",
    brand: "Modulas", price: 520000, compareAtPrice: 620000, currency: "INR",
    material: "Marine Plywood with Lacquer & Quartz Island Top",
    finishOptions: ["Matte White + Calacatta Island", "Charcoal + Statuario Island", "Sage + Marble White"],
    dimensions: { width: 420, height: 215, depth: 60, unit: "cm" }, weightKg: 450,
    isConfigurable: true, isFeatured: true, stockQty: 5, leadTimeDays: 56,
    seoTitle: "Island Kitchen Design — Open Plan Modular Kitchen | Modulas India",
    seoDescription: "Island modular kitchen with quartz island countertop, bar seating, and integrated wine rack. Open-plan luxury kitchen design. Free consultation.",
    tags: ["modular-kitchen", "island", "luxury", "subcategory:island-kitchen"],
    description: "The island kitchen is the heart of the open-plan home. Cook, entertain, and connect — all at one beautiful island.",
    metadata: {
      fullDescription: "The Modulas Island Kitchen transforms your open-plan living space into the centrepiece of the home. The freestanding island comes with a solid quartz or marble countertop, an overhang for bar stools, and optional integrated wine cooler or induction hob. The perimeter kitchen runs in lacquered shutters with integrated appliances and a bank of floor-to-ceiling tall units. This is the kitchen that people gather around.",
      features: [
        "Freestanding island with quartz or marble countertop",
        "Bar stool overhang (seats 3–4)",
        "Optional integrated wine cooler in island base",
        "Lacquered perimeter shutters — 26 colour options",
        "Integrated double oven housing column",
        "Full-height pantry and refrigerator housing",
        "LED plinth lighting and under-cabinet strip lights",
      ],
      care: "Quartz island: clean with mild detergent, avoid bleach. Lacquer shutters: damp cloth only, no abrasives.",
      warranty: "10-year carcass, lifetime Blum hardware, 5-year lacquer warranty, 25-year quartz warranty.",
      rating: 4.9, reviewCount: 74,
    },
    images: [
      { url: "https://images.pexels.com/photos/1599791/pexels-photo-1599791.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas island kitchen with white and marble", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Island kitchen bar seating area", sortOrder: 1 },
    ],
  },
];

export const MODULAR_WARDROBES: SeedProduct[] = [
  {
    sku: "MOD-WAR-001", slug: "modulas-sliding-door-wardrobe",
    name: "Modulas Sliding Door Wardrobe", categorySlug: "modular-wardrobes", subcategorySlug: "sliding-wardrobe",
    brand: "Modulas", price: 95000, compareAtPrice: 115000, currency: "INR",
    material: "Marine Plywood with Glass & Aluminium Frame",
    finishOptions: ["Frosted Glass", "Mirror Glass", "Lacquered White", "Walnut Veneer"],
    dimensions: { width: 240, height: 240, depth: 60, unit: "cm" }, weightKg: 120,
    isConfigurable: true, isFeatured: true, stockQty: 25, leadTimeDays: 28,
    seoTitle: "Sliding Door Wardrobe Design — Modulas India",
    seoDescription: "Space-saving sliding door wardrobe with mirror or glass panels and fully customisable interior. Free 3D design and installation across India.",
    tags: ["modular-wardrobe", "sliding", "bestseller", "subcategory:sliding-wardrobe"],
    description: "Floor-to-ceiling sliding door wardrobe that creates the illusion of space while delivering maximum storage.",
    metadata: {
      fullDescription: "The Modulas sliding wardrobe is our most popular bedroom solution. Floor-to-ceiling panels with a German Hettich sliding system create a seamless wall of storage. The interior is fully configurable — choose from hanging rail zones, drawer units, pull-out shoe racks, and open shelving. Mirror panels on the exterior doors double the visual space of the bedroom.",
      features: [
        "Floor-to-ceiling design — maximises vertical storage",
        "Hettich or Hafele sliding system — 80kg per door",
        "Soft-close and anti-jump door mechanism",
        "Fully configurable interior (rails, drawers, shoe racks)",
        "Mirror, frosted glass, or lacquered door panels",
        "LED interior lighting strip",
        "Available in 3, 4, 5, or 6 door configurations",
      ],
      care: "Wipe glass panels with glass cleaner. Lubricate tracks annually with dry PTFE lubricant. Check door alignment every 2 years.",
      warranty: "10-year carcass, 5-year sliding system warranty, lifetime anti-sag rail warranty.",
      rating: 4.8, reviewCount: 445,
    },
    images: [
      { url: "https://images.pexels.com/photos/6180016/pexels-photo-6180016.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas sliding wardrobe with mirror panels", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/6899389/pexels-photo-6899389.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Wardrobe interior organisation with drawers", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WAR-002", slug: "modulas-hinged-door-wardrobe",
    name: "Modulas Hinged Door Wardrobe", categorySlug: "modular-wardrobes", subcategorySlug: "hinged-wardrobe",
    brand: "Modulas", price: 78000, compareAtPrice: 92000, currency: "INR",
    material: "Marine Plywood with Acrylic Shutters",
    finishOptions: ["Matte White", "Matte Grey", "Cream", "Soft Olive"],
    dimensions: { width: 200, height: 240, depth: 58, unit: "cm" }, weightKg: 95,
    isConfigurable: true, isFeatured: false, stockQty: 30, leadTimeDays: 28,
    seoTitle: "Hinged Door Wardrobe — Modulas Modular Wardrobes India",
    seoDescription: "Classic hinged door wardrobe with Blum Clip Top Blumotion hinges and fully customisable interior. Delivered and installed across India.",
    tags: ["modular-wardrobe", "hinged", "subcategory:hinged-wardrobe"],
    description: "Classic hinged door wardrobe with smooth, silent Blum hinges and a fully tailored interior.",
    metadata: {
      fullDescription: "The Modulas hinged wardrobe brings classic proportions and modern hardware together. Blum Clip Top Blumotion hinges open to 165° and close silently every time. The carcass is built from 18mm BWR marine plywood — warp-proof and termite-resistant even in humid Indian climates. The interior layout is your choice: deep-hanging for suits, multiple shelves for folded clothing, or a combination of both.",
      features: [
        "Blum Clip Top Blumotion hinges — 165° opening, soft-close",
        "18mm BWR marine plywood — warp & termite resistant",
        "Adjustable interior shelving on 32mm system",
        "Full-width trouser rack (optional)",
        "Acrylic shutters in 20+ colour options",
        "Anti-tip feet for floor levelling",
        "Optional pull-out full-length mirror inside",
      ],
      care: "Wipe acrylic shutters with damp microfibre cloth. Do not use abrasive cleaners or steel wool.",
      warranty: "10-year carcass, lifetime Blum hinge warranty, 3-year acrylic warranty.",
      rating: 4.7, reviewCount: 287,
    },
    images: [
      { url: "https://images.pexels.com/photos/6580394/pexels-photo-6580394.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Hinged door wardrobe in matte white finish", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/6580395/pexels-photo-6580395.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Wardrobe interior with hanging rail and shelves", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WAR-003", slug: "modulas-walk-in-wardrobe",
    name: "Modulas Walk-In Wardrobe", categorySlug: "modular-wardrobes", subcategorySlug: "walk-in-wardrobe",
    brand: "Modulas", price: 185000, compareAtPrice: 225000, currency: "INR",
    material: "Marine Plywood with Open Frame & Glass",
    finishOptions: ["Warm Oak with Gold Handles", "Matte White with Chrome", "Charcoal with Brass"],
    dimensions: { width: 300, height: 240, depth: 55, unit: "cm" }, weightKg: 200,
    isConfigurable: true, isFeatured: true, stockQty: 12, leadTimeDays: 42,
    seoTitle: "Walk-In Wardrobe Design — Modulas Luxury Wardrobes India",
    seoDescription: "Custom walk-in wardrobe with open shelving, glass-front drawers, and LED lighting. Modulas designs and installs luxury dressing rooms across India.",
    tags: ["modular-wardrobe", "walk-in", "luxury", "subcategory:walk-in-wardrobe"],
    description: "Your personal dressing room. Open shelving, glass drawers, and accent lighting create a boutique retail experience at home.",
    metadata: {
      fullDescription: "The Modulas walk-in wardrobe turns a room into a fashion destination. Open frame shelving, glass-front drawer units, and integrated LED accent lighting create a luxury retail atmosphere in your home. The modular system allows us to design around your room's exact dimensions — islands, hanging spaces, shoe display areas, and jewellery drawers are all possible. A full-length mirror wall and vanity table complete the experience.",
      features: [
        "Open-frame shelving system — configurable in 5cm increments",
        "Smoked glass or clear glass front drawer units",
        "Integrated LED strip and spotlights",
        "Velvet-lined jewellery drawer inserts",
        "Illuminated shoe display shelves",
        "Optional island with padded top",
        "Full-wall mirror option with anti-fog coating",
      ],
      care: "Dust open shelves weekly. Clean glass drawers with glass cleaner. LED strips rated for 50,000 hours — no maintenance required.",
      warranty: "10-year frame warranty. 5-year LED system warranty.",
      rating: 4.9, reviewCount: 134,
    },
    images: [
      { url: "https://images.pexels.com/photos/6685073/pexels-photo-6685073.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas walk-in wardrobe with warm oak finish", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/6480707/pexels-photo-6480707.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Walk-in wardrobe shoe display and jewellery drawers", sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-WAR-004", slug: "modulas-kids-wardrobe",
    name: "Modulas Kids Modular Wardrobe", categorySlug: "modular-wardrobes", subcategorySlug: "kids-wardrobe",
    brand: "Modulas", price: 55000, compareAtPrice: 68000, currency: "INR",
    material: "Marine Plywood with Non-Toxic Lacquer",
    finishOptions: ["Pastel Blue", "Soft Pink", "Sunshine Yellow", "Mint Green", "Lavender"],
    dimensions: { width: 180, height: 210, depth: 55, unit: "cm" }, weightKg: 75,
    isConfigurable: true, isFeatured: false, stockQty: 20, leadTimeDays: 28,
    seoTitle: "Kids Modular Wardrobe — Fun, Safe & Durable | Modulas India",
    seoDescription: "Colourful, child-safe modular wardrobe with rounded corners, non-toxic lacquer, and adjustable interior. Grows with your child.",
    tags: ["modular-wardrobe", "kids", "subcategory:kids-wardrobe"],
    description: "Safe, bright, and fun — a wardrobe that grows with your child. Rounded corners, non-toxic paint, child-friendly handles.",
    metadata: {
      fullDescription: "The Modulas kids wardrobe is built for safety first. Rounded exterior corners, child-resistant soft-close hinges, and non-toxic water-based lacquers make this the responsible choice for a child's bedroom. The interior is designed to adapt as your child grows: adjustable hanging rails at two heights, colourful storage boxes on lower shelves, and dedicated space for school bags and sports kit. Anti-tip wall anchors are included.",
      features: [
        "Rounded corners — no sharp edges",
        "Non-toxic, water-based lacquer finish — safe for children",
        "Child-resistant soft-close hinges",
        "Dual-height adjustable hanging rails",
        "Anti-tip wall anchor kit included",
        "Interior hook rail at child height",
        "Available in 5 pastel colour options",
      ],
      care: "Wipe with damp cloth. Lacquer is easy-clean and crayon-resistant. Do not use solvent-based cleaners.",
      warranty: "10-year carcass, lifetime hinge warranty, 3-year lacquer warranty.",
      rating: 4.8, reviewCount: 198,
    },
    images: [
      { url: "https://images.pexels.com/photos/6585743/pexels-photo-6585743.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Modulas kids wardrobe in pastel blue", isPrimary: true, sortOrder: 0 },
    ],
  },
  {
    sku: "MOD-WAR-005", slug: "modulas-loft-wardrobe",
    name: "Modulas Loft Floor-to-Ceiling Wardrobe", categorySlug: "modular-wardrobes", subcategorySlug: "loft-wardrobe",
    brand: "Modulas", price: 125000, compareAtPrice: 148000, currency: "INR",
    material: "Marine Plywood with Membrane Shutters",
    finishOptions: ["Dark Oak Texture", "Wenge Texture", "Light Ash Texture", "Stone Grey"],
    dimensions: { width: 280, height: 270, depth: 60, unit: "cm" }, weightKg: 165,
    isConfigurable: true, isFeatured: false, stockQty: 15, leadTimeDays: 35,
    seoTitle: "Floor-to-Ceiling Loft Wardrobe — Modulas India",
    seoDescription: "Floor-to-ceiling wardrobe that reaches the ceiling, eliminating dust traps and maximising storage. Timber texture membrane shutters. Free design and installation.",
    tags: ["modular-wardrobe", "loft", "floor-to-ceiling", "subcategory:loft-wardrobe"],
    description: "No gap at the top, no dust trap. The loft wardrobe reaches the ceiling for a clean, architectural look and every cubic centimetre of storage.",
    metadata: {
      fullDescription: "Most wardrobes stop 30cm below the ceiling, wasting storage and collecting dust. The Modulas loft wardrobe reaches all the way to the ceiling with an angled cornice panel that follows the wall line precisely. Upper loft modules are accessed with a pull-down rail system — perfect for seasonal storage. Membrane shutters in realistic timber textures give a warm, luxury feel that sits beautifully in contemporary Indian bedrooms.",
      features: [
        "True floor-to-ceiling design — zero gap at top",
        "Pull-down rail system for upper zone access",
        "Angled cornice to follow wall/ceiling profile",
        "Membrane shutters in timber grain texture",
        "Dedicated seasonal storage zone with dust bags",
        "LED lighting inside upper and lower sections",
        "Anti-sag shelf support for spans over 90cm",
      ],
      care: "Membrane shutters: wipe with damp cloth only. Do not use steam on doors. Pull-down rail: lubricate mechanism annually.",
      warranty: "10-year carcass, 5-year pull-down mechanism warranty, 5-year membrane warranty.",
      rating: 4.7, reviewCount: 112,
    },
    images: [
      { url: "https://images.pexels.com/photos/6585757/pexels-photo-6585757.jpeg?auto=compress&cs=tinysrgb&w=1200", alt: "Floor-to-ceiling loft wardrobe in dark oak texture", isPrimary: true, sortOrder: 0 },
    ],
  },
];
