import { SeedProduct } from './catalog.seed';

export const LIVING_ROOM: SeedProduct[] = [
  // ── Coffee Tables (6) ────────────────────────────────────────────────────
  {
    sku: 'LIV-CT-001',
    slug: 'travertine-oval-coffee-table',
    name: 'Travertine Oval Coffee Table',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 185000,
    compareAtPrice: 220000,
    currency: 'INR',
    material: 'Honed Italian travertine top with polished brass base',
    finishOptions: ['Classic Travertine / Polished Brass', 'Walnut Travertine / Brushed Bronze'],
    dimensions: { width: 130, height: 38, depth: 80, unit: 'cm' },
    weightKg: 72,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 6,
    leadTimeDays: 28,
    seoTitle: 'Travertine Oval Coffee Table – Italian Stone & Brass | Modulas',
    seoDescription: 'A honed Italian travertine oval top on a hand-polished brass sculptural base. The Travertine Oval Coffee Table is the centrepiece a luxury living room deserves.',
    tags: ['coffee-table', 'travertine', 'brass', 'oval', 'stone', 'subcategory:coffee-tables'],
    description: 'The Travertine Oval Coffee Table pairs a honed Italian travertine slab with a sculptural polished brass base — a masterclass in material contrast and tectonic beauty.',
    metadata: {
      fullDescription: 'Quarried from the hillside deposits of Tivoli, Italy, where travertine has been extracted since Roman antiquity, the stone top of this coffee table arrives honed to a silken, matte finish that reveals the fossil-rich internal structure of the stone. Each slab is unique — no two tables are identical. The brass base is hand-fabricated from solid brass tube, welded into three interlocking arcs, then hand-polished to a warm mirror finish before receiving a clear lacquer coat to retard tarnishing. A recessed felt pad under the stone protects the brass structure. The result is a coffee table that functions equally well as a sculpture.',
      features: [
        'Honed Italian travertine — unique natural stone slab',
        'Hand-fabricated solid brass three-arc base',
        'Hand-polished and lacquer-protected brass',
        'Recessed felt protection between stone and base',
        'Each piece unique due to natural stone variation',
        'Available in two stone and finish combinations',
      ],
      care: 'Wipe stone with a damp cloth and pH-neutral cleaner. Avoid acidic liquids (lemon, wine) directly on travertine. Dust brass base with a soft dry cloth.',
      warranty: '5 years structural, lifetime stone guarantee against manufacturing defects',
      rating: 4.9,
      reviewCount: 38,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Travertine Oval Coffee Table with brass base', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900', alt: 'Travertine Coffee Table — stone detail' },
    ],
  },
  {
    sku: 'LIV-CT-002',
    slug: 'cascade-walnut-coffee-table',
    name: 'Cascade Walnut Coffee Table',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 125000,
    compareAtPrice: 148000,
    currency: 'INR',
    material: 'Solid walnut with waterfall edge and hairpin steel legs',
    finishOptions: ['Natural Walnut', 'Smoked Walnut'],
    dimensions: { width: 120, height: 40, depth: 65, unit: 'cm' },
    weightKg: 48,
    isConfigurable: false,
    isFeatured: true,
    stockQty: 10,
    leadTimeDays: 21,
    seoTitle: 'Cascade Walnut Coffee Table – Solid Walnut Waterfall Edge | Modulas',
    seoDescription: 'The Cascade Coffee Table showcases solid walnut in a striking waterfall edge construction — the grain flows continuously from top to side in a seamless, sculptural form.',
    tags: ['coffee-table', 'walnut', 'waterfall-edge', 'solid-wood', 'subcategory:coffee-tables'],
    description: 'The Cascade Coffee Table celebrates walnut at its most expressive — a waterfall edge construction where the grain flows uninterrupted from the top surface down through the vertical sides.',
    metadata: {
      fullDescription: 'The waterfall edge is one of furniture\'s most technically demanding joints — the grain must align perfectly across the mitred corner so the wood appears to flow continuously, like water over a precipice. The Cascade Coffee Table achieves this with matched walnut panels sourced from a single tree, ensuring grain continuity across all three surfaces. The top and two waterfall ends form a self-supporting U-section; four slender hairpin legs in hand-blackened steel provide the remaining support at a visually minimal footprint. The surface receives a hard-wax oil finish that highlights the depth of walnut\'s natural figure.',
      features: [
        'Solid walnut waterfall edge — grain-matched across all three faces',
        'Sourced from single-tree matched panels',
        'Four hand-blackened steel hairpin legs',
        'Hard-wax oil finish for natural depth',
        'Felt foot pads to protect flooring',
      ],
      care: 'Wipe with a slightly damp cloth. Re-apply hard-wax oil annually. Use coasters to prevent water rings.',
      warranty: '5 years structural',
      rating: 4.8,
      reviewCount: 52,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Cascade Walnut Coffee Table waterfall edge', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CT-003',
    slug: 'noir-marble-coffee-table',
    name: 'Noir Marble Coffee Table',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 245000,
    compareAtPrice: 285000,
    currency: 'INR',
    material: 'Nero Marquina marble top with matte black steel frame',
    finishOptions: ['Nero Marquina / Matte Black Steel', 'Calacatta / Polished Gold Steel'],
    dimensions: { width: 110, height: 36, depth: 110, unit: 'cm' },
    weightKg: 95,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 4,
    leadTimeDays: 35,
    seoTitle: 'Noir Marble Coffee Table – Nero Marquina | Modulas',
    seoDescription: 'Nero Marquina marble — dramatic black with white veining — on a precisely welded matte black steel frame. The Noir Coffee Table is a statement of controlled opulence.',
    tags: ['coffee-table', 'marble', 'nero-marquina', 'black', 'luxury', 'subcategory:coffee-tables'],
    description: 'Controlled opulence in black and white. The Noir Marble Coffee Table presents a Nero Marquina slab — deep black stone with dramatic white veining — on a precisely welded matte black steel frame.',
    metadata: {
      fullDescription: 'Nero Marquina is among the world\'s most theatrically beautiful marbles — quarried in the Basque Country of Spain, its near-black ground is traversed by veins of brilliant white calcite that appear almost luminescent against the dark ground. The 20 mm polished slab is bookmatched from a single block, so the white veining mirrors itself across the central seam. The frame is fabricated from 40 × 20 mm rectangular steel section, TIG-welded and satin-powder-coated in matte black. Levelling feet at each corner accommodate uneven floors.',
      features: [
        'Nero Marquina marble — bookmatched from single block',
        '20 mm polished slab with mirrored white veining',
        'TIG-welded 40 × 20 mm steel section frame',
        'Satin matte black powder-coat finish on steel',
        'Four adjustable levelling feet',
        'Available in Calacatta / Gold Steel variant',
      ],
      care: 'Wipe with a damp cloth and pH-neutral cleaner. Seal marble annually with a penetrating stone sealer. Avoid acidic substances.',
      warranty: '5 years structural, lifetime stone guarantee',
      rating: 4.9,
      reviewCount: 29,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Noir Marble Coffee Table with black frame', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CT-004',
    slug: 'rio-rattan-coffee-table',
    name: 'Rio Rattan Coffee Table',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 68000,
    compareAtPrice: 82000,
    currency: 'INR',
    material: 'Hand-woven rattan on solid teak frame with tempered glass top',
    finishOptions: ['Natural Rattan', 'Bleached Rattan'],
    dimensions: { width: 100, height: 42, depth: 60, unit: 'cm' },
    weightKg: 18,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 22,
    leadTimeDays: 14,
    seoTitle: 'Rio Rattan Coffee Table – Hand-Woven with Glass Top | Modulas',
    seoDescription: 'The Rio Rattan Coffee Table combines hand-woven rattan on a solid teak frame with a clear tempered glass top — a warm, textural centrepiece with a contemporary finish.',
    tags: ['coffee-table', 'rattan', 'teak', 'glass', 'natural', 'subcategory:coffee-tables'],
    description: 'Warmth, texture, and lightness converge in the Rio Rattan Coffee Table — hand-woven rattan panels on a solid teak frame, topped with 8 mm tempered glass.',
    metadata: {
      fullDescription: 'The Rio Rattan Coffee Table brings the warmth and texture of natural craft to the modern living room. Rattan strands — sourced from certified Indonesian plantations and hand-split to uniform width — are woven by skilled artisans across a structural solid teak frame in a close herringbone pattern. An 8 mm clear tempered glass top protects the weave while maintaining visual access to its texture. The solid teak structure is finished with a natural teak oil that enhances its honey-amber tone. Rubber grip discs hold the glass in place without requiring fixings.',
      features: [
        'Hand-woven rattan panels in herringbone pattern',
        'Certified Indonesian rattan — sustainably sourced',
        'Solid teak frame, natural oil finish',
        '8 mm tempered clear glass top',
        'Rubber grip discs for glass — no fixings required',
      ],
      care: 'Dust rattan with a soft brush. Wipe glass with a streak-free glass cleaner. Apply teak oil to frame every 12 months.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 64,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Rio Rattan Coffee Table in natural finish', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CT-005',
    slug: 'arc-glass-coffee-table',
    name: 'Arc Glass Coffee Table',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 155000,
    compareAtPrice: 180000,
    currency: 'INR',
    material: 'Curved tempered smoked glass with brushed chrome base',
    finishOptions: ['Smoked Glass / Brushed Chrome', 'Clear Glass / Polished Gold'],
    dimensions: { width: 115, height: 38, depth: 60, unit: 'cm' },
    weightKg: 42,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 8,
    leadTimeDays: 21,
    seoTitle: 'Arc Glass Coffee Table – Smoked Glass & Chrome | Modulas',
    seoDescription: 'The Arc Glass Coffee Table pairs a curved 12 mm smoked tempered glass top with a sculptural brushed chrome base — pure contemporary luxury.',
    tags: ['coffee-table', 'glass', 'chrome', 'contemporary', 'smoked', 'subcategory:coffee-tables'],
    description: 'The Arc Glass Coffee Table is pure material confidence — a 12 mm curved smoked tempered glass top balanced on a sculptural brushed chrome oval base.',
    metadata: {
      fullDescription: 'Precision-curved from 12 mm tempered smoked glass using a specialised hot-bending process, the Arc Glass Coffee Table top achieves a gentle concave curvature that appears to float. All edges are polished to a seamless C-profile. The base is hand-formed from 316-grade stainless steel tube, shaped into a low oval arch and given a brushed chrome surface treatment. Three discreet rubber pads on the base cradle the glass without any visible fixings. The visual effect — stone-dark glass hovering above a chrome arch — is one of architectural lightness.',
      features: [
        '12 mm hot-bent tempered smoked glass, polished C-profile edge',
        'Sculptural 316-grade stainless steel oval arch base',
        'Brushed chrome surface treatment on base',
        'Three rubber cradle pads — no visible fixings',
        'Available in clear glass / polished gold variant',
      ],
      care: 'Clean glass with a streak-free glass cleaner and a microfibre cloth. Polish chrome base with a specialist chrome cleaner monthly.',
      warranty: '5 years structural, 3 years glass integrity guarantee',
      rating: 4.7,
      reviewCount: 24,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Arc Glass Coffee Table in smoked glass', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CT-006',
    slug: 'nest-side-and-coffee-table-set',
    name: 'Nest Side & Coffee Table Set',
    categorySlug: 'living',
    subcategorySlug: 'coffee-tables',
    brand: 'Modulas Atelier',
    price: 95000,
    compareAtPrice: 115000,
    currency: 'INR',
    material: 'Set of 3 — solid oak nesting tables',
    finishOptions: ['Natural Oak', 'Black Oak', 'White Oak'],
    dimensions: { width: 90, height: 40, depth: 55, unit: 'cm' },
    weightKg: 28,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 16,
    leadTimeDays: 14,
    seoTitle: 'Nest Side & Coffee Table Set – 3-Piece Solid Oak | Modulas',
    seoDescription: 'Three solid oak nesting tables that stack together as a coffee table or fan out as individual side tables — the most versatile living room surface set Modulas offers.',
    tags: ['coffee-table', 'side-table', 'nesting', 'oak', 'set', 'subcategory:coffee-tables'],
    description: 'Three solid oak nesting tables — stackable as a coffee table centrepiece, or fanned out to serve an entire sofa arrangement. Versatility without visual compromise.',
    metadata: {
      fullDescription: 'The Nest set comprises three progressively sized solid oak tables that nest beneath one another precisely, with 5 mm clearance between each surface. Used as a stack, they form a unified coffee table with a striking stepped silhouette. Separated, the two smaller tables serve as side tables at armchair height — each fully structural, with four solid oak legs. All three share the same leg profile and table edge treatment for visual coherence when spread across a room. Available in natural, black-stained, or white-oiled oak.',
      features: [
        'Set of 3 — large, medium, small nesting tables',
        'All solid oak — no veneers or composites',
        'Uniform leg profile across all three pieces',
        'Use stacked as one table or separated as three',
        'Available in natural, black, or white oak',
      ],
      care: 'Wipe with a damp cloth. Re-oil with natural oak oil every 12–18 months to maintain colour depth.',
      warranty: '3 years structural',
      rating: 4.8,
      reviewCount: 77,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Nest Nesting Tables in natural oak', isPrimary: true },
    ],
  },

  // ── Side Tables (5) ──────────────────────────────────────────────────────
  {
    sku: 'LIV-ST-001',
    slug: 'arc-brass-side-table',
    name: 'Arc Brass Side Table',
    categorySlug: 'living',
    subcategorySlug: 'side-tables',
    brand: 'Modulas Atelier',
    price: 48000,
    compareAtPrice: 58000,
    currency: 'INR',
    material: 'Hand-spun solid brass with circular top',
    finishOptions: ['Polished Brass', 'Brushed Brass', 'Antique Brass'],
    dimensions: { width: 40, height: 55, depth: 40, unit: 'cm' },
    weightKg: 8,
    isConfigurable: false,
    isFeatured: true,
    stockQty: 20,
    leadTimeDays: 14,
    seoTitle: 'Arc Brass Side Table – Hand-Spun Solid Brass | Modulas',
    seoDescription: 'The Arc Brass Side Table is a single sculptural statement — hand-spun solid brass in an arched tripod form. A perfect accent beside any sofa or armchair.',
    tags: ['side-table', 'brass', 'sculptural', 'accent', 'subcategory:side-tables'],
    description: 'A single, bold sculptural gesture — the Arc Brass Side Table is hand-spun from solid brass, its three arching legs meeting at a circular top in a form that is pure, restrained luxury.',
    metadata: {
      fullDescription: 'The Arc Brass Side Table is made in a single foundry in Moradabad, Uttar Pradesh, where brass-smithing traditions date back four centuries. Each leg is individually hand-spun on a lathe from solid brass rod, then hand-bent to the precise arc angle. The three legs are hand-soldered to a circular disc top — no screws, no visible fixings. The assembled form is then hand-polished to the customer\'s chosen finish: mirror-polished, brushed-satin, or patinated antique. A felt base pad prevents floor scratching.',
      features: [
        'Hand-spun and hand-bent solid brass legs',
        'Hand-soldered assembly — no visible fixings',
        'Three finish options: polished, brushed, antique',
        'Circular solid brass top',
        'Felt base pad for floor protection',
        'Made by master craftsmen in Moradabad',
      ],
      care: 'Polish with a specialist brass cleaner to maintain lustre. Antique finish: wipe with a dry cloth only — do not polish.',
      warranty: '3 years structural',
      rating: 4.9,
      reviewCount: 41,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Arc Brass Side Table in polished brass', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-ST-002',
    slug: 'drum-marble-side-table',
    name: 'Drum Marble Side Table',
    categorySlug: 'living',
    subcategorySlug: 'side-tables',
    brand: 'Modulas Atelier',
    price: 85000,
    compareAtPrice: 100000,
    currency: 'INR',
    material: 'Solid marble drum column with marble top — single stone',
    finishOptions: ['Statuario White', 'Green Onyx', 'Sahara Noir'],
    dimensions: { width: 35, height: 50, depth: 35, unit: 'cm' },
    weightKg: 38,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 10,
    leadTimeDays: 21,
    seoTitle: 'Drum Marble Side Table – Solid Stone | Modulas',
    seoDescription: 'The Drum Marble Side Table is turned from a single block of marble — column and top in one continuous piece. Monolithic, extraordinary, and available in three rare stones.',
    tags: ['side-table', 'marble', 'stone', 'monolithic', 'luxury', 'subcategory:side-tables'],
    description: 'Monolithic beauty — the Drum Marble Side Table is turned from a single block of stone, column and top in one continuous form, available in Statuario White, Green Onyx, or Sahara Noir.',
    metadata: {
      fullDescription: 'There is no frame, no leg, no join — the Drum Marble Side Table is CNC-turned from a single solid block of marble, producing a seamless, monolithic column that terminates in a flat circular top. The turning reveals the stone\'s internal structure in concentric rings along the column face. Three stone options are offered: Statuario White with dramatic grey veining; Green Onyx, translucent when backlit; and Sahara Noir, deep charcoal with golden veining. The base is faced with a circular felt disc that protects flooring.',
      features: [
        'Turned from a single block of stone — no joins',
        'Three rare stone options: Statuario, Green Onyx, Sahara Noir',
        'CNC-turned with hand-polished finish',
        'Circular felt base disc for floor protection',
        'Each piece unique due to natural stone variation',
      ],
      care: 'Wipe with a damp cloth and pH-neutral cleaner. Seal annually. Avoid acidic substances on stone surface.',
      warranty: '5 years structural, lifetime stone guarantee',
      rating: 4.9,
      reviewCount: 19,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Drum Marble Side Table in Statuario White', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-ST-003',
    slug: 'float-acrylic-side-table',
    name: 'Float Acrylic Side Table',
    categorySlug: 'living',
    subcategorySlug: 'side-tables',
    brand: 'Modulas Atelier',
    price: 38000,
    currency: 'INR',
    material: 'Optically clear cast acrylic — single-block construction',
    finishOptions: ['Clear', 'Smoked Amber', 'Rose Blush'],
    dimensions: { width: 38, height: 52, depth: 38, unit: 'cm' },
    weightKg: 6,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 28,
    leadTimeDays: 10,
    seoTitle: 'Float Acrylic Side Table – Transparent | Modulas',
    seoDescription: 'The Float Acrylic Side Table disappears into its surroundings — cast from a single block of optically clear acrylic in a geometric form that seems to levitate.',
    tags: ['side-table', 'acrylic', 'transparent', 'modern', 'minimal', 'subcategory:side-tables'],
    description: 'The Float Acrylic Side Table dissolves into its environment — cast from a single block of optically clear acrylic, it takes up visual space without occupying it.',
    metadata: {
      fullDescription: 'The Float Acrylic Side Table is precision-cast from optical-grade cast acrylic — not extruded, which would show internal stress lines — before being CNC-machined to its final geometric form and hand-polished to eliminate all tool marks. The result is a table with near-invisible presence, reflecting light gently across its softly faceted surfaces. Smoked amber and rose blush variants add a subtle wash of colour while maintaining the translucent quality. An ideal companion for any furniture style, as it neither competes nor clashes.',
      features: [
        'Optical-grade cast acrylic — no internal stress lines',
        'CNC-machined and hand-polished to eliminate tool marks',
        'Three colourways: clear, smoked amber, rose blush',
        'Single-block construction — no joins',
        'Lightweight and easy to reposition',
      ],
      care: 'Wipe with a damp soft cloth. Do not use glass cleaner or alcohol-based products. Minor scratches can be buffed out with plastic polish.',
      warranty: '2 years',
      rating: 4.6,
      reviewCount: 55,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Float Acrylic Side Table in clear', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-ST-004',
    slug: 'porter-oak-side-table',
    name: 'Porter Oak Side Table',
    categorySlug: 'living',
    subcategorySlug: 'side-tables',
    brand: 'Modulas Atelier',
    price: 28000,
    currency: 'INR',
    material: 'Solid oak with lower shelf',
    finishOptions: ['Natural Oak', 'Black Oak', 'Whitened Oak'],
    dimensions: { width: 45, height: 55, depth: 45, unit: 'cm' },
    weightKg: 10,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 40,
    leadTimeDays: 10,
    seoTitle: 'Porter Oak Side Table – Solid Oak with Shelf | Modulas',
    seoDescription: 'The Porter Oak Side Table: a solid oak classic with a lower display shelf. Practical, understated, enduring — and available in three oak finishes.',
    tags: ['side-table', 'oak', 'shelf', 'practical', 'subcategory:side-tables'],
    description: 'A solid oak side table with a generous lower shelf — the Porter is the unpretentious workhorse of the living room, beautiful in its simplicity.',
    metadata: {
      fullDescription: 'The Porter Oak Side Table is designed to be bought, placed, and forgotten about — in the best possible sense. Four solid oak legs, a solid oak top, and a solid oak lower shelf, joined with traditional dowel-and-glue construction, finished in one of three oil colourways. Everything is solid timber; nothing is veneered. At 45 cm square, it sits comfortably beside any sofa or armchair. The lower shelf holds books, remotes, or a plant with no fuss.',
      features: [
        'Solid oak throughout — top, legs, and lower shelf',
        'Traditional dowel-and-glue construction',
        'Three oil finish colourways',
        'Square 45 × 45 cm footprint',
      ],
      care: 'Wipe with a damp cloth. Re-oil with natural oak oil every 12–18 months.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 134,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Porter Oak Side Table in natural oak', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-ST-005',
    slug: 'pedestal-terrazzo-side-table',
    name: 'Pedestal Terrazzo Side Table',
    categorySlug: 'living',
    subcategorySlug: 'side-tables',
    brand: 'Modulas Atelier',
    price: 55000,
    compareAtPrice: 68000,
    currency: 'INR',
    material: 'Terrazzo composite top with powder-coated steel pedestal',
    finishOptions: ['Blush Terrazzo / Gold Steel', 'Charcoal Terrazzo / Black Steel'],
    dimensions: { width: 42, height: 58, depth: 42, unit: 'cm' },
    weightKg: 20,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 15,
    leadTimeDays: 14,
    seoTitle: 'Pedestal Terrazzo Side Table – Terrazzo & Steel | Modulas',
    seoDescription: 'The Pedestal Terrazzo Side Table pairs a hand-cast terrazzo composite top with a slender powder-coated steel pedestal — colour, texture, and structure in one elegant form.',
    tags: ['side-table', 'terrazzo', 'steel', 'colourful', 'pedestal', 'subcategory:side-tables'],
    description: 'The Pedestal Terrazzo Side Table brings colour, texture, and material character to the living room in one compact form — hand-cast terrazzo top on a slender steel pedestal.',
    metadata: {
      fullDescription: 'Terrazzo — the ancient Italian technique of embedding stone, glass, and marble chips in a cement binder — is here reinterpreted in a vibrant, contemporary palette. The circular top is hand-cast in a custom mould and hand-ground to a polished finish that reveals the full depth of its chip composition. The blush variant uses rose quartz and white marble chips in a pink cement matrix; the charcoal uses black granite and smoked glass chips in a dark cement ground. The pedestal is a single length of 50 mm steel tube, laser-cut at the base into four radiating feet and powder-coated to complement the terrazzo.',
      features: [
        'Hand-cast terrazzo composite top — hand-ground and polished',
        'Two colourways with contrasting chip compositions',
        'Laser-cut 50 mm steel tube pedestal with radiating feet',
        'Powder-coated steel in complementary finish to terrazzo',
        'Circular 42 cm diameter top',
      ],
      care: 'Wipe terrazzo with a damp cloth. Seal annually with a penetrating stone sealer. Wipe steel with a dry cloth.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 38,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Pedestal Terrazzo Side Table in blush and gold', isPrimary: true },
    ],
  },

  // ── Console Tables (4) ───────────────────────────────────────────────────
  {
    sku: 'LIV-CO-001',
    slug: 'axis-console-table',
    name: 'Axis Console Table',
    categorySlug: 'living',
    subcategorySlug: 'console-tables',
    brand: 'Modulas Atelier',
    price: 95000,
    compareAtPrice: 115000,
    currency: 'INR',
    material: 'Solid walnut top with hand-welded steel X-frame',
    finishOptions: ['Walnut / Matte Black Steel', 'Walnut / Polished Brass Steel'],
    dimensions: { width: 140, height: 80, depth: 40, unit: 'cm' },
    weightKg: 36,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 12,
    leadTimeDays: 21,
    seoTitle: 'Axis Console Table – Walnut & Steel X-Frame | Modulas',
    seoDescription: 'The Axis Console Table pairs a solid walnut top with a dramatic hand-welded steel X-frame — a striking entryway or living room console with real material presence.',
    tags: ['console-table', 'walnut', 'steel', 'x-frame', 'entryway', 'subcategory:console-tables'],
    description: 'The Axis Console Table makes a confident entry statement — a solid walnut top on a dramatic hand-welded steel X-frame that projects strength and precision in equal measure.',
    metadata: {
      fullDescription: 'The Axis Console Table is conceived as a visual anchor for an entryway, hallway, or living room wall. A solid walnut plank top — 35 mm thick and edge-profiled with a slim chamfer — rests on a structural X-frame fabricated from 25 × 25 mm square steel section. The cross-brace geometry distributes load evenly and provides an element of dynamic tension to the overall form. Two finish combinations are offered: the understated walnut with matte black steel, and the warmer walnut with antique brass-dipped steel. A lower stretcher between the X-frames provides rigidity and a surface for shoes or a plant.',
      features: [
        'Solid walnut plank top, 35 mm with chamfered edge',
        'Hand-welded 25 × 25 mm square steel X-frame',
        'Two finish options: matte black or brass steel',
        'Lower stretcher provides rigidity and storage surface',
        'Powder-coated or plated steel frame options',
      ],
      care: 'Wipe walnut top with a damp cloth. Re-oil annually. Wipe steel frame with a dry cloth; use mild cleaner for marks.',
      warranty: '5 years structural',
      rating: 4.8,
      reviewCount: 43,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Axis Console Table in walnut and matte black', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CO-002',
    slug: 'gallery-marble-console',
    name: 'Gallery Marble Console',
    categorySlug: 'living',
    subcategorySlug: 'console-tables',
    brand: 'Modulas Atelier',
    price: 195000,
    compareAtPrice: 230000,
    currency: 'INR',
    material: 'Bianco Carrara marble top with solid brass tapered legs',
    finishOptions: ['Bianco Carrara / Polished Brass', 'Statuario / Brushed Gold'],
    dimensions: { width: 160, height: 82, depth: 40, unit: 'cm' },
    weightKg: 85,
    isConfigurable: false,
    isFeatured: true,
    stockQty: 5,
    leadTimeDays: 35,
    seoTitle: 'Gallery Marble Console – Carrara & Brass | Modulas',
    seoDescription: 'The Gallery Marble Console pairs a honed Bianco Carrara marble top with four hand-turned polished brass tapered legs — a statement living room or hallway piece of extraordinary refinement.',
    tags: ['console-table', 'marble', 'brass', 'carrara', 'luxury', 'subcategory:console-tables'],
    description: 'A piece of gallery-worthy refinement — the Gallery Marble Console pairs a honed Bianco Carrara slab with four hand-turned polished brass legs that taper elegantly to their feet.',
    metadata: {
      fullDescription: 'Bianco Carrara marble — the stone of Michelangelo\'s David and the Pantheon — is here worked into a honed console top: its cool white ground and soft grey veining are rendered in matte rather than polished finish, emphasising the depth of the stone\'s natural texture. The four legs are individually hand-turned from solid brass rod on a traditional lathe, tapered from 35 mm at the apron to 15 mm at the floor, and polished to a warm mirror finish. A solid brass apron rail connects the four legs and transfers the considerable weight of the stone evenly. Adjustable brass floor levellers are recessed into the base of each leg.',
      features: [
        'Honed Bianco Carrara marble top — matte finish',
        'Four hand-turned solid brass tapered legs',
        'Solid brass apron rail — structural and aesthetic',
        'Adjustable recessed brass floor levellers',
        'Statuario / Brushed Gold variant available',
        'Each stone slab unique due to natural variation',
      ],
      care: 'Wipe marble with a damp cloth and pH-neutral cleaner. Seal annually. Polish brass with specialist brass cleaner; antique variants: dry cloth only.',
      warranty: '5 years structural, lifetime stone guarantee',
      rating: 5.0,
      reviewCount: 16,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Gallery Marble Console in Carrara and brass', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CO-003',
    slug: 'slim-oak-console-table',
    name: 'Slim Oak Console Table',
    categorySlug: 'living',
    subcategorySlug: 'console-tables',
    brand: 'Modulas Atelier',
    price: 58000,
    currency: 'INR',
    material: 'Solid oak with three drawers and open lower shelf',
    finishOptions: ['Natural Oak', 'Smoked Oak'],
    dimensions: { width: 130, height: 78, depth: 35, unit: 'cm' },
    weightKg: 32,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 18,
    leadTimeDays: 14,
    seoTitle: 'Slim Oak Console Table with Drawers | Modulas',
    seoDescription: 'A slim-profile solid oak console table with three drawers and an open lower shelf — practical, beautiful, and a natural fit for hallways or behind a sofa.',
    tags: ['console-table', 'oak', 'drawers', 'storage', 'hallway', 'subcategory:console-tables'],
    description: 'The Slim Oak Console Table is a master of proportions — a 35 cm depth makes it suitable for any hallway or behind-sofa position, while three drawers and a lower shelf keep life organised.',
    metadata: {
      fullDescription: 'At 35 cm deep, the Slim Oak Console Table fits where full-depth furniture cannot. Three solid oak drawers — each with a flush, handle-free push-to-open mechanism — run the full width of the table, providing excellent storage for keys, post, and everyday items. A solid oak lower shelf sits 20 cm from the floor, providing display space or basket storage. All construction is solid oak; the drawer boxes are through-dovetailed at the corners. Available in natural and smoked oak oil finishes.',
      features: [
        'Solid oak throughout — top, frame, shelves, and drawers',
        'Three push-to-open flush-front drawers',
        'Through-dovetailed drawer box construction',
        'Open lower shelf — 20 cm from floor',
        '35 cm depth — fits behind sofas and in hallways',
      ],
      care: 'Wipe with a damp cloth. Re-oil annually to maintain richness of colour.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 61,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Slim Oak Console Table in natural oak', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-CO-004',
    slug: 'crescent-console-table',
    name: 'Crescent Console Table',
    categorySlug: 'living',
    subcategorySlug: 'console-tables',
    brand: 'Modulas Atelier',
    price: 118000,
    compareAtPrice: 140000,
    currency: 'INR',
    material: 'Curved solid ash front with smoked glass shelf and brass legs',
    finishOptions: ['Natural Ash / Brass', 'Black Ash / Matte Black'],
    dimensions: { width: 150, height: 80, depth: 42, unit: 'cm' },
    weightKg: 44,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 7,
    leadTimeDays: 21,
    seoTitle: 'Crescent Console Table – Curved Ash & Brass | Modulas',
    seoDescription: 'The Crescent Console Table features a steam-bent curved ash front panel, smoked glass lower shelf, and hand-turned brass legs — a sculptural console of singular character.',
    tags: ['console-table', 'ash', 'curved', 'brass', 'glass', 'subcategory:console-tables'],
    description: 'The Crescent Console Table stands apart through its steam-bent curved ash front panel — a technically demanding process that produces a gentle convex curve across the full 150 cm width.',
    metadata: {
      fullDescription: 'Steam-bending is one of furniture-making\'s most demanding techniques: the ash timber is soaked, then heated in a steam box until pliable enough to be formed over a curved mould and clamped until cool and set. The result — a seamless, grain-continuous curved front panel — is impossible to achieve by any other means without joints or veneers. The lower shelf is 6 mm smoked glass resting on solid brass supports. Four hand-turned solid brass legs, tapered and polished, complete the composition. A console of singular sculptural character.',
      features: [
        'Steam-bent curved solid ash front panel — grain-continuous',
        '6 mm smoked glass lower shelf',
        'Four hand-turned solid brass tapered legs',
        'Solid brass shelf support brackets',
        'Technically demanding single-piece bent construction',
      ],
      care: 'Wipe ash panel with a damp cloth; re-oil every 12 months. Clean glass with streak-free cleaner. Polish brass quarterly.',
      warranty: '5 years structural',
      rating: 4.9,
      reviewCount: 21,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Crescent Console Table in natural ash and brass', isPrimary: true },
    ],
  },

  // ── TV Units (5) ─────────────────────────────────────────────────────────
  {
    sku: 'LIV-TV-001',
    slug: 'horizon-walnut-tv-unit',
    name: 'Horizon Walnut TV Unit',
    categorySlug: 'living',
    subcategorySlug: 'tv-units',
    brand: 'Modulas Atelier',
    price: 145000,
    compareAtPrice: 170000,
    currency: 'INR',
    material: 'Solid walnut with cane door panels and black metal legs',
    finishOptions: ['Natural Walnut / Natural Cane', 'Smoked Walnut / Bleached Cane'],
    dimensions: { width: 200, height: 55, depth: 45, unit: 'cm' },
    weightKg: 72,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 8,
    leadTimeDays: 28,
    seoTitle: 'Horizon Walnut TV Unit – Solid Walnut & Cane | Modulas',
    seoDescription: 'The Horizon Walnut TV Unit: 200 cm of solid walnut with hand-woven cane door panels and hairpin steel legs. A considered media unit for the luxury living room.',
    tags: ['tv-unit', 'walnut', 'cane', 'media-console', 'living-room', 'subcategory:tv-units'],
    description: 'The Horizon Walnut TV Unit brings warmth, texture, and the craft of hand-woven cane to the centrepiece wall of any living room — solid walnut over hairpin steel legs at 200 cm wide.',
    metadata: {
      fullDescription: 'At 200 cm, the Horizon Walnut TV Unit commands wall presence without visual heaviness. The low-profile silhouette — 55 cm height — maintains a natural sightline to screens of up to 75 inches. Two cane-fronted cabinets frame a central open bay that provides 150 cm of open shelf space for AV equipment. The cane panels are hand-woven in a tight hexagonal pattern by artisans in Kerala, using natural rattan strand that allows air circulation around electronics. All structure is solid walnut; internal cable management includes a dedicated HDMI and power grommet port at the rear.',
      features: [
        '200 cm wide solid walnut low-profile unit',
        'Hand-woven hexagonal cane door panels',
        'Central open bay for AV equipment — 150 cm wide',
        'Dedicated rear cable management grommet ports',
        'Six solid walnut hairpin legs with levelling pads',
        'Supports screens up to 75 inches at natural sightline height',
      ],
      care: 'Dust cane panels with a soft brush. Wipe walnut with a damp cloth; re-oil annually. Keep electronics ventilated through cane panels.',
      warranty: '5 years structural',
      rating: 4.9,
      reviewCount: 47,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Horizon Walnut TV Unit — full width view', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-TV-002',
    slug: 'float-wall-tv-unit',
    name: 'Float Wall TV Unit',
    categorySlug: 'living',
    subcategorySlug: 'tv-units',
    brand: 'Modulas Atelier',
    price: 98000,
    compareAtPrice: 118000,
    currency: 'INR',
    material: 'Oak veneer floating wall unit — full modular system',
    finishOptions: ['Natural Oak', 'White Oak', 'Charcoal'],
    dimensions: { width: 240, height: 45, depth: 35, unit: 'cm' },
    weightKg: 54,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 10,
    leadTimeDays: 21,
    seoTitle: 'Float Wall TV Unit – Wall-Mounted Floating | Modulas',
    seoDescription: 'The Float Wall TV Unit mounts to the wall at a chosen height, creating a clean floating aesthetic. Oak veneer, fully modular, with hidden cable management behind a removable back panel.',
    tags: ['tv-unit', 'floating', 'wall-mounted', 'oak', 'modular', 'subcategory:tv-units'],
    description: 'The Float Wall TV Unit mounts flush to the wall, creating the illusion of furniture that hovers — a clean, architecturally resolved media solution in oak veneer.',
    metadata: {
      fullDescription: 'The Float Wall TV Unit is designed to disappear into the architecture of the room while organising everything beneath your screen. Mounting at a customer-specified height, the unit presents a perfectly flat, frameless face — two closed cabinets with push-to-open doors flank a central open bay. A removable rear panel gives full access to cable management; HDMI and power grommets are pre-routed to a hidden management channel along the unit base. Available in 240, 180, and 120 cm widths to suit different wall configurations.',
      features: [
        'Wall-mounted floating design at customer-specified height',
        'Two push-to-open closed cabinets and central open bay',
        'Removable rear panel for cable management access',
        'Pre-routed HDMI and power grommet ports',
        'Available in 120, 180, and 240 cm widths',
        'Oak veneer over solid-core panel',
      ],
      care: 'Wipe veneer surfaces with a damp cloth. Avoid prolonged direct sunlight. Ensure adequate wall fixings per installation guide.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 59,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Float Wall TV Unit in natural oak', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-TV-003',
    slug: 'sideboard-tv-unit',
    name: 'Sideboard TV Unit',
    categorySlug: 'living',
    subcategorySlug: 'tv-units',
    brand: 'Modulas Atelier',
    price: 125000,
    currency: 'INR',
    material: 'Solid ash with sliding door panels and solid brass handles',
    finishOptions: ['Natural Ash', 'Black Ash'],
    dimensions: { width: 180, height: 60, depth: 45, unit: 'cm' },
    weightKg: 65,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 9,
    leadTimeDays: 21,
    seoTitle: 'Sideboard TV Unit – Solid Ash & Brass | Modulas',
    seoDescription: 'The Sideboard TV Unit doubles as a sideboard and media console — solid ash with sliding door panels, solid brass handles, and generous internal shelving.',
    tags: ['tv-unit', 'sideboard', 'ash', 'brass', 'sliding-doors', 'subcategory:tv-units'],
    description: 'A media console and sideboard in one — the Sideboard TV Unit in solid ash with sliding panels and solid brass bar handles serves dual duty without aesthetic compromise.',
    metadata: {
      fullDescription: 'The Sideboard TV Unit resolves the common living room dilemma of needing both a media console and a sideboard in the same space. At 180 × 60 cm, it provides a generous top surface for display while its interior — accessed through two sliding solid ash panels with solid brass bar handles — contains three adjustable shelves and a dedicated cable grommet port. The sliding door mechanism runs on a concealed recessed track and glides on precision-machined rollers without lifting or binding. The unit stands on four solid brass cone feet.',
      features: [
        'Solid ash construction throughout',
        'Two sliding solid ash panels with solid brass bar handles',
        'Concealed recessed sliding track mechanism',
        'Three adjustable internal shelves',
        'Integrated cable grommet port',
        'Four solid brass cone feet',
      ],
      care: 'Wipe ash surfaces with a damp cloth; re-oil annually. Lubricate sliding track with a dry silicone spray every 12 months.',
      warranty: '5 years structural',
      rating: 4.8,
      reviewCount: 33,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Sideboard TV Unit in natural ash', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-TV-004',
    slug: 'low-teak-media-unit',
    name: 'Low Teak Media Unit',
    categorySlug: 'living',
    subcategorySlug: 'tv-units',
    brand: 'Modulas Atelier',
    price: 175000,
    compareAtPrice: 210000,
    currency: 'INR',
    material: 'Reclaimed teak with woven leather drawer pulls',
    finishOptions: ['Reclaimed Natural Teak', 'Reclaimed Ebonised Teak'],
    dimensions: { width: 220, height: 50, depth: 48, unit: 'cm' },
    weightKg: 98,
    isConfigurable: false,
    isFeatured: true,
    stockQty: 4,
    leadTimeDays: 35,
    seoTitle: 'Low Teak Media Unit – Reclaimed Teak | Modulas',
    seoDescription: 'The Low Teak Media Unit is built from reclaimed teak salvaged from century-old structures — a 220 cm wide media console with depth of grain and character no new timber can match.',
    tags: ['tv-unit', 'reclaimed-teak', 'sustainable', 'media-unit', 'luxury', 'subcategory:tv-units'],
    description: 'The Low Teak Media Unit is built from reclaimed teak salvaged from century-old structures in Rajasthan — its grain and character are the irreplaceable product of a hundred years of life.',
    metadata: {
      fullDescription: 'Reclaimed teak is among the world\'s most characterful furniture timbers — decades of exposure to humidity, heat, and use produce a depth of grain, natural oil, and silver-grey surface patina that cannot be replicated in new timber. The Low Teak Media Unit repurposes structural beams from demolished havelis (traditional merchant mansions) in Rajasthan, cutting them into planks and joining them with new mortise-and-tenon joinery. Four cabinet doors are fitted with woven buffalo leather pull-loops hand-sewn by artisans in Jodhpur. The unit stands directly on the floor on a continuous reclaimed teak plinth base.',
      features: [
        'Built from certified reclaimed teak — century-old structural timber',
        'Mortise-and-tenon joinery throughout',
        'Four cabinet doors with hand-woven buffalo leather pulls',
        'Continuous reclaimed teak plinth base',
        'Internal cable management provision',
        'Each unit unique due to natural character of reclaimed timber',
      ],
      care: 'Apply teak oil annually to maintain moisture balance. Reclaimed teak will continue to silver gracefully — this is natural and desirable. Condition leather pulls every 6 months.',
      warranty: '10 years structural',
      rating: 4.9,
      reviewCount: 22,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Low Teak Media Unit — reclaimed teak with leather pulls', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-TV-005',
    slug: 'arc-media-console',
    name: 'Arc Media Console',
    categorySlug: 'living',
    subcategorySlug: 'tv-units',
    brand: 'Modulas Atelier',
    price: 78000,
    currency: 'INR',
    material: 'MDF with lacquer finish and arched door cutouts',
    finishOptions: ['Ivory White', 'Sage Green', 'Terracotta'],
    dimensions: { width: 160, height: 55, depth: 42, unit: 'cm' },
    weightKg: 44,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 16,
    leadTimeDays: 14,
    seoTitle: 'Arc Media Console – Arched Door Design | Modulas',
    seoDescription: 'The Arc Media Console brings architectural arched doors to the living room — available in ivory, sage, or terracotta lacquer for a colourful, considered media storage statement.',
    tags: ['tv-unit', 'arched-doors', 'lacquer', 'colourful', 'contemporary', 'subcategory:tv-units'],
    description: 'The Arc Media Console introduces the architectural arch to the living room — arched door cutouts in three cheerful lacquer colourways, bringing personality to the media wall.',
    metadata: {
      fullDescription: 'The arch has become one of the defining architectural motifs of contemporary interior design — and the Arc Media Console brings it to the living room in three considered colourways. Four arched doors — each CNC-routed with a perfect semicircular top — open on concealed hinges to reveal two internal shelves per cabinet compartment. The doors are solid-core MDF, painted in four coats of water-based lacquer and sanded between coats to achieve a smooth, semi-matte finish. Integrated arched cutout handles eliminate the need for external hardware.',
      features: [
        'Four arched-top doors with integrated cutout handles',
        'CNC-routed arches with hand-painted lacquer finish',
        'Four coats water-based lacquer, sanded between coats',
        'Concealed hinges — doors open flat',
        'Two internal shelves per cabinet compartment',
        'Three lacquer colourways available',
      ],
      care: 'Wipe with a damp soft cloth. Do not use abrasive cleaners on lacquered surface.',
      warranty: '3 years structural',
      rating: 4.6,
      reviewCount: 88,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Arc Media Console in ivory white', isPrimary: true },
    ],
  },

  // ── Display Shelving (4) ─────────────────────────────────────────────────
  {
    sku: 'LIV-DS-001',
    slug: 'gallery-wall-shelves',
    name: 'Gallery Wall Shelves',
    categorySlug: 'living',
    subcategorySlug: 'display-shelving',
    brand: 'Modulas Atelier',
    price: 45000,
    currency: 'INR',
    material: 'Set of 3 solid walnut floating shelves with hidden fixings',
    finishOptions: ['Natural Walnut', 'Smoked Walnut'],
    dimensions: { width: 80, height: 5, depth: 22, unit: 'cm' },
    weightKg: 6,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 30,
    leadTimeDays: 10,
    seoTitle: 'Gallery Wall Shelves – 3-Piece Solid Walnut | Modulas',
    seoDescription: 'Three solid walnut floating shelves with completely hidden fixings — wall-mount at any configuration for a clean, gallery-worthy display of books, art, and objects.',
    tags: ['display-shelving', 'floating-shelves', 'walnut', 'wall-mounted', 'subcategory:display-shelving'],
    description: 'Three solid walnut floating shelves with perfectly hidden fixings — the Gallery Wall Shelves transform any wall into a curated display surface.',
    metadata: {
      fullDescription: 'The Gallery Wall Shelves use a concealed keyhole bracket system: the steel brackets are fixed to the wall first, then the solid walnut shelf casings slide over them for a completely hardware-free face. The result is a shelf that appears to grow from the wall. Each of the three shelves in the set is 80 cm wide and 22 cm deep — wide enough to display art books horizontally or frame a plant. All three can be arranged in any configuration: staggered, aligned, or cascading. Wall fixing kit and template included.',
      features: [
        'Set of 3 — 80 cm solid walnut floating shelves',
        'Concealed keyhole bracket system — no visible hardware',
        'Shelf slides over pre-fixed wall bracket',
        '22 cm depth suitable for books, art, plants',
        'Arrange in any wall configuration',
        'Wall fixing kit and positioning template included',
      ],
      care: 'Wipe with a damp cloth. Re-oil annually with natural oil to maintain walnut warmth.',
      warranty: '3 years structural',
      rating: 4.8,
      reviewCount: 92,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Gallery Wall Shelves in natural walnut', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-DS-002',
    slug: 'curio-display-cabinet',
    name: 'Curio Display Cabinet',
    categorySlug: 'living',
    subcategorySlug: 'display-shelving',
    brand: 'Modulas Atelier',
    price: 145000,
    compareAtPrice: 168000,
    currency: 'INR',
    material: 'Solid oak frame with clear glass panels and integrated LED lighting',
    finishOptions: ['Natural Oak', 'Black Oak'],
    dimensions: { width: 80, height: 180, depth: 38, unit: 'cm' },
    weightKg: 55,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 6,
    leadTimeDays: 28,
    seoTitle: 'Curio Display Cabinet – Solid Oak with LED Lighting | Modulas',
    seoDescription: 'The Curio Display Cabinet in solid oak frames five glass-fronted shelves with integrated warm LED lighting — the ideal home for a curated collection of art objects or ceramics.',
    tags: ['display-shelving', 'cabinet', 'glass', 'oak', 'led-lighting', 'subcategory:display-shelving'],
    description: 'The Curio Display Cabinet turns a collection into an exhibition — five glass-fronted shelves in a solid oak frame, illuminated by integrated warm LED strip lighting at each shelf level.',
    metadata: {
      fullDescription: 'The Curio Display Cabinet is designed for those who collect with intention and want to display accordingly. Five adjustable glass shelves sit within a solid oak frame with glass side and door panels that allow the interior to be seen from multiple angles. Integrated 3000K LED strips at each shelf level illuminate objects from below, creating a gallery effect without shadow. A two-way hinge door on the right opens to full 180°, allowing easy access without moving the cabinet. All glass panels are 5 mm tempered.',
      features: [
        'Solid oak frame with 5 mm tempered glass panels on three sides and door',
        'Five adjustable glass shelves',
        'Integrated 3000K LED strips at each shelf level',
        'Touch-dimmer control on apron',
        'Full 180° door opening',
        'Available with mirror back panel option',
      ],
      care: 'Wipe glass panels with a streak-free glass cleaner. Dust solid oak frame with a dry cloth. LED strips rated 50,000 hours.',
      warranty: '5 years structural, 2 years electronics',
      rating: 4.9,
      reviewCount: 28,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Curio Display Cabinet in natural oak with LED lighting', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-DS-003',
    slug: 'ladder-display-shelf',
    name: 'Ladder Display Shelf',
    categorySlug: 'living',
    subcategorySlug: 'display-shelving',
    brand: 'Modulas Atelier',
    price: 48000,
    compareAtPrice: 58000,
    currency: 'INR',
    material: 'Solid ash ladder frame with five graduated shelves',
    finishOptions: ['Natural Ash', 'Black Ash', 'White Ash'],
    dimensions: { width: 60, height: 185, depth: 38, unit: 'cm' },
    weightKg: 22,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 24,
    leadTimeDays: 10,
    seoTitle: 'Ladder Display Shelf – Solid Ash | Modulas',
    seoDescription: 'The Ladder Display Shelf in solid ash presents five graduated shelves in a leaning ladder format — a versatile, space-efficient display solution for any living room corner.',
    tags: ['display-shelving', 'ladder-shelf', 'ash', 'leaning', 'subcategory:display-shelving'],
    description: 'The Ladder Display Shelf leans against the wall with quiet confidence — five graduated solid ash shelves in a tapering ladder frame that turns any corner into a display moment.',
    metadata: {
      fullDescription: 'The Ladder Display Shelf is a study in graduated proportion: the five solid ash shelves step progressively narrower from the 60 cm base shelf to the 40 cm top shelf, mirroring the natural taper of the ladder frame. The lean angle is precisely calibrated to allow the shelf to stand stably without wall fixing while keeping the shelves close to level. A discreet wall hook at the top of each upright provides optional wall security. All joinery is mortise-and-tenon with wedged through-tenons visible on the outer faces of the uprights.',
      features: [
        'Five graduated solid ash shelves (60 cm to 40 cm)',
        'Precisely calibrated lean angle for self-standing stability',
        'Optional wall hook fixings at top of uprights',
        'Mortise-and-tenon joinery with visible wedged through-tenons',
        'Three finish options: natural, black, white ash',
      ],
      care: 'Wipe with a damp cloth. Re-oil annually to maintain finish. Avoid placing excessively heavy items on upper shelves.',
      warranty: '3 years structural',
      rating: 4.6,
      reviewCount: 103,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Ladder Display Shelf in natural ash', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-DS-004',
    slug: 'arc-niche-shelf-set',
    name: 'Arc Niche Shelf Set',
    categorySlug: 'living',
    subcategorySlug: 'display-shelving',
    brand: 'Modulas Atelier',
    price: 62000,
    currency: 'INR',
    material: 'Set of 2 arched solid oak niche shelves with hidden wall plate',
    finishOptions: ['Natural Oak', 'Dusty White', 'Sage Green'],
    dimensions: { width: 55, height: 70, depth: 18, unit: 'cm' },
    weightKg: 14,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 18,
    leadTimeDays: 14,
    seoTitle: 'Arc Niche Shelf Set – Arched Solid Oak Display Niches | Modulas',
    seoDescription: 'A pair of arched niche shelves in solid oak — wall-mounted with a hidden back plate, creating the appearance of architectural niches without the construction work.',
    tags: ['display-shelving', 'arched', 'niche', 'oak', 'wall-mounted', 'subcategory:display-shelving'],
    description: 'The Arc Niche Shelf Set pairs two arched solid oak wall-mounted niches — create the effect of architectural alcoves anywhere on a wall, without structural work.',
    metadata: {
      fullDescription: 'The Arc Niche Shelf Set simulates the architectural luxury of built-in alcove niches using surface-mounted solid oak boxes with arched top profiles. Each box is constructed from 20 mm solid oak panels, CNC-routed with a perfect semicircular top, then lacquered in the customer\'s chosen colour. The interior base functions as a display shelf; the interior walls are painted in a complementary warm white as standard. A single concealed steel back plate fixes to the wall and accepts the niche box via hidden keyhole slots. Sold as a pair.',
      features: [
        'Set of two solid oak arched niche boxes',
        'CNC-routed semicircular arch top profile',
        'Concealed steel back plate — hidden keyhole mounting',
        'Interior base as display shelf',
        'Interior walls in complementary warm white',
        'Three exterior colourways available',
      ],
      care: 'Wipe lacquered exterior with a damp microfibre cloth. Do not use abrasive cleaners. Dust interior with a soft dry cloth.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 56,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Arc Niche Shelf Set in natural oak', isPrimary: true },
    ],
  },

  // ── Floor Lamps (2) ──────────────────────────────────────────────────────
  {
    sku: 'LIV-FL-001',
    slug: 'arc-brass-floor-lamp',
    name: 'Arc Brass Floor Lamp',
    categorySlug: 'living',
    subcategorySlug: 'floor-lamps',
    brand: 'Modulas Atelier',
    price: 85000,
    compareAtPrice: 100000,
    currency: 'INR',
    material: 'Hand-spun solid brass arc with natural linen shade',
    finishOptions: ['Polished Brass / Ivory Linen', 'Antique Brass / Ivory Linen', 'Matte Black / White Linen'],
    dimensions: { width: 50, height: 185, depth: 150, unit: 'cm' },
    weightKg: 14,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 12,
    leadTimeDays: 21,
    seoTitle: 'Arc Brass Floor Lamp – Solid Brass with Linen Shade | Modulas',
    seoDescription: 'The Arc Brass Floor Lamp extends 150 cm over a seating area, casting warm diffused light through a natural linen shade — the quintessential luxury living room lamp.',
    tags: ['floor-lamp', 'brass', 'arc-lamp', 'linen-shade', 'lighting', 'subcategory:floor-lamps'],
    description: 'The Arc Brass Floor Lamp is the quintessential living room lighting statement — a hand-spun solid brass arm arcing 150 cm over a seating area, terminating in a natural linen drum shade.',
    metadata: {
      fullDescription: 'The Arc Brass Floor Lamp draws from the mid-century tradition of the arc lamp — a design archetype that positions the light source directly above a seating area without requiring a ceiling fitting. The arm is hand-spun from solid brass tube in one continuous curve, extending 150 cm from upright base to shade centre. The base is a weighted solid marble slab — 5 kg of Bianco Carrara — that provides ballast without the need for additional counterweights. The natural linen drum shade (45 cm diameter) diffuses a warm, ambient 3000K glow. A marble-effect touch dimmer is integrated into the upright.',
      features: [
        'Hand-spun solid brass arm — single continuous curve',
        '150 cm horizontal arc extending over seating area',
        'Weighted Bianco Carrara marble base — 5 kg',
        'Natural linen drum shade — 45 cm diameter',
        'Integrated touch dimmer on upright',
        'E27 bulb socket — compatible with smart bulbs',
        'Cable concealed within brass arm',
      ],
      care: 'Polish brass with a specialist brass cleaner. Shake linen shade gently to remove dust. Wipe marble base with a damp cloth.',
      warranty: '3 years structural, 1 year electronics',
      rating: 4.9,
      reviewCount: 67,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900', alt: 'Arc Brass Floor Lamp in polished brass', isPrimary: true },
    ],
  },
  {
    sku: 'LIV-FL-002',
    slug: 'tripod-teak-floor-lamp',
    name: 'Tripod Teak Floor Lamp',
    categorySlug: 'living',
    subcategorySlug: 'floor-lamps',
    brand: 'Modulas Atelier',
    price: 62000,
    currency: 'INR',
    material: 'Solid teak tripod legs with woven rattan shade',
    finishOptions: ['Natural Teak / Natural Rattan', 'Ebonised Teak / Bleached Rattan'],
    dimensions: { width: 55, height: 165, depth: 55, unit: 'cm' },
    weightKg: 10,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 18,
    leadTimeDays: 14,
    seoTitle: 'Tripod Teak Floor Lamp – Teak & Rattan Shade | Modulas',
    seoDescription: 'The Tripod Teak Floor Lamp stands on three solid teak legs beneath a hand-woven rattan shade — warm, natural, and designed to bring organic texture to any living room.',
    tags: ['floor-lamp', 'teak', 'rattan', 'tripod', 'natural', 'lighting', 'subcategory:floor-lamps'],
    description: 'Three solid teak legs, hand-joined at a brass collar, support a hand-woven rattan globe shade — the Tripod Teak Floor Lamp brings natural warmth and organic texture to the living room.',
    metadata: {
      fullDescription: 'The Tripod Teak Floor Lamp celebrates natural materials in their most direct application. Three solid teak legs — each hand-tapered and finished with natural teak oil — converge at a hand-machined solid brass collar from which the lamp body rises. The globe shade is hand-woven from split rattan strand by artisans in Cirebon, Indonesia, in a classic open weave that casts a dappled pattern of light across the ceiling and walls. An E27 bulb socket accepts any standard fitting; a fabric-covered cable runs to a floor switch.',
      features: [
        'Three solid teak tripod legs, hand-tapered and oiled',
        'Hand-machined solid brass leg collar',
        'Hand-woven open-weave rattan globe shade — Cirebon, Indonesia',
        'Dappled light pattern through woven rattan',
        'E27 bulb socket — compatible with any standard or smart bulb',
        'Fabric-covered cable with floor switch',
      ],
      care: 'Dust rattan shade with a soft brush. Apply teak oil to legs annually. Do not use high-wattage bulbs (max 40W incandescent equivalent).',
      warranty: '3 years structural, 1 year electronics',
      rating: 4.7,
      reviewCount: 44,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900', alt: 'Tripod Teak Floor Lamp in natural teak and rattan', isPrimary: true },
    ],
  },
];
