/**
 * Modulas Luxury Furniture — Master Product Seed
 * Run via: ts-node -r tsconfig-paths/register src/seed/run-seed.ts
 */

export interface SeedImage {
  url: string;
  /** Preferred alias used in newer seed files */
  alt?: string;
  /** Legacy alias used in original seed files */
  altText?: string;
  isPrimary?: boolean;
  sortOrder?: number;
}

export interface SeedProduct {
  sku: string;
  slug: string;
  name: string;
  categorySlug: string;
  subcategorySlug: string;
  brand: string;
  price: number;
  compareAtPrice?: number;
  currency: string;
  material: string;
  finishOptions: string[];
  dimensions: { width: number; height: number; depth: number; unit: string };
  weightKg: number;
  isConfigurable: boolean;
  isFeatured: boolean;
  stockQty: number;
  leadTimeDays: number;
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  description: string;
  metadata: {
    fullDescription: string;
    features: string[];
    care: string;
    warranty: string;
    rating: number;
    reviewCount: number;
  };
  images: SeedImage[];
}

// ─────────────────────────────────────────────────────────────
// CATEGORY 1 — SEATING & SOFAS  (28 products)
// ─────────────────────────────────────────────────────────────
export const SEATING_SOFAS: SeedProduct[] = [
  // ── 3-Seater Sofas (8) ──────────────────────────────────────
  {
    sku: "MOD-SOF-001", slug: "luxe-verona-3-seater-sofa",
    name: "Luxe Verona 3-Seater Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Modulas Originals", price: 385000, compareAtPrice: 455000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Oatmeal", "Slate Grey", "Warm Sand", "Ivory"],
    dimensions: { width: 230, height: 83, depth: 98, unit: "cm" }, weightKg: 78,
    isConfigurable: true, isFeatured: true, stockQty: 8, leadTimeDays: 28,
    seoTitle: "Luxe Verona 3-Seater Boucle Sofa — Modulas Luxury Furniture India",
    seoDescription: "The Verona 3-seater sofa in premium boucle fabric. Kiln-dried hardwood frame, hand-tied springs, and feather-down cushions. Fully customisable. Ships across India.",
    tags: ["bestseller", "subcategory:3-seater-sofas"],
    description: "Cloud-soft boucle over a kiln-dried hardwood frame with hand-tied eight-way springs. The Verona defines the art of effortless luxury seating.",
    metadata: {
      fullDescription: "The Luxe Verona is our most celebrated 3-seater — a sofa that rewards slow afternoons and long conversations alike. Its kiln-dried European beech frame is built to last generations, with hand-tied eight-way springs beneath a double-layered cushion system: high-resilience foam wrapped in ethically sourced duck-feather down. The boucle upholstery, woven in Belgium, gains character with age. Legs are solid American white oak, available in natural or smoked finish.",
      features: [
        "Kiln-dried European beech hardwood frame — 25-year structural guarantee",
        "Hand-tied eight-way spring suspension",
        "High-resilience foam + duck-feather down cushion wrap",
        "Belgian boucle upholstery, pre-treated for stain resistance",
        "Solid American white oak legs — natural or smoked",
        "Modular configuration available (add chaise or ottoman)",
        "Customisable leg finish and upholstery colour",
      ],
      care: "Vacuum weekly with a soft brush attachment. Spot-clean with a damp cloth and mild fabric cleaner. Professional cleaning recommended annually. Rotate cushions fortnightly.",
      warranty: "25-year frame warranty. 5-year cushion and spring warranty. 2-year fabric warranty.",
      rating: 4.9, reviewCount: 187,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Luxe Verona 3-Seater Sofa in Oatmeal Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Verona Sofa — living room setting", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-002", slug: "portofino-feather-back-sofa",
    name: "Portofino Feather-Back Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Atelier Series", price: 495000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Cognac", "Midnight Black", "Saddle Tan", "Chalk White"],
    dimensions: { width: 218, height: 80, depth: 95, unit: "cm" }, weightKg: 86,
    isConfigurable: true, isFeatured: true, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Portofino Full-Grain Leather 3-Seater Sofa — Modulas",
    seoDescription: "Full-grain aniline leather sofa with feather-back cushions and solid brass feet. Handcrafted in India. 25-year frame warranty.",
    tags: ["premium", "subcategory:3-seater-sofas"],
    description: "Full-grain aniline leather that ages into something more beautiful than the day it arrived. Feather-back cushions create a silhouette that is both precise and inviting.",
    metadata: {
      fullDescription: "The Portofino is for those who understand that a sofa is a long-term relationship. Its shell is shaped from a solid walnut frame — visible at the legs and back rail — and upholstered in full-grain aniline leather sourced from a tannery in Kanpur that has been supplying luxury houses for four decades. The feather-back cushions are individually bagged and stitched by hand, producing a back that yields perfectly to the spine without losing shape. Solid brass feet in a brushed finish complete the look.",
      features: [
        "Solid walnut structural frame — visible leg and back rail detail",
        "Full-grain aniline leather — develops patina over time",
        "Hand-stitched, individually bagged feather-back cushions",
        "Pocket-spring seat base for consistent support",
        "Brushed solid brass feet",
        "Available in 2-seater, 3-seater, and corner configurations",
        "Conditioning kit included with every order",
      ],
      care: "Wipe with a dry microfibre cloth for daily maintenance. Apply leather conditioner every 3–4 months. Keep away from direct sunlight and heat sources to prevent fading.",
      warranty: "25-year frame warranty. 7-year leather and spring warranty.",
      rating: 4.8, reviewCount: 94,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Portofino Leather Sofa in Cognac", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Portofino — side profile detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-003", slug: "palazzo-deep-seat-sofa",
    name: "Palazzo Deep-Seat Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Modulas Originals", price: 428000, compareAtPrice: 498000, currency: "INR",
    material: "Performance Linen", finishOptions: ["Natural Flax", "Stone", "Charcoal", "Terracotta", "Sage"],
    dimensions: { width: 248, height: 78, depth: 112, unit: "cm" }, weightKg: 82,
    isConfigurable: true, isFeatured: false, stockQty: 6, leadTimeDays: 28,
    seoTitle: "Palazzo Deep-Seat Performance Linen Sofa — Modulas",
    seoDescription: "Extra-deep 112 cm sofa in performance linen. Ideal for families. Kiln-dried oak frame with anti-tip certified legs. Ships across India in 28 days.",
    tags: ["sale", "subcategory:3-seater-sofas"],
    description: "At 112 cm deep, the Palazzo is unapologetically generous. Performance linen that resists spills and fading — luxury that lives well with real life.",
    metadata: {
      fullDescription: "Designed for those who believe a sofa should be sat in, not just admired, the Palazzo offers an exceptional 112 cm seat depth — deep enough to curl up with a book, wide enough to sleep on. The performance linen blend is engineered to resist staining, pilling, and UV fading, making it suitable for homes with children, pets, and the demands of daily life — without compromising on the refined aesthetic Modulas is known for.",
      features: [
        "112 cm extra-deep seat — fits any lounging position",
        "Performance linen — stain, pill, and UV-fade resistant",
        "Kiln-dried solid oak frame with anti-tip certification",
        "High-density cold-cure foam seats — retains shape after 10+ years",
        "Reversible scatter cushions included",
        "Choice of 5 colourways across 3 fabric weights",
        "Configurable with matching ottoman",
      ],
      care: "Machine-washable cushion covers (cold, gentle cycle). Spot-clean frame fabric with damp cloth and mild detergent. Air-dry only.",
      warranty: "25-year frame warranty. 3-year fabric warranty.",
      rating: 4.7, reviewCount: 143,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Palazzo Deep-Seat Sofa in Natural Flax", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Palazzo Sofa — cushion and arm detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-004", slug: "naples-leather-grand-sofa",
    name: "Naples Leather Grand Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Heritage Collection", price: 545000, currency: "INR",
    material: "Semi-Aniline Leather", finishOptions: ["Tobacco", "Forest Green", "Bordeaux", "Dove Grey"],
    dimensions: { width: 235, height: 84, depth: 97, unit: "cm" }, weightKg: 91,
    isConfigurable: false, isFeatured: true, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Naples Leather Grand Sofa — Heritage Collection by Modulas",
    seoDescription: "Semi-aniline leather grand sofa with button-tufted seat base and solid walnut feet. A timeless statement piece. Heritage Collection by Modulas.",
    tags: ["premium", "limited", "subcategory:3-seater-sofas"],
    description: "The Naples Grand is an heirloom in the making. Semi-aniline leather, button-tufted seat base, and a solid walnut frame that tells a story of genuine craft.",
    metadata: {
      fullDescription: "Heritage Collection pieces are made in small batches and upholstered entirely by hand at our Jaipur atelier. The Naples Grand uses semi-aniline leather — retaining the hide's natural grain while adding a protective topcoat — over a button-tufted seat base that references the great English club chairs of the 19th century. The back cushions are loose, feather-filled, and plump — designed to look lived-in and at ease.",
      features: [
        "Semi-aniline leather — natural grain visible, protected topcoat",
        "Button-tufted seat base — traditional English detail",
        "Loose feather-filled back cushions",
        "Solid walnut frame — visible side and leg rail",
        "Hand-upholstered at Modulas Jaipur Atelier",
        "Available with matching club chair",
        "Personalised engraving available on seat rail",
      ],
      care: "Condition with a leather cream every 6 months. Wipe spills immediately with a clean dry cloth. Avoid placement in direct sunlight.",
      warranty: "Lifetime frame warranty. 10-year leather warranty.",
      rating: 4.9, reviewCount: 61,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Naples Leather Grand Sofa in Tobacco", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Naples — tufted seat detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-005", slug: "brescia-4-seater-sofa",
    name: "Brescia 4-Seater Grand Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Modulas Originals", price: 620000, currency: "INR",
    material: "Velvet", finishOptions: ["Sage Green", "Ink Blue", "Dusty Rose", "Graphite", "Champagne"],
    dimensions: { width: 290, height: 82, depth: 95, unit: "cm" }, weightKg: 98,
    isConfigurable: true, isFeatured: false, stockQty: 3, leadTimeDays: 35,
    seoTitle: "Brescia 4-Seater Velvet Grand Sofa — Modulas Luxury",
    seoDescription: "290 cm velvet grand sofa seating 4. Custom colour selection, kiln-dried hardwood frame. Ideal for large living rooms and open-plan spaces.",
    tags: ["new", "subcategory:3-seater-sofas"],
    description: "When a 3-seater isn't enough. The Brescia stretches to 290 cm — a velvet expanse that transforms any room into a gathering place.",
    metadata: {
      fullDescription: "The Brescia was designed to anchor the grandest of rooms. At 290 cm, it comfortably seats four, with individual pocket-spring seat cushions that prevent the central sag common in large sofas. The crushed velvet pile is woven in a tight loop that resists marking and compression — it looks as good after five years as the day it arrived. Legs are turned solid oak, available in natural or ebonised finish.",
      features: [
        "290 cm width — comfortably seats 4 adults",
        "Individual pocket-spring cushions — no central sag",
        "Crushed velvet — mark and compression resistant",
        "Turned solid oak legs — natural or ebonised",
        "Kiln-dried hardwood frame — 25-year guarantee",
        "5 colourways; custom colours available on request",
        "Matching ottoman and dining chair fabric coordination available",
      ],
      care: "Brush velvet pile regularly with a soft-bristle brush. Steam clean annually. Avoid direct sunlight to preserve pile depth and colour.",
      warranty: "25-year frame. 5-year velvet and spring warranty.",
      rating: 4.8, reviewCount: 52,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Brescia 4-Seater Sofa in Sage Green Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Brescia — large living room setting", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-006", slug: "ravenna-slim-arm-sofa",
    name: "Ravenna Slim-Arm Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Atelier Series", price: 345000, currency: "INR",
    material: "Belgian Linen", finishOptions: ["Warm White", "Wheat", "Blush", "Soft Grey"],
    dimensions: { width: 215, height: 75, depth: 88, unit: "cm" }, weightKg: 71,
    isConfigurable: true, isFeatured: false, stockQty: 9, leadTimeDays: 21,
    seoTitle: "Ravenna Slim-Arm Belgian Linen Sofa — Modulas Atelier Series",
    seoDescription: "Minimalist slim-arm sofa in Belgian linen. Low profile, generous seat. Perfect for contemporary and Japandi interiors. Atelier Series by Modulas.",
    tags: ["subcategory:3-seater-sofas"],
    description: "A sofa that knows when to step back. The Ravenna's slim arms and low profile create breathing room — Belgian linen in four calm colourways.",
    metadata: {
      fullDescription: "Inspired by Scandinavian residential design, the Ravenna strips the sofa down to its essentials without sacrificing comfort. The arm width is a deliberate 12 cm — nearly half that of traditional sofas — creating a sense of visual lightness that suits smaller rooms and open-plan spaces equally. Belgian linen is chosen for its texture and its ability to take on depth of colour without looking heavy.",
      features: [
        "12 cm slim arms — maximum seating width in minimal footprint",
        "Low 75 cm profile — suits contemporary and Japandi interiors",
        "Belgian linen — woven in Ghent, Belgium",
        "Kiln-dried beech hardwood frame",
        "High-resilience cold-cure foam cushions",
        "Hairpin legs in brushed steel or brass",
        "Matching 2-seater available",
      ],
      care: "Dry-clean cushion covers. Spot-clean frame with a damp cloth. Linen naturally softens with use — embrace the texture.",
      warranty: "15-year frame. 3-year fabric warranty.",
      rating: 4.7, reviewCount: 108,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Ravenna Slim-Arm Sofa in Warm White Linen", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Ravenna — arm and leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-007", slug: "como-chesterfield-sofa",
    name: "Como Chesterfield Sofa", categorySlug: "sofas", subcategorySlug: "chesterfields",
    brand: "Heritage Collection", price: 520000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Antique Tan", "British Racing Green", "Oxblood", "Midnight Navy"],
    dimensions: { width: 208, height: 79, depth: 90, unit: "cm" }, weightKg: 89,
    isConfigurable: false, isFeatured: true, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Como Chesterfield Full-Grain Leather Sofa — Heritage Collection Modulas",
    seoDescription: "Classic Chesterfield in full-grain leather. Deep button-tufting, rolled arms, and nail-head trim. Hand-built at Modulas Jaipur Atelier.",
    tags: ["premium", "limited", "subcategory:chesterfields"],
    description: "The Chesterfield, perfected. Deep button-tufting by hand, rolled arms, and full-grain leather that develops a personality unique to each owner.",
    metadata: {
      fullDescription: "The Como Chesterfield is made exactly as Chesterfields have always been made: slowly, by hand, with no shortcuts. Each button is set by a craftsman using a long needle and twine, pulling the leather taut into perfect diamond tufts. The rolled arms are shaped over solid beech formers and upholstered in the same leather hide as the body — ensuring colour continuity across the full piece. Nail-head trim in antique brass finishes the silhouette.",
      features: [
        "Hand-set button tufting — each button individually positioned",
        "Rolled arms over solid beech formers",
        "Antique brass nail-head trim",
        "Full-grain leather from a certified Indian tannery",
        "Coil-spring seat base — traditional construction",
        "Solid walnut bun feet",
        "Available as 2-seater, 3-seater, or armchair set",
      ],
      care: "Condition with leather balsam every 3 months. Dust regularly with a soft cloth. The tufted areas can be gently cleaned with a leather foam cleaner applied with a soft brush.",
      warranty: "Lifetime frame. 10-year leather warranty.",
      rating: 4.9, reviewCount: 73,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Como Chesterfield in Antique Tan Leather", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Como — button tufting detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SOF-008", slug: "catania-compact-sofa",
    name: "Catania Compact Sofa", categorySlug: "sofas", subcategorySlug: "3-seater-sofas",
    brand: "Modulas Originals", price: 265000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Cloud White", "Pebble", "Midnight", "Terracotta"],
    dimensions: { width: 195, height: 78, depth: 86, unit: "cm" }, weightKg: 64,
    isConfigurable: true, isFeatured: false, stockQty: 12, leadTimeDays: 21,
    seoTitle: "Catania Compact Boucle 3-Seater Sofa — Modulas",
    seoDescription: "195 cm compact 3-seater sofa in premium boucle. Ideal for apartments and compact living rooms. Ships India-wide in 21 days.",
    tags: ["bestseller", "subcategory:3-seater-sofas"],
    description: "Big comfort in a considered footprint. The Catania fits where other 3-seaters can't — without compromising on seat depth or frame quality.",
    metadata: {
      fullDescription: "The Catania was born from a brief to build a proper 3-seater sofa for Indian urban apartments, where rooms are generous but not vast. At 195 cm, it fits in rooms where a standard 210+ cm sofa would crowd the space. Yet it seats three adults comfortably, thanks to a 86 cm seat depth and a high-resilience foam cushion system that doesn't compress flat after a year of use. Available in four boucle colourways with contrasting piping as an optional detail.",
      features: [
        "195 cm compact width — fits Indian apartment layouts",
        "86 cm seat depth — seats 3 without compromise",
        "High-resilience foam with anti-sag webbing",
        "Premium boucle — woven in Belgium",
        "Solid beech frame — 20-year guarantee",
        "Tapered solid oak legs — 3 finish options",
        "Optional contrast piping available",
      ],
      care: "Vacuum with soft brush weekly. Spot-clean with boucle-safe foam cleaner. Rotate cushions monthly.",
      warranty: "20-year frame. 3-year fabric warranty.",
      rating: 4.6, reviewCount: 221,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Catania Compact Sofa in Cloud White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Catania — apartment living context", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Sectional Sofas (5) ────────────────────────────────────────
  {
    sku: "MOD-SEC-001", slug: "aria-cloud-sectional",
    name: "Aria Cloud Sectional", categorySlug: "sofas", subcategorySlug: "sectional-sofas",
    brand: "Modulas Originals", price: 785000, compareAtPrice: 945000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm White", "Stone", "Sage", "Slate"],
    dimensions: { width: 310, height: 80, depth: 165, unit: "cm" }, weightKg: 148,
    isConfigurable: true, isFeatured: true, stockQty: 3, leadTimeDays: 42,
    seoTitle: "Aria Cloud L-Shape Boucle Sectional Sofa — Modulas",
    seoDescription: "Large L-shape sectional sofa in premium boucle. 310 × 165 cm. Modular — add or remove sections. Kiln-dried frame, feather-down cushions.",
    tags: ["bestseller", "sale", "subcategory:sectional-sofas"],
    description: "The Aria fills a room with warmth rather than weight. Modular by design — every section can be reconfigured as your home evolves.",
    metadata: {
      fullDescription: "The Aria Cloud is Modulas's best-selling piece — a modular boucle sectional that has found its way into living rooms across India. Each module is independently sprung and cushioned, which means you can rearrange, add a chaise, or remove a section without disrupting the integrity of the whole. The boucle is woven in a tight loop that resists flattening, and the feather-down wrap on each cushion ensures the sofa looks inviting even after years of use.",
      features: [
        "Fully modular — chaise left or right, add 1-seat sections",
        "Individual pocket-spring modules — no shared base",
        "Feather-down wrapped high-resilience foam cushions",
        "Belgian boucle — loop-woven, anti-crush pile",
        "Kiln-dried hardwood frame throughout",
        "Solid oak legs — natural, smoked, or ebonised",
        "10-year modular compatibility guarantee",
      ],
      care: "Vacuum monthly. Feather cushions — plump daily. Professional steam clean annually. Remove and spot-clean covers as needed.",
      warranty: "25-year frame. 5-year spring and cushion. 3-year fabric.",
      rating: 4.9, reviewCount: 312,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Aria Cloud Sectional in Warm White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Aria Sectional — modular detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SEC-002", slug: "milan-corner-sectional",
    name: "Milan Corner Sectional", categorySlug: "sofas", subcategorySlug: "sectional-sofas",
    brand: "Modulas Originals", price: 920000, currency: "INR",
    material: "Performance Linen", finishOptions: ["Natural Flax", "Charcoal", "Terracotta", "Deep Teal"],
    dimensions: { width: 340, height: 82, depth: 180, unit: "cm" }, weightKg: 168,
    isConfigurable: true, isFeatured: true, stockQty: 2, leadTimeDays: 42,
    seoTitle: "Milan Large Corner Sectional Sofa in Performance Linen — Modulas",
    seoDescription: "340 cm large corner sectional in stain-resistant performance linen. 7 modules, configurable layout. For large living rooms and open-plan spaces.",
    tags: ["premium", "new", "subcategory:sectional-sofas"],
    description: "The Milan takes the corner and makes it the centre of the room. Seven modules, infinite configurations — performance linen that shrugs off real life.",
    metadata: {
      fullDescription: "Designed for the generous proportions of contemporary Indian homes, the Milan Corner Sectional ships in seven individual modules that can be assembled in multiple L-shapes, U-shapes, or peninsula configurations. The performance linen is certified for 100,000 double-rub abrasion resistance — making it one of the most durable fabrics in our collection while maintaining the quiet elegance of natural linen texture.",
      features: [
        "7 independent modules — multiple layout configurations",
        "Performance linen — 100,000 double-rub certified",
        "Individual pocket-spring seat in each module",
        "USB-C and wireless charging integrated in one armrest",
        "Adjustable headrest on chaise module",
        "Storage ottoman module available",
        "Custom fabric and leg finish options",
      ],
      care: "Performance linen can be wiped with a damp cloth. Machine-washable removable covers. Professional clean for full sections.",
      warranty: "25-year frame. 5-year module compatibility. 5-year fabric.",
      rating: 4.8, reviewCount: 147,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Milan Corner Sectional in Natural Flax", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Milan Sectional — corner module detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SEC-003", slug: "amalfi-l-shape-sectional",
    name: "Amalfi L-Shape Sectional", categorySlug: "sofas", subcategorySlug: "sectional-sofas",
    brand: "Atelier Series", price: 695000, currency: "INR",
    material: "Velvet", finishOptions: ["Forest Green", "Ink Blue", "Burnt Sienna", "Pewter"],
    dimensions: { width: 285, height: 84, depth: 155, unit: "cm" }, weightKg: 138,
    isConfigurable: true, isFeatured: false, stockQty: 4, leadTimeDays: 35,
    seoTitle: "Amalfi L-Shape Velvet Sectional Sofa — Atelier Series Modulas",
    seoDescription: "Velvet L-shape sectional in 4 rich colourways. 285 cm wide. Deep seats, feather-down cushions. Atelier Series — handcrafted in India.",
    tags: ["premium", "subcategory:sectional-sofas"],
    description: "Rich velvet in four considered colourways — the Amalfi brings colour and depth to a sectional format that is usually played safe.",
    metadata: {
      fullDescription: "The Amalfi challenges the convention that sectionals must be neutral. Its velvet pile — woven in a tight 500gsm loop — comes in four colours chosen to work with warm wood tones, marble surfaces, and the light conditions typical of Indian interiors. The frame is solid beech, and the seat suspension uses a combination of sinuous springs and webbing — proven to outlast coil-spring systems in high-use environments.",
      features: [
        "500 gsm velvet — tight loop weave, crush-resistant",
        "4 rich colourways curated for Indian interior light",
        "Sinuous spring + webbing seat suspension",
        "Removable, washable cushion covers",
        "Reversible chaise — left or right configuration",
        "Solid beech frame — 20-year guarantee",
        "Matching accent chair available",
      ],
      care: "Brush velvet with a soft-bristle brush after use. Steam clean annually. Keep out of direct sunlight to preserve colour depth.",
      warranty: "20-year frame. 4-year velvet and spring.",
      rating: 4.8, reviewCount: 89,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Amalfi Sectional in Forest Green Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Amalfi — velvet pile detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SEC-004", slug: "vicenza-modular-sectional",
    name: "Vicenza Modular Sectional", categorySlug: "sofas", subcategorySlug: "sectional-sofas",
    brand: "Modulas Originals", price: 845000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Oatmeal", "Warm Sand", "Dove Grey", "Blush"],
    dimensions: { width: 320, height: 78, depth: 170, unit: "cm" }, weightKg: 155,
    isConfigurable: true, isFeatured: false, stockQty: 3, leadTimeDays: 42,
    seoTitle: "Vicenza Fully Modular Boucle Sectional — Modulas",
    seoDescription: "Fully modular boucle sectional — reconfigure at any time. 8 sections, connectors included. 25-year frame. Free home delivery and assembly.",
    tags: ["new", "subcategory:sectional-sofas"],
    description: "The Vicenza grows with your home. Eight modular sections connect magnetically — reconfigure in minutes without tools.",
    metadata: {
      fullDescription: "Modular furniture should be truly modular — not just sectional in name. The Vicenza uses patented magnetic connectors to join sections, so reconfiguration takes minutes rather than hours. The system includes 8 modules: two corner pieces, four singles, one armless unit, and one chaise. Any combination is structurally sound. The boucle cover is zipped on each module for easy cleaning and eventual reupholstery.",
      features: [
        "Patented magnetic connectors — tool-free reconfiguration",
        "8 modules — corners, singles, armless, chaise",
        "Zipped boucle covers — fully removable and cleanable",
        "Individual pocket-spring cushion per module",
        "Low 78 cm profile — visually light in any space",
        "Matching coffee table and side table available",
        "Covers available in all Modulas fabrics",
      ],
      care: "Remove and machine-wash covers (cool, gentle cycle). Vacuum inner cushions monthly. Magnetic connectors require no maintenance.",
      warranty: "25-year frame. Lifetime connector guarantee. 3-year cover warranty.",
      rating: 4.7, reviewCount: 78,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Vicenza Modular Sectional in Oatmeal Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Vicenza — magnetic connector detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SEC-005", slug: "lecce-modular-corner",
    name: "Lecce Modular Corner Sofa", categorySlug: "sofas", subcategorySlug: "sectional-sofas",
    brand: "Modulas Originals", price: 635000, currency: "INR",
    material: "Performance Linen", finishOptions: ["Stone", "Sand", "Cream", "Graphite"],
    dimensions: { width: 275, height: 80, depth: 145, unit: "cm" }, weightKg: 128,
    isConfigurable: true, isFeatured: false, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Lecce Modular Corner Sofa in Performance Linen — Modulas",
    seoDescription: "Modular corner sofa in stain-resistant performance linen. 5-section system. Left or right chaise. Free assembly pan-India.",
    tags: ["subcategory:sectional-sofas"],
    description: "A corner sofa that earns its place. The Lecce's 5-section system adapts to left-hand or right-hand configurations without additional cost.",
    metadata: {
      fullDescription: "The Lecce is designed for the practical luxury buyer — someone who wants a sectional that works in today's home and can be adapted for tomorrow's. The 5-section system (two arms, two seats, one corner) ships in standard-width cartons that fit in lifts and narrow staircases, then connects with steel coupling plates that lock each module rigidly in place. Performance linen means the sofa can be wiped clean of most spills.",
      features: [
        "5-section modular system — no tools required",
        "Ships in lift-compatible packaging",
        "Steel coupling plate connectors — rigid and rattle-free",
        "Left or right chaise — reconfigurable at home",
        "Performance linen — 80,000 double-rub rated",
        "High-resilience cold-cure foam cushions",
        "Solid oak legs — 3 finish options",
      ],
      care: "Wipe with damp cloth for most spills. Machine-wash cushion covers (cool). Professional upholstery clean every 2 years.",
      warranty: "20-year frame. 3-year fabric. 5-year connector warranty.",
      rating: 4.6, reviewCount: 115,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Lecce Corner Sofa in Stone Linen", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Lecce — section connector detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── 2-Seater Sofas (4) ───────────────────────────────────────
  {
    sku: "MOD-2ST-001", slug: "riviera-boucle-2-seater",
    name: "Riviera Boucle 2-Seater", categorySlug: "sofas", subcategorySlug: "2-seater-sofas",
    brand: "Atelier Series", price: 245000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Ivory", "Blush", "Slate", "Ochre"],
    dimensions: { width: 168, height: 80, depth: 92, unit: "cm" }, weightKg: 58,
    isConfigurable: true, isFeatured: false, stockQty: 10, leadTimeDays: 21,
    seoTitle: "Riviera Boucle 2-Seater Sofa — Atelier Series Modulas",
    seoDescription: "Elegant boucle 2-seater sofa. 168 cm wide, 92 cm deep. Ideal for reading rooms, studies, and secondary living spaces.",
    tags: ["subcategory:2-seater-sofas"],
    description: "A 2-seater that refuses to be an afterthought. The Riviera has the proportions and detailing of a full sofa — just scaled for more intimate spaces.",
    metadata: {
      fullDescription: "The Riviera was designed to bring the same quality as Modulas's full-size sofas to smaller spaces — studies, reading rooms, guest bedrooms, and apartment second-living-areas. Every element is present: kiln-dried hardwood frame, hand-tied springs, feather-down cushion wrap, and Belgian boucle. The only thing reduced is the width.",
      features: [
        "168 cm width — ideal for compact rooms",
        "Kiln-dried hardwood frame — 25-year guarantee",
        "Hand-tied eight-way springs",
        "Feather-down wrapped foam cushions",
        "Belgian boucle in 4 colourways",
        "Tapered solid oak legs",
        "Matching 3-seater and armchair available",
      ],
      care: "Vacuum weekly. Spot-clean with boucle cleaner. Feather cushions — plump daily.",
      warranty: "25-year frame. 3-year fabric.",
      rating: 4.7, reviewCount: 134,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Riviera 2-Seater in Ivory Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Riviera — reading room context", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-2ST-002", slug: "torino-loveseat",
    name: "Torino Velvet Loveseat", categorySlug: "sofas", subcategorySlug: "2-seater-sofas",
    brand: "Modulas Originals", price: 195000, currency: "INR",
    material: "Velvet", finishOptions: ["Emerald", "Sapphire", "Rose Gold", "Charcoal"],
    dimensions: { width: 152, height: 82, depth: 86, unit: "cm" }, weightKg: 52,
    isConfigurable: false, isFeatured: false, stockQty: 14, leadTimeDays: 14,
    seoTitle: "Torino Velvet Loveseat Sofa — Modulas Luxury Furniture",
    seoDescription: "Velvet loveseat in 4 jewel-tone colourways. 152 cm compact width. Perfect for studies, bedrooms, and boutique hotel-style spaces.",
    tags: ["new", "subcategory:2-seater-sofas"],
    description: "The Torino sits in the room like a jewel — compact, precise, and unforgettable in any of four rich velvet colourways.",
    metadata: {
      fullDescription: "A loveseat should create a sense of intimacy. The Torino's 152 cm width and its deeply tufted back panel draw two people naturally closer — it is equally at home in a master bedroom sitting area as a formal drawing room. The velvet is woven in a 480 gsm pile that holds its colour and sheen even in high-traffic positions.",
      features: [
        "152 cm compact width — fits any room",
        "Deeply tufted back panel",
        "480 gsm velvet — rich sheen, colour-fast",
        "Solid walnut show-wood frame visible at arms and back rail",
        "Sinuous spring seat base",
        "Brass nailhead trim optional",
        "Available with or without scatter cushions",
      ],
      care: "Brush velvet pile after use. Spot-clean with velvet-specific cleaner. Do not saturate fabric.",
      warranty: "15-year frame. 3-year velvet warranty.",
      rating: 4.8, reviewCount: 97,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Torino Loveseat in Emerald Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Torino — tufted back detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-2ST-003", slug: "parma-boucle-armchair-sofa",
    name: "Parma Boucle Compact Sofa", categorySlug: "sofas", subcategorySlug: "2-seater-sofas",
    brand: "Modulas Originals", price: 218000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm Cream", "Sage", "Caramel", "Pebble"],
    dimensions: { width: 158, height: 79, depth: 88, unit: "cm" }, weightKg: 54,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 21,
    seoTitle: "Parma Compact Boucle 2-Seater Sofa — Modulas",
    seoDescription: "Compact boucle 2-seater sofa, 158 cm. Feather-wrapped cushions, solid oak legs. Pairs with Parma armchair for complete seating set.",
    tags: ["subcategory:2-seater-sofas"],
    description: "The Parma brings the full boucle experience to the 2-seat format — feather-wrapped cushions, solid oak legs, and a silhouette that pairs naturally with the Parma armchair.",
    metadata: {
      fullDescription: "Designed as part of the Parma seating family, this 2-seater maintains the same frame construction, spring depth, and cushion specification as the matching armchair and 3-seater. Purchasing as a set qualifies for coordinated colour-matching across all pieces and a 10% family discount.",
      features: [
        "158 cm width — ideal for secondary living areas",
        "Feather-down wrapped foam cushions",
        "Solid oak legs — natural or smoked",
        "Part of the Parma family — coordinate with armchair and 3-seater",
        "Kiln-dried beech frame",
        "Premium Belgian boucle",
        "10% family discount when purchased as a set",
      ],
      care: "Vacuum weekly. Spot-clean with boucle cleaner. Feather cushions — plump and rotate.",
      warranty: "25-year frame. 3-year fabric.",
      rating: 4.7, reviewCount: 82,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Parma 2-Seater in Warm Cream Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85", altText: "Parma — leg and cushion detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-2ST-004", slug: "genova-slim-two-seater",
    name: "Genova Slim 2-Seater", categorySlug: "sofas", subcategorySlug: "2-seater-sofas",
    brand: "Atelier Series", price: 175000, currency: "INR",
    material: "Belgian Linen", finishOptions: ["Warm White", "Wheat", "Soft Blue", "Sage Green"],
    dimensions: { width: 145, height: 76, depth: 82, unit: "cm" }, weightKg: 46,
    isConfigurable: false, isFeatured: false, stockQty: 16, leadTimeDays: 14,
    seoTitle: "Genova Slim Belgian Linen 2-Seater Sofa — Atelier Series",
    seoDescription: "145 cm slim 2-seater sofa in Belgian linen. Low 76 cm profile. Ships in 14 days. Ideal for compact Indian apartments.",
    tags: ["subcategory:2-seater-sofas"],
    description: "At 145 cm, the Genova is the smallest sofa in the Modulas collection — and arguably the most elegant. Belgian linen, hairpin legs, low profile.",
    metadata: {
      fullDescription: "The Genova was designed with the studio apartment and the small reading room in mind. Its 145 cm width and 76 cm low profile create a piece that commands attention without dominating the room. Belgian linen — in four calm colourways — adds texture without weight. Hairpin legs in brushed steel keep the floor visible, increasing the sense of space.",
      features: [
        "145 cm width — smallest sofa in Modulas range",
        "76 cm low profile — visually lightweight",
        "Belgian linen — naturally textured, soft-hand feel",
        "Brushed steel hairpin legs",
        "High-resilience foam cushions",
        "Kiln-dried beech frame",
        "Scatter cushions included",
      ],
      care: "Dry-clean cushion covers. Spot-clean frame fabric with damp cloth.",
      warranty: "15-year frame. 2-year fabric.",
      rating: 4.6, reviewCount: 164,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Genova 2-Seater in Warm White Linen", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Genova — hairpin leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Accent Chairs (5) ──────────────────────────────────────────
  {
    sku: "MOD-CHR-001", slug: "capri-velvet-swivel-chair",
    name: "Capri Velvet Swivel Chair", categorySlug: "sofas", subcategorySlug: "accent-chairs",
    brand: "Atelier Series", price: 148000, compareAtPrice: 178000, currency: "INR",
    material: "Velvet", finishOptions: ["Forest Green", "Burnt Sienna", "Ink Blue", "Chalk", "Burgundy"],
    dimensions: { width: 78, height: 82, depth: 78, unit: "cm" }, weightKg: 24,
    isConfigurable: false, isFeatured: true, stockQty: 18, leadTimeDays: 14,
    seoTitle: "Capri Velvet Swivel Lounge Chair — Atelier Series Modulas",
    seoDescription: "360° swivel lounge chair in premium velvet. Solid brass disc base. 5 colourways. Ships across India in 14 days.",
    tags: ["bestseller", "sale", "subcategory:accent-chairs"],
    description: "A fully upholstered swivel chair on a polished brass disc base. Five velvet colourways — each chosen to command a corner without needing a companion.",
    metadata: {
      fullDescription: "The Capri Swivel has become one of Modulas's signature pieces — a chair that works as a reading chair, a TV chair, or simply as a sculptural object in the room. Its 360° smooth-bearing swivel base is machined from solid brass, polished and lacquered to prevent tarnishing. The shell is fully upholstered in 480 gsm velvet, with a sprung seat base that prevents cushion fatigue.",
      features: [
        "360° smooth-bearing swivel — polished solid brass base",
        "Fully upholstered shell — no exposed frame",
        "480 gsm velvet — crush-resistant pile",
        "Sprung seat base — retains shape after years of use",
        "5 jewel-tone colourways",
        "Matching footstool available",
        "Available in boucle and linen variants",
      ],
      care: "Brush velvet after use. Spot-clean with foam velvet cleaner. Polish brass base with a soft dry cloth.",
      warranty: "10-year frame and swivel mechanism. 3-year fabric.",
      rating: 4.9, reviewCount: 247,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Capri Swivel Chair in Forest Green Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Capri — brass base detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-CHR-002", slug: "venezia-wingback-chair",
    name: "Venezia Wingback Chair", categorySlug: "sofas", subcategorySlug: "accent-chairs",
    brand: "Heritage Collection", price: 165000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Cognac", "Midnight Black", "Tobacco", "British Racing Green"],
    dimensions: { width: 82, height: 105, depth: 86, unit: "cm" }, weightKg: 28,
    isConfigurable: false, isFeatured: false, stockQty: 7, leadTimeDays: 28,
    seoTitle: "Venezia Wingback Leather Chair — Heritage Collection Modulas",
    seoDescription: "Classic wingback chair in full-grain leather. High-back, wide wings, bun feet. Heritage Collection — hand-built at Modulas Jaipur Atelier.",
    tags: ["premium", "subcategory:accent-chairs"],
    description: "The wingback in its truest form — high back, pronounced wings, and the kind of presence that earns a room its character.",
    metadata: {
      fullDescription: "The Venezia is Heritage Collection's interpretation of the English wingback chair, a form that has survived three centuries because it is functionally perfect. The high back and lateral wings create a pocket of warmth around the seated figure — originally designed to shield a reader from draughts, today creating an intimate zone within an open room. Upholstered in full-grain leather with visible natural grain and secured with brass nailhead trim.",
      features: [
        "High 105 cm back — classical wingback proportion",
        "Full-grain leather — grain-visible, develops patina",
        "Antique brass nailhead trim",
        "Coil-spring seat — traditional construction",
        "Solid walnut bun feet",
        "Available with matching footstool",
        "Hand-built at Modulas Jaipur Atelier",
      ],
      care: "Condition monthly with leather balsam. Dust regularly. Nailhead trim — polish with a dry cloth.",
      warranty: "Lifetime frame. 10-year leather.",
      rating: 4.9, reviewCount: 58,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Venezia Wingback Chair in Cognac Leather", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Venezia — nailhead trim detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-CHR-003", slug: "montecarlo-accent-chair",
    name: "Montecarlo Accent Chair", categorySlug: "sofas", subcategorySlug: "accent-chairs",
    brand: "Modulas Originals", price: 95000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm White", "Sage", "Blush", "Stone"],
    dimensions: { width: 72, height: 84, depth: 76, unit: "cm" }, weightKg: 18,
    isConfigurable: false, isFeatured: false, stockQty: 22, leadTimeDays: 14,
    seoTitle: "Montecarlo Boucle Accent Chair — Modulas Luxury Furniture",
    seoDescription: "Boucle accent lounge chair in 4 colourways. Walnut legs, pocket-spring seat. Compact at 72 cm wide. Ideal as a reading or statement chair.",
    tags: ["bestseller", "subcategory:accent-chairs"],
    description: "The Montecarlo is a chair that asks to be sat in. Boucle, pocket springs, walnut legs — everything a reading chair should be.",
    metadata: {
      fullDescription: "Simple things, done properly. The Montecarlo lounge chair has a barrel-back form — gently curved at the shoulders to support the upper back without constraining it — and a seat that uses pocket springs rather than foam alone, giving a more responsive and longer-lasting sit. The walnut legs are slender-tapered, making the chair look lighter than its specification suggests.",
      features: [
        "Barrel-back form — supportive without constraining",
        "Pocket-spring seat — more responsive than foam-only",
        "Premium Belgian boucle",
        "Slender-tapered walnut legs",
        "72 cm compact width",
        "Available with matching footstool",
        "Pairs with all Modulas sofa ranges",
      ],
      care: "Vacuum with soft brush. Spot-clean boucle with foam cleaner.",
      warranty: "15-year frame. 3-year fabric.",
      rating: 4.7, reviewCount: 188,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Montecarlo Accent Chair in Warm White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Montecarlo — walnut leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-CHR-004", slug: "roma-channel-back-armchair",
    name: "Roma Channel-Back Armchair", categorySlug: "sofas", subcategorySlug: "accent-chairs",
    brand: "Atelier Series", price: 112000, currency: "INR",
    material: "Velvet", finishOptions: ["Dusty Pink", "Sage", "Champagne", "Teal"],
    dimensions: { width: 75, height: 86, depth: 80, unit: "cm" }, weightKg: 20,
    isConfigurable: false, isFeatured: false, stockQty: 14, leadTimeDays: 14,
    seoTitle: "Roma Channel-Back Velvet Armchair — Atelier Series Modulas",
    seoDescription: "Channel-back velvet armchair in 4 pastel and jewel-tone colourways. Solid brass feet, sprung seat. Mid-century modern inspiration.",
    tags: ["new", "subcategory:accent-chairs"],
    description: "Vertical channel tufting gives the Roma's back its distinctive rhythm. A mid-century silhouette in four velvet colourways that elevate any corner.",
    metadata: {
      fullDescription: "Channel-back tufting — vertical columns of stitching that run the full height of the backrest — creates a visual rhythm that is simultaneously modern and historical. The Roma's channel back is set 5 cm proud of the frame, creating a floating effect when viewed from the side. The seat uses a sinuous spring base with a 60 cm seat depth — generously proportioned for an armchair of this size.",
      features: [
        "Vertical channel-back tufting — full-height",
        "60 cm seat depth — generous for an accent chair",
        "Sinuous spring seat base",
        "Solid brass feet — round, brushed finish",
        "Velvet in 4 considered colourways",
        "Exposed wood armrests — solid walnut",
        "Matches Roma footstool",
      ],
      care: "Brush velvet with a soft brush. Spot-clean with velvet foam cleaner. Polish walnut arms with furniture wax twice yearly.",
      warranty: "15-year frame. 3-year velvet.",
      rating: 4.8, reviewCount: 76,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Roma Channel-Back Armchair in Dusty Pink", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Roma — channel-back detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-CHR-005", slug: "siena-boucle-reading-chair",
    name: "Siena Boucle Reading Chair", categorySlug: "sofas", subcategorySlug: "accent-chairs",
    brand: "Modulas Originals", price: 88000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Ivory", "Warm Sand", "Slate", "Forest"],
    dimensions: { width: 70, height: 88, depth: 78, unit: "cm" }, weightKg: 17,
    isConfigurable: false, isFeatured: false, stockQty: 25, leadTimeDays: 10,
    seoTitle: "Siena Boucle Reading Chair — Modulas Luxury Accent Chairs",
    seoDescription: "Boucle reading armchair with high back and wide seat. 70 cm wide. Ships in 10 days. Available in 4 colourways.",
    tags: ["subcategory:accent-chairs"],
    description: "Designed around the act of reading — a high back for neck support, wide arms for a drink or a book, and boucle that feels as good as it looks.",
    metadata: {
      fullDescription: "The Siena was designed with a single-use case in mind — and executed perfectly. The high 88 cm back supports the neck without forcing the reader upright; the arm width of 18 cm is sufficient to rest a forearm or balance a cup. The boucle upholstery is pre-treated with an anti-pill finish that keeps the texture pristine even after years of daily use.",
      features: [
        "High 88 cm back — neck support for extended reading",
        "18 cm wide arms — rest forearm or balance a cup",
        "Anti-pill boucle finish",
        "Pocket-spring seat",
        "70 cm compact width",
        "Solid walnut legs",
        "Available with matching footstool",
      ],
      care: "Vacuum weekly. Spot-clean with boucle-specific cleaner.",
      warranty: "15-year frame. 3-year fabric.",
      rating: 4.7, reviewCount: 203,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Siena Reading Chair in Ivory Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Siena — high back and arm detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Ottomans & Poufs (3) ────────────────────────────────────────
  {
    sku: "MOD-OTM-001", slug: "florence-boucle-ottoman",
    name: "Florence Boucle Ottoman", categorySlug: "sofas", subcategorySlug: "ottomans-poufs",
    brand: "Modulas Originals", price: 48000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Cream", "Charcoal", "Sage", "Blush"],
    dimensions: { width: 80, height: 40, depth: 80, unit: "cm" }, weightKg: 12,
    isConfigurable: false, isFeatured: false, stockQty: 30, leadTimeDays: 10,
    seoTitle: "Florence Boucle Round Ottoman — Modulas Luxury Furniture",
    seoDescription: "Round boucle ottoman in 4 colourways. 80 cm diameter. Solid oak plinth base. Works as footrest, coffee table, or extra seating.",
    tags: ["bestseller", "subcategory:ottomans-poufs"],
    description: "A round boucle ottoman on a solid oak plinth — works as a footrest, a coffee table with a tray, or a seat for unexpected guests.",
    metadata: {
      fullDescription: "The Florence Ottoman was designed to serve multiple roles without looking like it's trying too hard. Its 80 cm diameter is wide enough to use as a small coffee table when topped with a tray, yet low enough at 40 cm to function as a generous footrest. The solid oak plinth base adds a material contrast — visible through the boucle drape on each side.",
      features: [
        "80 cm diameter — functional as footrest or coffee table",
        "Solid oak plinth base — visible through boucle drape",
        "High-density foam — retains shape under weight",
        "Belgian boucle in 4 colourways",
        "Non-slip felt base",
        "Available in square configuration",
        "Pairs with all Modulas sofas",
      ],
      care: "Spot-clean boucle with foam cleaner. Polish oak base with furniture wax annually.",
      warranty: "5-year structural warranty.",
      rating: 4.6, reviewCount: 312,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Florence Ottoman in Cream Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Florence — plinth base detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-OTM-002", slug: "tuscany-leather-pouf",
    name: "Tuscany Leather Pouf", categorySlug: "sofas", subcategorySlug: "ottomans-poufs",
    brand: "Heritage Collection", price: 38000, currency: "INR",
    material: "Full-Grain Leather", finishOptions: ["Tan", "Cognac", "Black", "Olive"],
    dimensions: { width: 65, height: 38, depth: 65, unit: "cm" }, weightKg: 6,
    isConfigurable: false, isFeatured: false, stockQty: 20, leadTimeDays: 10,
    seoTitle: "Tuscany Full-Grain Leather Pouf — Heritage Collection Modulas",
    seoDescription: "Full-grain leather pouf in 4 colourways. 65 cm diameter. Hand-stitched seams. Part of Heritage Collection by Modulas.",
    tags: ["premium", "subcategory:ottomans-poufs"],
    description: "Full-grain leather, hand-stitched by craftsmen in Jaipur. The Tuscany Pouf develops its own story with every year of use.",
    metadata: {
      fullDescription: "The Tuscany Pouf is a Heritage Collection piece — made entirely by hand in small batches at the Modulas Jaipur Atelier. Its full-grain leather panels are hand-cut, stitched, and stuffed with a combination of recycled fibre and high-density foam. The topstitching around each panel is done with waxed thread for durability and visual contrast.",
      features: [
        "Full-grain leather — develops patina with age",
        "Hand-cut and stitched leather panels",
        "Waxed topstitching — durable and decorative",
        "Recycled fibre and high-density foam fill",
        "Non-slip base",
        "Personalised embossing available on base",
        "Hand-built at Jaipur Atelier",
      ],
      care: "Wipe with a dry cloth. Condition every 6 months with leather balm.",
      warranty: "5-year structural. 3-year leather.",
      rating: 4.8, reviewCount: 145,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Tuscany Leather Pouf in Tan", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Tuscany — stitching detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-OTM-003", slug: "padova-round-velvet-pouf",
    name: "Padova Round Velvet Pouf", categorySlug: "sofas", subcategorySlug: "ottomans-poufs",
    brand: "Modulas Originals", price: 28000, currency: "INR",
    material: "Velvet", finishOptions: ["Emerald", "Dusty Pink", "Mustard", "Midnight"],
    dimensions: { width: 55, height: 35, depth: 55, unit: "cm" }, weightKg: 4,
    isConfigurable: false, isFeatured: false, stockQty: 35, leadTimeDays: 7,
    seoTitle: "Padova Round Velvet Pouf — Modulas Luxury Seating Accessories",
    seoDescription: "Velvet round pouf in 4 jewel tones. 55 cm diameter. Ships in 7 days. Ideal as footrest or casual extra seating.",
    tags: ["subcategory:ottomans-poufs"],
    description: "The smallest piece in the Modulas collection — and in any colour, one of the most useful. A velvet pouf that earns its place in any room.",
    metadata: {
      fullDescription: "The Padova is the quickest way to add a touch of the Modulas aesthetic to any space. At 55 cm, it works as a footrest for a sofa, a perch for unexpected guests, or a platform for a plant or decorative object. The velvet comes in four jewel tones — each chosen to work as an accent colour without overwhelming the surrounding palette.",
      features: [
        "55 cm compact diameter",
        "480 gsm velvet in 4 jewel tones",
        "High-density foam fill — retains shape",
        "Non-slip felt base",
        "Ships in 7 days",
        "Can be personalised with monogram",
        "Available in sets of 2 at a discount",
      ],
      care: "Spot-clean with velvet foam cleaner. Do not wet the base.",
      warranty: "2-year structural.",
      rating: 4.5, reviewCount: 428,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Padova Velvet Pouf in Emerald", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85", altText: "Padova — room context", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Daybeds & Chaises (3) ──────────────────────────────────────
  {
    sku: "MOD-DAY-001", slug: "bergamo-chaise-longue",
    name: "Bergamo Chaise Longue", categorySlug: "sofas", subcategorySlug: "daybeds-chaises",
    brand: "Atelier Series", price: 285000, compareAtPrice: 335000, currency: "INR",
    material: "Boucle Fabric", finishOptions: ["Warm White", "Stone", "Blush", "Slate"],
    dimensions: { width: 178, height: 78, depth: 85, unit: "cm" }, weightKg: 58,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 21,
    seoTitle: "Bergamo Boucle Chaise Longue — Atelier Series Modulas",
    seoDescription: "Boucle chaise longue in 4 colourways. 178 cm long. Left or right facing. Kiln-dried frame, feather-wrapped cushions.",
    tags: ["sale", "subcategory:daybeds-chaises"],
    description: "A chaise that invites the afternoon in. The Bergamo's 178 cm length accommodates even the tallest frames in complete horizontal comfort.",
    metadata: {
      fullDescription: "The Bergamo Chaise Longue brings the Continental tradition of afternoon repose into the contemporary home. Its 178 cm reclining surface is upholstered in a single continuous piece of boucle — no visible seams along the length — with a bolster cushion at the raised end and a scatter cushion included. The frame is kiln-dried beech with a solid oak leg in a turned finish.",
      features: [
        "178 cm length — accommodates any height",
        "Single-piece boucle seat upholstery — no visible seams",
        "Feather-wrapped bolster cushion included",
        "Left or right facing — specify at checkout",
        "Kiln-dried beech frame",
        "Turned solid oak legs",
        "Reversible scatter cushion included",
      ],
      care: "Vacuum with soft brush. Spot-clean boucle with foam cleaner. Feather bolster — plump daily.",
      warranty: "20-year frame. 3-year fabric.",
      rating: 4.8, reviewCount: 67,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Bergamo Chaise Longue in Warm White Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Bergamo — length and cushion detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DAY-002", slug: "pisa-velvet-daybed",
    name: "Pisa Velvet Daybed", categorySlug: "sofas", subcategorySlug: "daybeds-chaises",
    brand: "Modulas Originals", price: 345000, currency: "INR",
    material: "Velvet", finishOptions: ["Sage Green", "Dusty Rose", "Ink Blue", "Graphite"],
    dimensions: { width: 195, height: 72, depth: 90, unit: "cm" }, weightKg: 72,
    isConfigurable: false, isFeatured: true, stockQty: 5, leadTimeDays: 28,
    seoTitle: "Pisa Velvet Daybed — Modulas Luxury Furniture India",
    seoDescription: "Full-length velvet daybed, 195 cm. Bolster arms, sprung mattress base. 4 rich colourways. For master bedrooms, sunrooms, and studies.",
    tags: ["new", "subcategory:daybeds-chaises"],
    description: "The Pisa blurs the line between sofa and bed. A 195 cm velvet surface on a sprung mattress base, with a bolster arm at each end.",
    metadata: {
      fullDescription: "The Pisa Daybed is designed for spaces that deserve more than a sofa but don't need another bedroom. Its 195 × 90 cm surface provides a genuine sleeping space, and the sprung mattress base — rather than the foam-over-board construction common in daybeds — means it can be slept on regularly without losing support. The bolster arms are removable for full-length lounging.",
      features: [
        "195 × 90 cm — genuine sleeping surface",
        "Sprung mattress base — suitable for regular sleep",
        "Removable bolster arms — full-length lounging mode",
        "480 gsm velvet — 4 colourways",
        "Solid walnut frame — raised platform legs",
        "Scatter cushions and bolsters included",
        "Matching bedside table available",
      ],
      care: "Brush velvet with soft-bristle brush. Spot-clean with velvet foam cleaner. Air bolsters regularly.",
      warranty: "15-year frame and spring. 3-year velvet.",
      rating: 4.7, reviewCount: 48,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85", altText: "Pisa Daybed in Sage Green Velvet", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Pisa — bolster and surface detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DAY-003", slug: "siena-linen-chaise",
    name: "Siena Linen Chaise", categorySlug: "sofas", subcategorySlug: "daybeds-chaises",
    brand: "Atelier Series", price: 225000, currency: "INR",
    material: "Belgian Linen", finishOptions: ["Natural", "Warm Stone", "Soft Grey", "Blush"],
    dimensions: { width: 162, height: 74, depth: 82, unit: "cm" }, weightKg: 50,
    isConfigurable: true, isFeatured: false, stockQty: 9, leadTimeDays: 21,
    seoTitle: "Siena Belgian Linen Chaise Lounge — Atelier Series Modulas",
    seoDescription: "Belgian linen chaise lounge in 4 natural colourways. 162 cm. Solid oak frame. Perfect for sunlit corners and reading nooks.",
    tags: ["subcategory:daybeds-chaises"],
    description: "The Siena Linen Chaise works with light rather than against it — natural linen that shifts colour through the day as sunlight moves across the room.",
    metadata: {
      fullDescription: "Belgian linen on a solid oak frame — the Siena Chaise relies on material quality rather than silhouette drama. Its natural linen picks up warmth in morning light and cools in evening shade, making it particularly beautiful in sun-lit rooms. The frame is entirely solid oak — legs, rail, and arm — left in a natural oil finish that deepens with age.",
      features: [
        "162 cm length — proportional for most rooms",
        "Belgian linen — responds beautifully to natural light",
        "Solid oak frame — fully visible, naturally oiled",
        "High-resilience foam cushion",
        "Scatter cushion and bolster included",
        "Left or right arm configuration",
        "Matching reading chair available",
      ],
      care: "Dry-clean cushion cover. Spot-clean frame linen with damp cloth. Oil oak frame annually.",
      warranty: "15-year frame. 2-year fabric.",
      rating: 4.6, reviewCount: 59,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85", altText: "Siena Linen Chaise in Natural", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=900&q=85", altText: "Siena — oak frame detail", isPrimary: false, sortOrder: 1 },
    ],
  },
];
