import { SeedProduct } from './catalog.seed';

export const STUDY_OFFICE: SeedProduct[] = [
  // ── Writing Desks (6) ────────────────────────────────────────────────────
  {
    sku: 'STU-WD-001',
    slug: 'maestro-writing-desk',
    name: 'Maestro Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 148000,
    compareAtPrice: 175000,
    currency: 'INR',
    material: 'Solid American Walnut with brass hardware',
    finishOptions: ['Natural Walnut', 'Ebonised Walnut', 'Smoked Oak'],
    dimensions: { width: 150, height: 76, depth: 70, unit: 'cm' },
    weightKg: 52,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 8,
    leadTimeDays: 21,
    seoTitle: 'Maestro Writing Desk – Solid Walnut | Modulas',
    seoDescription: 'The Maestro Writing Desk in solid American walnut pairs a generous work surface with subtle brass hardware. Crafted for those who demand beauty from their workspace.',
    tags: ['writing-desk', 'walnut', 'brass', 'study', 'subcategory:writing-desks'],
    description: 'A masterwork of functional elegance — the Maestro Writing Desk pairs a generously proportioned solid walnut top with slender tapered legs and delicate brass drawer pulls.',
    metadata: {
      fullDescription: 'The Maestro Writing Desk is conceived for the discerning professional who refuses to compromise on beauty. Hewn from sustainably sourced American walnut, each slab is hand-selected for grain continuity before being mortise-and-tenon joined to its solid walnut base. Three dovetail-jointed drawers glide on soft-close runners, their handles cast in solid brass and hand-polished to a warm satin lustre. The work surface receives a hand-rubbed oil finish that honours the timber\'s natural warmth while providing a resilient, low-sheen patina that improves with age. A discreet cable management channel runs along the back apron, keeping the surface uncluttered.',
      features: [
        'Solid American walnut construction throughout',
        'Three dovetail-jointed drawers with soft-close runners',
        'Hand-cast solid brass drawer pulls, satin-polished',
        'Integrated rear cable management channel',
        'Hand-rubbed natural oil finish',
        'Adjustable levelling feet',
      ],
      care: 'Wipe with a slightly damp cloth. Avoid prolonged exposure to direct sunlight. Re-oil annually with food-grade tung oil to maintain the finish.',
      warranty: '5 years structural, 2 years finish',
      rating: 4.9,
      reviewCount: 64,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Maestro Writing Desk front view', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900', alt: 'Maestro Writing Desk detail – brass pulls' },
    ],
  },
  {
    sku: 'STU-WD-002',
    slug: 'scholar-writing-desk',
    name: 'Scholar Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 98000,
    compareAtPrice: 115000,
    currency: 'INR',
    material: 'Solid oak with matte black steel frame',
    finishOptions: ['Natural Oak', 'Whitened Oak'],
    dimensions: { width: 140, height: 75, depth: 65, unit: 'cm' },
    weightKg: 44,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 14,
    leadTimeDays: 14,
    seoTitle: 'Scholar Writing Desk – Oak & Steel | Modulas',
    seoDescription: 'The Scholar Writing Desk combines solid oak warmth with matte black steel structure — a Scandinavian-inspired piece built for focused, inspired work.',
    tags: ['writing-desk', 'oak', 'steel', 'minimalist', 'subcategory:writing-desks'],
    description: 'Scandinavian restraint meets solid craftsmanship. The Scholar Writing Desk pairs a thick oak plank top with a precisely welded matte black steel frame.',
    metadata: {
      fullDescription: 'The Scholar Writing Desk draws from the Nordic tradition of honest, enduring furniture. The 40 mm solid oak top — chosen for its pronounced grain and natural creamy warmth — is supported by a hand-welded matte black steel frame with hairline-brushed cross bracing. A single solid oak shelf sits beneath the work surface, providing open storage for reference books or accessories. No unnecessary adornment: every element earns its place.',
      features: [
        '40 mm solid oak work surface',
        'Hand-welded matte black steel frame',
        'Integrated lower oak shelf',
        'Non-marking floor glides',
        'Partially assembled, toolkit included',
      ],
      care: 'Dust regularly with a dry cloth. Remove spills immediately. Apply beeswax paste annually to the oak surface.',
      warranty: '3 years structural',
      rating: 4.7,
      reviewCount: 42,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900', alt: 'Scholar Writing Desk in natural oak', isPrimary: true },
    ],
  },
  {
    sku: 'STU-WD-003',
    slug: 'luminary-writing-desk',
    name: 'Luminary Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 175000,
    compareAtPrice: 210000,
    currency: 'INR',
    material: 'Smoked oak with hidden integrated LED lighting',
    finishOptions: ['Smoked Oak', 'Black Oak'],
    dimensions: { width: 160, height: 76, depth: 72, unit: 'cm' },
    weightKg: 58,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 5,
    leadTimeDays: 28,
    seoTitle: 'Luminary Writing Desk with Integrated LED Lighting | Modulas',
    seoDescription: 'A writing desk that illuminates your thinking. The Luminary features smoked oak construction with a concealed warm-white LED strip along the rear apron.',
    tags: ['writing-desk', 'smoked-oak', 'led-lighting', 'premium', 'subcategory:writing-desks'],
    description: 'The Luminary is a writing desk that illuminates your work — a warm-white LED channel is invisibly integrated into the rear apron, casting soft, shadow-free light across the work surface.',
    metadata: {
      fullDescription: 'Commissioned for those who work into the evening hours, the Luminary Writing Desk resolves the tension between ambient and task lighting. A 3000K warm-white LED strip, recessed into a routed channel in the rear apron, projects diffused uplight that bounces off the wall behind the desk. The structure is solid smoked oak — each plank kiln-dried and book-matched for a continuous, dramatic grain — joined with through-wedged tenons and finished with hard-wax oil. A single discreet power socket and USB-A/C hub is recessed into the right side of the apron.',
      features: [
        'Integrated 3000K warm-white LED rear apron lighting',
        'Recessed power socket with USB-A and USB-C ports',
        'Solid smoked oak, book-matched planks',
        'Through-wedged tenon joinery',
        'Hard-wax oil finish',
        'Touch-dimmer control on apron edge',
      ],
      care: 'Use a slightly damp cloth for surface cleaning. LED strip rated 50,000 hours; contact Modulas service for replacement.',
      warranty: '5 years structural, 2 years electronics',
      rating: 4.9,
      reviewCount: 31,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Luminary Writing Desk with ambient lighting', isPrimary: true },
    ],
  },
  {
    sku: 'STU-WD-004',
    slug: 'vista-writing-desk',
    name: 'Vista Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 82000,
    currency: 'INR',
    material: 'Solid ash with powder-coated steel legs',
    finishOptions: ['Natural Ash', 'Bleached Ash'],
    dimensions: { width: 130, height: 74, depth: 60, unit: 'cm' },
    weightKg: 36,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 20,
    leadTimeDays: 14,
    seoTitle: 'Vista Writing Desk – Solid Ash | Modulas',
    seoDescription: 'Clean lines and solid ash construction make the Vista Writing Desk a versatile luxury essential for any home study.',
    tags: ['writing-desk', 'ash', 'minimalist', 'subcategory:writing-desks'],
    description: 'The Vista is an essay in restraint — a solid ash top on four slender, slightly tapered legs in powder-coated steel. Simple, beautiful, built to last.',
    metadata: {
      fullDescription: 'The Vista Writing Desk is Modulas\'s most accessible study piece without sacrificing material integrity. The 35 mm solid ash top presents a fine, consistent grain; the bleached option lifts this to a near-white Scandinavian tone. Four slightly flared solid-steel legs in satin-matte powder coat provide structural rigidity with visual lightness. A rear-routed cable groove keeps power leads tidy. Arrives flatpack with all tools included.',
      features: [
        '35 mm solid ash work surface',
        'Satin-matte powder-coated steel legs',
        'Rear cable management groove',
        'Easy 20-minute flatpack assembly',
      ],
      care: 'Wipe clean with a damp cloth. Apply natural wood oil every 12–18 months.',
      warranty: '3 years structural',
      rating: 4.6,
      reviewCount: 78,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900', alt: 'Vista Writing Desk in natural ash', isPrimary: true },
    ],
  },
  {
    sku: 'STU-WD-005',
    slug: 'lexicon-writing-desk',
    name: 'Lexicon Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 125000,
    compareAtPrice: 145000,
    currency: 'INR',
    material: 'Solid walnut with full-grain leather writing pad insert',
    finishOptions: ['Dark Walnut', 'Mid Walnut'],
    dimensions: { width: 145, height: 76, depth: 68, unit: 'cm' },
    weightKg: 48,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 10,
    leadTimeDays: 21,
    seoTitle: 'Lexicon Writing Desk with Leather Pad – Walnut | Modulas',
    seoDescription: 'The Lexicon Writing Desk features a full-grain leather writing pad inset into a solid walnut surface — the desk of serious writers and professionals.',
    tags: ['writing-desk', 'walnut', 'leather', 'executive-style', 'subcategory:writing-desks'],
    description: 'A calling card for the serious writer. The Lexicon\'s solid walnut surface is inset with a generous full-grain leather writing pad — available in tan cognac, charcoal, or hunter green.',
    metadata: {
      fullDescription: 'The Lexicon Writing Desk draws from the heritage of Victorian writing tables, reinterpreted through a modern luxury lens. A substantial solid walnut top is routed to accept a full-grain leather inset pad — stitched at the border and available in three colourways. Two slim drawers feature antique brass ring pulls. The result is a desk that commands respect while inviting long, productive hours.',
      features: [
        'Solid walnut construction with leather inset writing pad',
        'Choice of three leather colours (tan, charcoal, hunter green)',
        'Two slim drawers with antique brass ring pulls',
        'Solid corner-block joinery for structural rigidity',
        'Hand-rubbed oil finish on walnut',
      ],
      care: 'Leather pad: condition every 6 months with colourless leather cream. Walnut: re-oil annually.',
      warranty: '5 years structural, 2 years leather',
      rating: 4.8,
      reviewCount: 39,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Lexicon Writing Desk with leather pad', isPrimary: true },
    ],
  },
  {
    sku: 'STU-WD-006',
    slug: 'studio-compact-writing-desk',
    name: 'Studio Compact Writing Desk',
    categorySlug: 'study',
    subcategorySlug: 'writing-desks',
    brand: 'Modulas Atelier',
    price: 58000,
    currency: 'INR',
    material: 'Solid birch plywood with lacquer finish',
    finishOptions: ['White Lacquer', 'Soft Black Lacquer', 'Natural Birch'],
    dimensions: { width: 100, height: 75, depth: 55, unit: 'cm' },
    weightKg: 26,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 35,
    leadTimeDays: 10,
    seoTitle: 'Studio Compact Writing Desk – Space-Saving | Modulas',
    seoDescription: 'The Studio Compact Desk brings Modulas craft to smaller spaces — solid birch with a lacquered finish in white, black, or natural.',
    tags: ['writing-desk', 'compact', 'birch', 'small-space', 'subcategory:writing-desks'],
    description: 'Proof that quality needs no square footage. The Studio Compact Desk delivers solid birch construction and a smooth lacquer finish in a thoughtfully scaled footprint.',
    metadata: {
      fullDescription: 'Designed for the apartment studio, guest bedroom, or alcove study, the Studio Compact Writing Desk refuses to sacrifice material quality for size. Solid birch plywood panels — not MDF — are CNC-cut before receiving multiple coats of water-based lacquer, hand-sanded between each coat. Two shallow cubbies provide open storage without adding visual bulk. Wall-fixing anchors are included as standard.',
      features: [
        'Solid birch plywood throughout — no MDF',
        'Multiple coats of water-based lacquer, hand-sanded between coats',
        'Two open cubbies for stationery storage',
        'Wall-fixing anchors included',
        'Lightweight and easy to reposition',
      ],
      care: 'Wipe with a damp microfibre cloth. Do not use abrasive cleaners on lacquered surface.',
      warranty: '2 years structural',
      rating: 4.5,
      reviewCount: 112,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900', alt: 'Studio Compact Writing Desk in white lacquer', isPrimary: true },
    ],
  },

  // ── Executive Desks (4) ──────────────────────────────────────────────────
  {
    sku: 'STU-ED-001',
    slug: 'penthouse-executive-desk',
    name: 'Penthouse Executive Desk',
    categorySlug: 'study',
    subcategorySlug: 'executive-desks',
    brand: 'Modulas Atelier',
    price: 385000,
    compareAtPrice: 440000,
    currency: 'INR',
    material: 'Book-matched black walnut with polished stainless steel',
    finishOptions: ['Black Walnut / Brushed Steel', 'Dark Walnut / Polished Brass'],
    dimensions: { width: 200, height: 76, depth: 90, unit: 'cm' },
    weightKg: 110,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 3,
    leadTimeDays: 42,
    seoTitle: 'Penthouse Executive Desk – Black Walnut & Steel | Modulas',
    seoDescription: 'A statement executive desk for the most discerning offices. Book-matched black walnut, polished steel, and built-in power hub — crafted to impress.',
    tags: ['executive-desk', 'black-walnut', 'steel', 'luxury', 'office', 'subcategory:executive-desks'],
    description: 'The Penthouse Executive Desk is the centrepiece of an extraordinary office. Two book-matched black walnut slabs form a dramatic, mirrored grain across a two-metre work surface.',
    metadata: {
      fullDescription: 'The Penthouse Executive Desk is conceived as both functional command centre and furniture art. Two quartersawn black walnut planks are book-matched — their grain flowing outward in bilateral symmetry — finished with matte lacquer that heightens depth without sheen. The frame is fabricated from 40 mm polished stainless steel tube, welded by hand and mirror-polished at the joints. A flush-mounted power module provides two power sockets, two USB-A and two USB-C ports. Two deep pedestal drawers feature individual key locks.',
      features: [
        'Book-matched black walnut two-metre top',
        'Hand-welded polished stainless steel frame',
        'Flush-mounted power module (2× power, 2× USB-A, 2× USB-C)',
        'Two key-locked pedestal drawers',
        'Matte lacquer finish on walnut',
        'Bespoke sizing available on request',
      ],
      care: 'Soft dry cloth on stainless steel prevents fingerprints. Apply specialist steel polish quarterly. Walnut: dust regularly, re-lacquer every 5 years.',
      warranty: '7 years structural, 2 years electronics',
      rating: 5.0,
      reviewCount: 18,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Penthouse Executive Desk front view', isPrimary: true },
    ],
  },
  {
    sku: 'STU-ED-002',
    slug: 'command-executive-desk',
    name: 'Command Executive Desk',
    categorySlug: 'study',
    subcategorySlug: 'executive-desks',
    brand: 'Modulas Atelier',
    price: 245000,
    compareAtPrice: 290000,
    currency: 'INR',
    material: 'Solid teak with oil finish and integrated cable management',
    finishOptions: ['Natural Teak', 'Ebonised Teak'],
    dimensions: { width: 180, height: 76, depth: 85, unit: 'cm' },
    weightKg: 95,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 6,
    leadTimeDays: 28,
    seoTitle: 'Command Executive Desk – Solid Teak | Modulas',
    seoDescription: 'The Command Executive Desk in solid teak: a powerful presence in any corner office or home study, with integrated cable management and deep pedestal storage.',
    tags: ['executive-desk', 'teak', 'cable-management', 'office', 'subcategory:executive-desks'],
    description: 'The Command Executive Desk asserts authority with solid teak construction, generous dimensions, and intelligent built-in cable management.',
    metadata: {
      fullDescription: 'Solid teak — one of the world\'s most durable and naturally oil-rich hardwoods — forms the backbone of the Command Executive Desk. The three-plank glued top provides a generous 180 cm work surface. Two full-height pedestals flank the knee well: the left houses three progressively deeper drawers; the right contains a filing-depth drawer plus an open cupboard. A routed cable channel runs beneath the apron, emerging through two grommet ports at the rear corners. Supplied with a leather-padded surface mat as standard.',
      features: [
        'Solid teak three-plank glued top with chamfered edge',
        'Left pedestal: 3 progressively deep drawers',
        'Right pedestal: 1 filing drawer + open cupboard',
        'Rear cable channel with two grommet ports',
        'Included leather surface mat',
        'Oil finish maintaining teak\'s natural moisture resistance',
      ],
      care: 'Apply teak oil every 6–12 months. Avoid placing hot objects directly on the surface.',
      warranty: '5 years structural',
      rating: 4.8,
      reviewCount: 27,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Command Executive Desk in natural teak', isPrimary: true },
    ],
  },
  {
    sku: 'STU-ED-003',
    slug: 'atlas-executive-desk',
    name: 'Atlas Executive Desk',
    categorySlug: 'study',
    subcategorySlug: 'executive-desks',
    brand: 'Modulas Atelier',
    price: 195000,
    currency: 'INR',
    material: 'Ash veneer on solid core with brushed gold legs',
    finishOptions: ['Natural Ash / Brushed Gold', 'Dark Ash / Matte Black'],
    dimensions: { width: 170, height: 75, depth: 80, unit: 'cm' },
    weightKg: 78,
    isConfigurable: false,
    isFeatured: true,
    stockQty: 7,
    leadTimeDays: 21,
    seoTitle: 'Atlas Executive Desk – Ash & Brushed Gold | Modulas',
    seoDescription: 'The Atlas Executive Desk blends a fine ash veneer top with hand-brushed gold frame legs — a bold statement of modern luxury for the professional home office.',
    tags: ['executive-desk', 'ash', 'gold', 'modern', 'subcategory:executive-desks'],
    description: 'Bold yet refined, the Atlas Executive Desk pairs fine ash veneer over a solid core with sculpted brushed-gold steel frame legs — a modern luxury centrepiece.',
    metadata: {
      fullDescription: 'A 30 mm solid-core top is clad with premium quarter-cut ash veneer in two bookmatched panels, sealed with a satin lacquer. Four geometric brushed-gold steel legs — each individually machined and electrolytically brushed — converge at a central steel stretcher. Two full-extension drawers are concealed in the right leg cluster with soft-close dampers and push-to-open mechanism.',
      features: [
        'Quarter-cut ash veneer over solid core',
        'Individually machined brushed-gold steel legs',
        'Two push-to-open soft-close drawers in right cluster',
        'Central steel stretcher for rigidity',
        'Satin lacquer sealed surface',
      ],
      care: 'Wipe veneer surface with a slightly damp cloth. Polish steel legs with a specialist metal cleaner monthly.',
      warranty: '5 years structural',
      rating: 4.7,
      reviewCount: 33,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Atlas Executive Desk – ash and gold', isPrimary: true },
    ],
  },
  {
    sku: 'STU-ED-004',
    slug: 'director-double-pedestal-desk',
    name: 'Director Double-Pedestal Desk',
    categorySlug: 'study',
    subcategorySlug: 'executive-desks',
    brand: 'Modulas Atelier',
    price: 310000,
    compareAtPrice: 360000,
    currency: 'INR',
    material: 'Solid mahogany with dovetail-jointed drawers and leather surface',
    finishOptions: ['Antique Mahogany', 'Dark Mahogany'],
    dimensions: { width: 190, height: 78, depth: 90, unit: 'cm' },
    weightKg: 118,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 4,
    leadTimeDays: 35,
    seoTitle: 'Director Double-Pedestal Desk – Solid Mahogany | Modulas',
    seoDescription: 'A classical double-pedestal executive desk in solid mahogany with ten dovetail-jointed drawers and a full-grain leather surface. Heirloom quality from Modulas.',
    tags: ['executive-desk', 'mahogany', 'double-pedestal', 'classical', 'subcategory:executive-desks'],
    description: 'A tribute to the great counting-house desks of the 19th century — reimagined with heirloom-grade solid mahogany and a full-grain oxblood leather writing surface.',
    metadata: {
      fullDescription: 'Carved from solid African mahogany, the Director Double-Pedestal Desk is an investment in legacy furniture. Two three-drawer pedestals and one full-width central frieze drawer provide ten storage compartments in total; every drawer is hand-cut with traditional English dovetail joinery and fitted with a soft-close metal runner. The work surface is inset with a full-grain oxblood leather writing pad. Brass drop-ring handles, key locks on the pedestals, and a reeded edge profile complete the classical vocabulary.',
      features: [
        'Solid African mahogany throughout',
        'Ten drawers — all hand-cut English dovetail joinery',
        'Full-grain oxblood leather inset writing pad',
        'Solid brass drop-ring handles',
        'Key-locked pedestal drawers',
        'Reeded edge profile on top',
      ],
      care: 'Polish mahogany with beeswax twice yearly. Condition leather pad every 6 months. Lubricate key locks annually.',
      warranty: '10 years structural, 3 years leather',
      rating: 4.9,
      reviewCount: 14,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Director Double-Pedestal Desk in antique mahogany', isPrimary: true },
    ],
  },

  // ── Standing Desks (3) ───────────────────────────────────────────────────
  {
    sku: 'STU-SD-001',
    slug: 'altitude-electric-standing-desk',
    name: 'Altitude Electric Standing Desk',
    categorySlug: 'study',
    subcategorySlug: 'standing-desks',
    brand: 'Modulas Atelier',
    price: 185000,
    compareAtPrice: 215000,
    currency: 'INR',
    material: 'Solid oak top with whisper-quiet dual-motor frame',
    finishOptions: ['Natural Oak', 'Black Oak', 'Walnut'],
    dimensions: { width: 160, height: 62, depth: 80, unit: 'cm' },
    weightKg: 68,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 12,
    leadTimeDays: 21,
    seoTitle: 'Altitude Electric Standing Desk – Solid Oak | Modulas',
    seoDescription: 'Modulas\'s premium electric height-adjustable desk: a 40 mm solid oak top on a whisper-quiet dual-motor frame with three memory presets, anti-collision, and a 10-year frame warranty.',
    tags: ['standing-desk', 'electric', 'height-adjustable', 'oak', 'ergonomic', 'subcategory:standing-desks'],
    description: 'The Altitude Electric Standing Desk combines a 40 mm solid oak surface with a whisper-quiet dual-motor frame — adjusting between 62 and 128 cm in under 20 seconds.',
    metadata: {
      fullDescription: 'A 40 mm solid oak top rests on a twin-column aluminium frame driven by two German-engineered motors delivering 200 N of lifting force per column. Adjustment range is 62–128 cm, with three programmable memory presets on the integrated touch panel. Anti-collision detection stops movement automatically if resistance is encountered. A rear cable tray in brushed aluminium keeps leads organised. Bluetooth app control allows preset management from your phone.',
      features: [
        '40 mm solid oak top in three finishes',
        'Whisper-quiet dual-motor frame (62–128 cm range)',
        'Three programmable memory height presets',
        'Anti-collision auto-stop technology',
        'Integrated Bluetooth app control',
        'Brushed aluminium rear cable tray',
        'Load capacity: 100 kg',
      ],
      care: 'Apply beeswax to oak top every 6 months. Motor unit is maintenance-free; wipe frame with a dry cloth.',
      warranty: '10 years frame, 5 years motor, 3 years electronics',
      rating: 4.9,
      reviewCount: 86,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Altitude Electric Standing Desk at standing height', isPrimary: true },
    ],
  },
  {
    sku: 'STU-SD-002',
    slug: 'apex-pro-standing-desk',
    name: 'Apex Pro Standing Desk',
    categorySlug: 'study',
    subcategorySlug: 'standing-desks',
    brand: 'Modulas Atelier',
    price: 145000,
    currency: 'INR',
    material: 'Strand-woven bamboo composite top with single-motor frame',
    finishOptions: ['Natural Bamboo', 'Carbonised Bamboo'],
    dimensions: { width: 150, height: 71, depth: 75, unit: 'cm' },
    weightKg: 54,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 18,
    leadTimeDays: 14,
    seoTitle: 'Apex Pro Standing Desk – Bamboo | Modulas',
    seoDescription: 'A sustainable standing desk: the Apex Pro features a hardwearing bamboo composite top on a single-motor height-adjustable frame, naturally beautiful and eco-conscious.',
    tags: ['standing-desk', 'bamboo', 'sustainable', 'height-adjustable', 'subcategory:standing-desks'],
    description: 'The Apex Pro pairs an eco-conscious strand-woven bamboo composite top with a single-motor frame — height-adjustable from 71 to 120 cm, built for the sustainability-minded professional.',
    metadata: {
      fullDescription: 'Strand-woven bamboo composite is harder than most hardwoods — and regenerates in five years. The 35 mm top is sealed with a UV-cured water-based lacquer. The single-motor base adjusts smoothly from 71 to 120 cm with a simple up/down rocker and two memory presets. Load capacity is 80 kg. A cable management spine clips to the frame uprights.',
      features: [
        '35 mm strand-woven bamboo composite top',
        'Single-motor frame, 71–120 cm range',
        'Two memory height presets',
        'Clip-on cable management spine',
        'UV-cured lacquer finish for durability',
        'Load capacity: 80 kg',
      ],
      care: 'Wipe with a damp cloth. Do not use strong chemical cleaners on bamboo surface.',
      warranty: '5 years frame, 3 years motor',
      rating: 4.7,
      reviewCount: 54,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Apex Pro Standing Desk in natural bamboo', isPrimary: true },
    ],
  },
  {
    sku: 'STU-SD-003',
    slug: 'elevate-height-adjustable-desk',
    name: 'Elevate Height-Adjustable Desk',
    categorySlug: 'study',
    subcategorySlug: 'standing-desks',
    brand: 'Modulas Atelier',
    price: 115000,
    compareAtPrice: 135000,
    currency: 'INR',
    material: 'MDF with premium walnut veneer on pneumatic gas-lift frame',
    finishOptions: ['Walnut Veneer', 'White Lacquer'],
    dimensions: { width: 140, height: 73, depth: 70, unit: 'cm' },
    weightKg: 48,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 22,
    leadTimeDays: 14,
    seoTitle: 'Elevate Height-Adjustable Desk – Walnut Veneer | Modulas',
    seoDescription: 'The Elevate Height-Adjustable Desk offers premium walnut veneer aesthetics and pneumatic gas-lift adjustment — effortless ergonomics at an accessible luxury price.',
    tags: ['standing-desk', 'gas-lift', 'height-adjustable', 'walnut-veneer', 'subcategory:standing-desks'],
    description: 'Pneumatic gas-lift adjustment and a premium walnut veneer surface make the Elevate the most accessible height-adjustable desk in the Modulas collection.',
    metadata: {
      fullDescription: 'The Elevate Height-Adjustable Desk delivers ergonomic flexibility without electronic complexity. A pneumatic gas-lift column adjusts the desk between 73 and 119 cm with a one-handed lever release — smooth, silent, and requiring no power supply. The 25 mm MDF core top is clad with premium book-matched walnut veneer and sealed with a satin lacquer. A lateral cable channel is integrated into the underside apron. The gas-cylinder frame is rated for 500,000 full-height adjustment cycles.',
      features: [
        'Pneumatic gas-lift frame, 73–119 cm, no power required',
        'Premium book-matched walnut veneer over MDF',
        'Integrated underside cable channel',
        'Gas-cylinder rated 500,000 adjustment cycles',
        'Satin lacquer surface seal',
      ],
      care: 'Wipe surface clean with a damp cloth. Gas-lift mechanism is sealed and maintenance-free.',
      warranty: '5 years frame, 3 years gas-lift mechanism',
      rating: 4.6,
      reviewCount: 67,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900', alt: 'Elevate Height-Adjustable Desk in walnut veneer', isPrimary: true },
    ],
  },

  // ── Office Chairs (5) ────────────────────────────────────────────────────
  {
    sku: 'STU-OC-001',
    slug: 'director-leather-office-chair',
    name: 'Director Leather Office Chair',
    categorySlug: 'study',
    subcategorySlug: 'office-chairs',
    brand: 'Modulas Atelier',
    price: 95000,
    compareAtPrice: 115000,
    currency: 'INR',
    material: 'Full-grain Italian leather with polished aluminium base',
    finishOptions: ['Cognac Leather', 'Charcoal Leather', 'Black Leather'],
    dimensions: { width: 68, height: 120, depth: 70, unit: 'cm' },
    weightKg: 24,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 15,
    leadTimeDays: 14,
    seoTitle: 'Director Leather Office Chair – Full Grain Italian Leather | Modulas',
    seoDescription: 'The Director Leather Office Chair wraps full-grain Italian leather over high-density foam with a five-star polished aluminium base. Ergonomic luxury for long work sessions.',
    tags: ['office-chair', 'leather', 'ergonomic', 'executive', 'subcategory:office-chairs'],
    description: 'The Director Leather Office Chair commands attention and sustains comfort through the longest days — full-grain Italian leather over memory foam, on a five-star polished aluminium base.',
    metadata: {
      fullDescription: 'Full-grain Italian leather — sourced from Tuscan tanneries and left with its natural grain intact — wraps a high-density cold-cure foam seat and back that maintain their shape over years of daily use. The sculpted lumbar zone provides anatomical support. Seat height, tilt tension, and armrest height adjust through intuitive mechanisms. A five-star polished cast-aluminium base on 60 mm dual-wheel castors provides stability on both carpet and hard floor.',
      features: [
        'Full-grain Italian leather, naturally grained',
        'High-density cold-cure foam seat and back',
        'Anatomical sculpted lumbar support',
        'Adjustable seat height, tilt tension, and armrest height',
        'Five-star polished cast-aluminium base',
        '60 mm dual-wheel castors for carpet and hard floor',
        'Maximum weight capacity: 130 kg',
      ],
      care: 'Condition leather every 3–4 months with a colourless leather cream. Castor wheels: remove hair and debris monthly.',
      warranty: '5 years structural, 3 years leather',
      rating: 4.9,
      reviewCount: 57,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=900', alt: 'Director Leather Office Chair in cognac', isPrimary: true },
    ],
  },
  {
    sku: 'STU-OC-002',
    slug: 'prestige-task-chair',
    name: 'Prestige Task Chair',
    categorySlug: 'study',
    subcategorySlug: 'office-chairs',
    brand: 'Modulas Atelier',
    price: 68000,
    currency: 'INR',
    material: 'Premium boucle fabric with walnut veneer armrests',
    finishOptions: ['Ivory Boucle', 'Charcoal Boucle', 'Sage Boucle'],
    dimensions: { width: 64, height: 110, depth: 66, unit: 'cm' },
    weightKg: 18,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 20,
    leadTimeDays: 14,
    seoTitle: 'Prestige Task Chair – Boucle & Walnut | Modulas',
    seoDescription: 'A refined task chair combining plush boucle upholstery with sculptural walnut veneer armrests. Ergonomic adjustment beneath a luxurious exterior.',
    tags: ['office-chair', 'boucle', 'walnut', 'task-chair', 'subcategory:office-chairs'],
    description: 'The Prestige Task Chair wraps ergonomic function in a luxurious boucle exterior with sculpted walnut veneer armrests — the design-forward office chair that belongs in a living room.',
    metadata: {
      fullDescription: 'Plush boucle upholstery — available in ivory, charcoal, and sage — covers a responsively sprung seat and a gently contoured back panel. Solid walnut veneer armrests add warmth that no plastic alternative can match. Five-point matte black nylon base with silent-roll castors. Seat height adjusts via pneumatic cylinder; recline angle locks at four positions.',
      features: [
        'Premium boucle upholstery in three colourways',
        'Solid walnut veneer sculpted armrests',
        'Responsively sprung seat with contoured back',
        'Pneumatic seat height adjustment',
        'Four-position recline lock',
        'Matte black nylon five-point base with silent-roll castors',
      ],
      care: 'Brush boucle fabric gently to maintain texture. Spot-clean with a damp cloth and mild soap.',
      warranty: '3 years structural, 2 years upholstery',
      rating: 4.7,
      reviewCount: 43,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=900', alt: 'Prestige Task Chair in ivory boucle', isPrimary: true },
    ],
  },
  {
    sku: 'STU-OC-003',
    slug: 'comfort-mesh-office-chair',
    name: 'Comfort Mesh Office Chair',
    categorySlug: 'study',
    subcategorySlug: 'office-chairs',
    brand: 'Modulas Atelier',
    price: 48000,
    compareAtPrice: 58000,
    currency: 'INR',
    material: '3D knit breathable mesh with anodised aluminium frame',
    finishOptions: ['Charcoal Mesh / Silver Frame', 'Black Mesh / Matte Black Frame'],
    dimensions: { width: 62, height: 118, depth: 64, unit: 'cm' },
    weightKg: 16,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 30,
    leadTimeDays: 10,
    seoTitle: 'Comfort Mesh Office Chair – Breathable Ergonomic | Modulas',
    seoDescription: 'The Comfort Mesh Office Chair uses a 3D knit breathable mesh back and seat on an anodised aluminium frame for all-day ergonomic support in India\'s warm climate.',
    tags: ['office-chair', 'mesh', 'ergonomic', 'breathable', 'subcategory:office-chairs'],
    description: 'Designed for India\'s warm working conditions, the Comfort Mesh Office Chair uses 3D knit breathable mesh that circulates air across the seat and back throughout the working day.',
    metadata: {
      fullDescription: 'Its 3D knit mesh — woven in a hexagonal tension pattern — provides consistent pressure distribution and excellent air permeability, keeping the user cool even during extended sessions. The anodised aluminium frame and arms project quality well above the chair\'s category. Six-way adjustability: seat height, seat depth, lumbar height, armrest height, armrest pivot, and recline tension. A synchronised tilt mechanism allows independent back and seat movement.',
      features: [
        '3D knit hexagonal tension mesh — seat and back',
        'Anodised aluminium frame and arm brackets',
        'Six-way adjustment including seat depth and lumbar height',
        'Synchronised tilt mechanism',
        'Moulded foam seat pad beneath mesh',
        'Anti-castor brake on all five wheels',
      ],
      care: 'Wipe mesh with a damp cloth. Vacuum periodically with a brush attachment to remove dust from mesh cells.',
      warranty: '5 years structural, 3 years mesh',
      rating: 4.6,
      reviewCount: 98,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=900', alt: 'Comfort Mesh Office Chair – charcoal', isPrimary: true },
    ],
  },
  {
    sku: 'STU-OC-004',
    slug: 'oxford-leather-office-chair',
    name: 'Oxford Leather Office Chair',
    categorySlug: 'study',
    subcategorySlug: 'office-chairs',
    brand: 'Modulas Atelier',
    price: 72000,
    compareAtPrice: 88000,
    currency: 'INR',
    material: 'Semi-aniline leather with solid oak armrests',
    finishOptions: ['Tobacco Leather', 'Navy Leather'],
    dimensions: { width: 66, height: 116, depth: 68, unit: 'cm' },
    weightKg: 22,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 11,
    leadTimeDays: 14,
    seoTitle: 'Oxford Leather Office Chair – Semi-Aniline & Oak | Modulas',
    seoDescription: 'The Oxford Leather Office Chair marries semi-aniline leather upholstery with solid oak armrests — traditional club-chair sensibility reimagined for the modern executive.',
    tags: ['office-chair', 'leather', 'oak', 'traditional', 'subcategory:office-chairs'],
    description: 'The Oxford Leather Office Chair draws from the British club tradition — semi-aniline leather, button-tufted back, and solid oak armrests create a timeless professional presence.',
    metadata: {
      fullDescription: 'Semi-aniline leather — softened through a light aniline dye that preserves natural grain while adding moderate stain resistance — covers a generously padded button-tufted back. The armrests are carved from solid white oak finished with natural hard-wax oil. A high-back silhouette with a gently curved top rail frames the user\'s shoulders. Pneumatic height adjustment and tilt-lock mechanism are discreetly integrated into a five-star solid brass-capped base.',
      features: [
        'Semi-aniline leather — natural grain, enhanced stain resistance',
        'Button-tufted high back with curved top rail',
        'Carved solid oak armrests, hard-wax oil finish',
        'Pneumatic height adjustment',
        'Tilt-lock mechanism',
        'Five-star base with solid brass foot caps',
      ],
      care: 'Condition with semi-aniline leather cream every 4 months. Avoid prolonged direct sunlight exposure.',
      warranty: '5 years structural, 3 years leather',
      rating: 4.8,
      reviewCount: 29,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=900', alt: 'Oxford Leather Office Chair in tobacco', isPrimary: true },
    ],
  },
  {
    sku: 'STU-OC-005',
    slug: 'ergo-pro-office-chair',
    name: 'Ergo Pro Office Chair',
    categorySlug: 'study',
    subcategorySlug: 'office-chairs',
    brand: 'Modulas Atelier',
    price: 55000,
    currency: 'INR',
    material: 'High-performance woven fabric with 8-way adjustable mechanism',
    finishOptions: ['Slate Blue', 'Charcoal Grey', 'Warm Beige'],
    dimensions: { width: 63, height: 125, depth: 65, unit: 'cm' },
    weightKg: 17,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 25,
    leadTimeDays: 10,
    seoTitle: 'Ergo Pro Office Chair – 8-Way Adjustable | Modulas',
    seoDescription: 'The Ergo Pro Office Chair delivers 8-way ergonomic adjustability — including adjustable headrest, dynamic lumbar, and seat depth — for all-day postural support.',
    tags: ['office-chair', 'ergonomic', 'adjustable', 'headrest', 'lumbar', 'subcategory:office-chairs'],
    description: 'Eight-way ergonomic adjustability — seat height, depth, tilt, 4D armrests, headrest, and dynamic lumbar — makes the Ergo Pro the most adaptable chair in the Modulas collection.',
    metadata: {
      fullDescription: 'Eight independent adjustments cover every contact point: pneumatic seat height, fore-aft seat depth, recline angle and tension, 4D armrests (height, width, pivot, depth), adjustable headrest (height and angle), and a dynamic lumbar pad that slides up or down and increases/decreases in prominence. The high-performance woven fabric is rated for 100,000 rub cycles. Polished aluminium five-point base with 60 mm hard-floor-safe castors.',
      features: [
        'Eight independent ergonomic adjustments',
        '4D adjustable armrests',
        'Height and angle-adjustable headrest',
        'Dynamic lumbar pad — height and depth adjustable',
        'High-performance woven fabric, 100k rub cycle rating',
        'Polished aluminium five-point base',
        'Hard-floor-safe 60 mm castors',
      ],
      care: 'Spot-clean fabric with mild soap and water. Vacuum fabric surfaces monthly. Lubricate recline mechanism annually.',
      warranty: '5 years structural, 3 years mechanism',
      rating: 4.7,
      reviewCount: 71,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=900', alt: 'Ergo Pro Office Chair in slate blue', isPrimary: true },
    ],
  },

  // ── Bookshelves (4) ──────────────────────────────────────────────────────
  {
    sku: 'STU-BS-001',
    slug: 'curator-bookshelf',
    name: 'Curator Bookshelf',
    categorySlug: 'study',
    subcategorySlug: 'bookshelves',
    brand: 'Modulas Atelier',
    price: 125000,
    compareAtPrice: 148000,
    currency: 'INR',
    material: 'Solid walnut with integrated brass rail system',
    finishOptions: ['Natural Walnut', 'Ebonised Walnut'],
    dimensions: { width: 120, height: 220, depth: 35, unit: 'cm' },
    weightKg: 88,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 6,
    leadTimeDays: 28,
    seoTitle: 'Curator Bookshelf – Solid Walnut with Brass Rail | Modulas',
    seoDescription: 'The Curator Bookshelf brings library sophistication to the home — solid walnut shelves on an integrated brass sliding rail system for an effortlessly curated display.',
    tags: ['bookshelf', 'walnut', 'brass', 'library', 'subcategory:bookshelves'],
    description: 'Library ambition, domestic scale. The Curator Bookshelf integrates a solid brass sliding rail system into six solid walnut shelves — a home library fixture of enduring character.',
    metadata: {
      fullDescription: 'Six solid walnut shelves — each 35 mm thick and edge-profiled with a fine chamfer — are spaced at adjustable heights within a solid walnut frame. An integrated wall-mounted brass rail runs across the top, accommodating a rolling ladder (available separately). Each shelf is supported by solid brass peg brackets slotting into a French cleat system hidden within the uprights, allowing infinite height adjustment. A solid walnut drawer at the base provides enclosed storage for periodicals.',
      features: [
        'Six solid walnut shelves, 35 mm thick, adjustable height',
        'Integrated brass top rail for rolling library ladder',
        'Solid brass peg bracket French cleat system',
        'Solid walnut base drawer with dovetail joinery',
        'Wall-fixing template and hardware included',
        'Rolling ladder available as optional accessory',
      ],
      care: 'Dust shelves with a dry cloth. Apply a thin coat of natural oil to exposed walnut surfaces annually.',
      warranty: '5 years structural',
      rating: 4.9,
      reviewCount: 22,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Curator Bookshelf in natural walnut', isPrimary: true },
    ],
  },
  {
    sku: 'STU-BS-002',
    slug: 'library-wall-shelf-system',
    name: 'Library Wall Shelf System',
    categorySlug: 'study',
    subcategorySlug: 'bookshelves',
    brand: 'Modulas Atelier',
    price: 85000,
    currency: 'INR',
    material: 'Solid ash shelves on powder-coated steel uprights',
    finishOptions: ['Natural Ash / Black Steel', 'Whitened Ash / White Steel'],
    dimensions: { width: 180, height: 200, depth: 30, unit: 'cm' },
    weightKg: 65,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 10,
    leadTimeDays: 21,
    seoTitle: 'Library Wall Shelf System – Ash & Steel | Modulas',
    seoDescription: 'A modular wall-mounted shelf system in solid ash and powder-coated steel — configurable, expandable, and architecturally striking.',
    tags: ['bookshelf', 'ash', 'steel', 'modular', 'wall-mounted', 'subcategory:bookshelves'],
    description: 'The Library Wall Shelf System is a modular, wall-mounted solution in solid ash and powder-coated steel — configurable in width and height to suit any study wall.',
    metadata: {
      fullDescription: 'Each solid ash shelf (30 mm, edge-rounded) hooks onto powder-coated steel wall uprights via solid brass hooks. Additional shelves, uprights, and extension modules can be ordered individually. The system mounts to three standard stud positions and accommodates shelves up to 90 kg each. The display wall evolves over time as a collection grows.',
      features: [
        'Modular: expandable by adding shelves and uprights',
        '30 mm solid ash shelves with rounded edge',
        'Powder-coated steel uprights and solid brass shelf hooks',
        'Each shelf rated to 90 kg',
        'Compatible with future extension modules',
        'Comprehensive wall-fixing kit included',
      ],
      care: 'Dust regularly. Re-apply a thin coat of natural oil to ash surfaces every 12–18 months.',
      warranty: '5 years structural',
      rating: 4.7,
      reviewCount: 36,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Library Wall Shelf System in natural ash', isPrimary: true },
    ],
  },
  {
    sku: 'STU-BS-003',
    slug: 'scholar-bookcase',
    name: 'Scholar Bookcase',
    categorySlug: 'study',
    subcategorySlug: 'bookshelves',
    brand: 'Modulas Atelier',
    price: 68000,
    compareAtPrice: 80000,
    currency: 'INR',
    material: 'Solid birch with five adjustable shelves',
    finishOptions: ['Natural Birch', 'White Lacquer', 'Black Lacquer'],
    dimensions: { width: 90, height: 210, depth: 32, unit: 'cm' },
    weightKg: 52,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 18,
    leadTimeDays: 14,
    seoTitle: 'Scholar Bookcase – Solid Birch | Modulas',
    seoDescription: 'Five adjustable solid birch shelves in a refined tall bookcase — the Scholar is a versatile home study staple in natural birch, white, or black lacquer.',
    tags: ['bookshelf', 'birch', 'bookcase', 'adjustable', 'subcategory:bookshelves'],
    description: 'Tall, refined, and unfussy — the Scholar Bookcase houses a lifetime of reading across five adjustable solid birch shelves in a full-height frame.',
    metadata: {
      fullDescription: 'Five adjustable solid birch shelves — each 25 mm thick and drilled at 32 mm pin-hole intervals — sit within a solid birch outer frame. A solid back panel prevents books from falling through and adds structural rigidity. Anti-tip wall fittings are pre-installed. The case ships in two sections for easy staircase access.',
      features: [
        'Five fully adjustable solid birch shelves',
        '25 mm shelves on 32 mm pin-hole drilling system',
        'Solid back panel for rigidity and book retention',
        'Anti-tip wall fittings pre-installed',
        'Ships in two sections for easy access',
      ],
      care: 'Wipe with a damp cloth. Natural birch oil: re-oil every 18 months. Lacquered: wipe with damp microfibre.',
      warranty: '3 years structural',
      rating: 4.6,
      reviewCount: 82,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Scholar Bookcase in natural birch', isPrimary: true },
    ],
  },
  {
    sku: 'STU-BS-004',
    slug: 'archive-modular-shelf',
    name: 'Archive Modular Shelf',
    categorySlug: 'study',
    subcategorySlug: 'bookshelves',
    brand: 'Modulas Atelier',
    price: 95000,
    currency: 'INR',
    material: 'Solid oak with hand-woven cane cabinet doors',
    finishOptions: ['Natural Oak / Natural Cane', 'Smoked Oak / Bleached Cane'],
    dimensions: { width: 160, height: 185, depth: 38, unit: 'cm' },
    weightKg: 74,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 9,
    leadTimeDays: 21,
    seoTitle: 'Archive Modular Shelf – Oak & Cane Doors | Modulas',
    seoDescription: 'Open shelving above, cane-door cabinet storage below — the Archive Modular Shelf in solid oak combines display and concealed storage in one architectural piece.',
    tags: ['bookshelf', 'oak', 'cane', 'modular', 'display-storage', 'subcategory:bookshelves'],
    description: 'The Archive Modular Shelf pairs open display shelves above with woven cane door cabinet storage below — a sophisticated combination of exhibition and concealment in solid oak.',
    metadata: {
      fullDescription: 'Four open shelves in the upper register provide a gallery for books, art objects, and ceramics; two cane-fronted cabinet doors in the lower register conceal folders, boxes, and supplies behind a tactile woven surface that allows air circulation. The structure is solid oak throughout, joined with mortise-and-tenon and secured with internal draw-bolts at the mid-shelf. The cane panels are hand-woven by artisans in Rajasthan.',
      features: [
        'Four open upper display shelves in solid oak',
        'Two lower cane-door cabinets with internal shelf',
        'Hand-woven Rajasthani cane door panels',
        'Mortise-and-tenon frame joinery',
        'Adjustable upper shelf heights',
        'Anti-tip floor levellers',
      ],
      care: 'Dust cane panels with a soft brush. Wipe oak with a damp cloth. Lightly mist cane with water to restore flexibility.',
      warranty: '5 years structural',
      rating: 4.8,
      reviewCount: 27,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900', alt: 'Archive Modular Shelf in natural oak and cane', isPrimary: true },
    ],
  },

  // ── Study Armchairs (3) ──────────────────────────────────────────────────
  {
    sku: 'STU-AC-001',
    slug: 'lumina-study-armchair',
    name: 'Lumina Study Armchair',
    categorySlug: 'study',
    subcategorySlug: 'study-armchairs',
    brand: 'Modulas Atelier',
    price: 88000,
    compareAtPrice: 105000,
    currency: 'INR',
    material: 'Full-grain leather with solid walnut frame and integrated side table',
    finishOptions: ['Cognac Leather / Dark Walnut', 'Black Leather / Natural Walnut'],
    dimensions: { width: 82, height: 90, depth: 86, unit: 'cm' },
    weightKg: 34,
    isConfigurable: true,
    isFeatured: true,
    stockQty: 8,
    leadTimeDays: 21,
    seoTitle: 'Lumina Study Armchair – Leather & Walnut with Side Table | Modulas',
    seoDescription: 'The Lumina Study Armchair pairs full-grain leather seating with a solid walnut frame and a swivelling integrated side table — the perfect reading chair for a considered study.',
    tags: ['study-armchair', 'leather', 'walnut', 'reading-chair', 'side-table', 'subcategory:study-armchairs'],
    description: 'The Lumina Study Armchair is a reading chair par excellence — full-grain leather upholstery, solid walnut frame, and a swivelling integrated side table that holds a drink and a book.',
    metadata: {
      fullDescription: 'Its wide, deeply padded seat — upholstered in full-grain leather over an eight-way hand-tied spring base — accommodates a wide range of seated positions. The solid walnut frame presents slender, angled legs and exposed arm rails that taper elegantly forward. A swivelling solid walnut side table mounts to the right arm via a chrome pivot and folds flush when not required. The back cushion is removable and independently replaceable.',
      features: [
        'Full-grain leather over eight-way hand-tied spring base',
        'Solid walnut frame — legs, arm rails, and side table',
        'Swivelling fold-flat side table on chrome pivot',
        'Removable and replaceable back cushion',
        'Hand-finished walnut in natural oil',
      ],
      care: 'Condition leather every 3 months. Pivot mechanism: apply a drop of machine oil annually. Walnut: wipe with a dry cloth.',
      warranty: '5 years structural, 3 years leather',
      rating: 4.9,
      reviewCount: 24,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900', alt: 'Lumina Study Armchair in cognac leather', isPrimary: true },
    ],
  },
  {
    sku: 'STU-AC-002',
    slug: 'regent-reading-chair',
    name: 'Regent Reading Chair',
    categorySlug: 'study',
    subcategorySlug: 'study-armchairs',
    brand: 'Modulas Atelier',
    price: 65000,
    currency: 'INR',
    material: 'Premium wool blend fabric with solid beech frame',
    finishOptions: ['Camel Wool', 'Forest Green Wool', 'Midnight Blue Wool'],
    dimensions: { width: 76, height: 88, depth: 82, unit: 'cm' },
    weightKg: 28,
    isConfigurable: false,
    isFeatured: false,
    stockQty: 14,
    leadTimeDays: 14,
    seoTitle: 'Regent Reading Chair – Wool & Beech | Modulas',
    seoDescription: 'The Regent Reading Chair wraps a solid beech frame in premium wool blend upholstery — a quietly sophisticated armchair ideal for a study or bedroom reading nook.',
    tags: ['study-armchair', 'wool', 'beech', 'reading-chair', 'subcategory:study-armchairs'],
    description: 'Quiet, enveloping, and perfectly proportioned for a study corner — the Regent Reading Chair upholsters a solid beech frame in a premium British wool blend.',
    metadata: {
      fullDescription: 'Wide enough to curl into, deep enough to disappear in, and covered in a premium British wool blend that grows more characterful with each passing season. The solid beech frame is finished in a satin-matte lacquer and presents gently splayed rear legs. A hand-tied spring seat and down-feather-wrapped foam cushions ensure the chair invites rather than merely permits prolonged sitting.',
      features: [
        'Premium British wool blend upholstery',
        'Solid beech frame, satin-matte lacquer finish',
        'Gently splayed rear legs for stability',
        'Hand-tied spring seat',
        'Down-feather-wrapped foam cushions',
        'Three colourways available',
      ],
      care: 'Brush wool fabric gently with a clothes brush. Spot-clean with a damp cloth and mild soap. Professional dry-clean for full clean.',
      warranty: '3 years structural, 2 years upholstery',
      rating: 4.7,
      reviewCount: 48,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900', alt: 'Regent Reading Chair in camel wool', isPrimary: true },
    ],
  },
  {
    sku: 'STU-AC-003',
    slug: 'lounge-library-chair',
    name: 'Lounge Library Chair',
    categorySlug: 'study',
    subcategorySlug: 'study-armchairs',
    brand: 'Modulas Atelier',
    price: 110000,
    compareAtPrice: 130000,
    currency: 'INR',
    material: 'Crushed velvet with polished brass 360° swivel base',
    finishOptions: ['Deep Teal Velvet', 'Dusty Rose Velvet', 'Charcoal Velvet'],
    dimensions: { width: 78, height: 92, depth: 84, unit: 'cm' },
    weightKg: 32,
    isConfigurable: true,
    isFeatured: false,
    stockQty: 7,
    leadTimeDays: 21,
    seoTitle: 'Lounge Library Chair – Velvet Swivel | Modulas',
    seoDescription: 'The Lounge Library Chair wraps a deeply padded swivel chair in crushed velvet on a polished brass base — equal parts design statement and reading sanctuary.',
    tags: ['study-armchair', 'velvet', 'swivel', 'brass', 'reading-chair', 'subcategory:study-armchairs'],
    description: 'A velvet swivel chair that commands attention and invites indulgence. The Lounge Library Chair rotates 360° on a polished brass base, pairing theatrical aesthetics with genuine comfort.',
    metadata: {
      fullDescription: 'A generous bucket-seat silhouette — with high wings and a wide, deeply padded seat — is upholstered in silk-content crushed velvet that catches light dramatically. A 360° polished brass swivel base allows the chair to address a desk one moment and a fireplace the next. The base is die-cast brass — not plated — with a lacquer protective coat. A feather-and-foam seat cushion provides the necessary indulgence for multi-hour reading sessions.',
      features: [
        'Silk-content crushed velvet upholstery, three colourways',
        '360° polished die-cast brass swivel base (not plated)',
        'High-wing back and generous bucket seat silhouette',
        'Feather-and-foam seat cushion',
        'Lacquer protective coat on brass base',
      ],
      care: 'Use a velvet brush to restore pile direction. Spot-clean with a dry-cleaning solvent cloth. Protect from prolonged sunlight.',
      warranty: '3 years structural, 2 years upholstery, 5 years brass base',
      rating: 4.8,
      reviewCount: 31,
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900', alt: 'Lounge Library Chair in deep teal velvet', isPrimary: true },
    ],
  },
];
