import type { SeedProduct } from "./catalog.seed";

// ─────────────────────────────────────────────────────────────
// CATEGORY 3 — DINING  (26 products)
// ─────────────────────────────────────────────────────────────
export const DINING: SeedProduct[] = [
  // ── Dining Tables (6) ─────────────────────────────────────────
  {
    sku: "MOD-DIN-001", slug: "orion-solid-oak-dining-table",
    name: "Orion Solid Oak Dining Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Modulas Originals", price: 285000, compareAtPrice: 335000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural Oil", "Whitened Oak", "Dark Smoked"],
    dimensions: { width: 200, height: 75, depth: 95, unit: "cm" }, weightKg: 92,
    isConfigurable: true, isFeatured: true, stockQty: 8, leadTimeDays: 28,
    seoTitle: "Orion Solid Oak Dining Table — Modulas Luxury Dining Furniture India",
    seoDescription: "Solid oak dining table, 200 cm — seats 8. Mortise-and-tenon joinery. 3 finishes. Custom sizes available. India-wide white-glove delivery.",
    tags: ["bestseller", "sale", "subcategory:dining-tables"],
    description: "200 cm of solid oak, finished in three ways — and joints that will outlast the trends that come and go around it.",
    metadata: {
      fullDescription: "The Orion is the anchor of Modulas's dining range — a table that works as naturally in a contemporary apartment as it does in a period home. Built from solid European oak (not oak veneer), its surface is 4 cm thick and finished with a penetrating oil that feeds the wood rather than coating it. The trestle base uses traditional mortise-and-tenon joinery, creating a structure that distributes weight evenly and resists the racking that causes cheaper tables to wobble over time.",
      features: [
        "Solid European oak — 4 cm thick surface",
        "Mortise-and-tenon trestle base joinery",
        "Seats 8 comfortably (6 with arm chairs)",
        "Penetrating oil finish — 3 colourways",
        "Custom lengths available (160 cm to 280 cm)",
        "Matching Orion bench and dining chairs",
        "10-year structural guarantee",
      ],
      care: "Wipe with dry cloth. Re-oil with teak or Danish oil once per year. Use table mats to prevent heat and moisture rings.",
      warranty: "10-year structural guarantee.",
      rating: 4.9, reviewCount: 168,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Orion Oak Dining Table in Natural Oil", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Orion — table leg and grain detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DIN-002", slug: "calacatta-grand-marble-table",
    name: "Calacatta Grand Marble Dining Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Heritage Collection", price: 625000, currency: "INR",
    material: "Calacatta Marble & Solid Brass", finishOptions: ["Calacatta White / Brushed Brass", "Statuario Grey / Matte Black"],
    dimensions: { width: 220, height: 75, depth: 100, unit: "cm" }, weightKg: 168,
    isConfigurable: false, isFeatured: true, stockQty: 3, leadTimeDays: 56,
    seoTitle: "Calacatta Marble Dining Table with Brass Base — Heritage Collection",
    seoDescription: "220 cm Calacatta marble dining table on solid brass base. Seats 10. Heritage Collection — limited production. Free white-glove delivery.",
    tags: ["premium", "limited", "subcategory:dining-tables"],
    description: "A 220 cm Calacatta marble table on a solid brass base — the dining table as a geological event. No two pieces of marble are identical.",
    metadata: {
      fullDescription: "The Calacatta Grand is Heritage Collection's most significant dining piece — a table whose materials alone tell a story. The Calacatta Bianco marble top (3 cm thick, honed finish) is sourced from a quarry in Carrara, Tuscany, and sealed before shipping. The base is constructed from 50 mm solid brass sections, welded and brushed by hand. Because no two pieces of Calacatta marble are identical, every table is truly one of a kind — the marble pattern will be photographed and shared before dispatch.",
      features: [
        "3 cm honed Calacatta Bianco marble top",
        "Individually photographed marble pattern — shared pre-dispatch",
        "Solid brass welded base — brushed by hand",
        "220 cm — seats 10 generously",
        "Marble care kit and sealer included",
        "Available 180 cm, 200 cm, and 220 cm",
        "Heritage Collection — made in small batches",
      ],
      care: "Wipe marble immediately after use. Re-seal every 6 months. Use trivets for hot dishes. Polish brass base with a soft dry cloth.",
      warranty: "Lifetime marble structure. 10-year brass base.",
      rating: 5.0, reviewCount: 29,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Calacatta Grand Marble Dining Table", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Calacatta — marble surface and brass base detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DIN-003", slug: "pinnacle-round-dining-table",
    name: "Pinnacle Round Dining Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Modulas Originals", price: 248000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut", "Ebonised"],
    dimensions: { width: 130, height: 75, depth: 130, unit: "cm" }, weightKg: 74,
    isConfigurable: false, isFeatured: false, stockQty: 10, leadTimeDays: 28,
    seoTitle: "Pinnacle Round Solid Walnut Dining Table — Modulas",
    seoDescription: "Round solid walnut dining table, 130 cm diameter. Pedestal base. Seats 4–5. Natural, dark, or ebonised finish.",
    tags: ["new", "subcategory:dining-tables"],
    description: "Round tables create conversations that rectangular tables cannot. The Pinnacle's pedestal base in solid walnut seats five without compromise.",
    metadata: {
      fullDescription: "The Pinnacle Round Table is designed around the principle that the best dining conversations happen when everyone can see everyone else — which a round table enables and a rectangular one doesn't. Its 130 cm diameter is the sweet spot: wide enough to seat five comfortably (four with arm chairs), compact enough to fit in dining rooms that a larger table would overwhelm. The single-pedestal base — in solid walnut — keeps legs out of the way.",
      features: [
        "130 cm diameter — seats 4–5",
        "Single pedestal base — no leg interference",
        "Solid walnut top — 3.5 cm thick",
        "Mortise-and-tenon pedestal joinery",
        "3 walnut finishes",
        "Available 120 cm and 150 cm diameters",
        "10-year structural guarantee",
      ],
      care: "Oil walnut surface twice per year. Use coasters and table mats. Wipe with dry cloth.",
      warranty: "10-year structural.",
      rating: 4.8, reviewCount: 92,
    },
    images: [
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Pinnacle Round Walnut Table", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Pinnacle — pedestal base detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DIN-004", slug: "prestige-travertine-dining-table",
    name: "Prestige Travertine Dining Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Atelier Series", price: 445000, currency: "INR",
    material: "Travertine & Solid Oak", finishOptions: ["Roman Travertine / Natural Oak", "Silver Travertine / Smoked Oak"],
    dimensions: { width: 210, height: 75, depth: 100, unit: "cm" }, weightKg: 148,
    isConfigurable: false, isFeatured: false, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Prestige Travertine Dining Table — Atelier Series Modulas",
    seoDescription: "Travertine dining table on solid oak trestle base. 210 cm, seats 8–10. Honed and filled finish. Natural or silver travertine.",
    tags: ["premium", "subcategory:dining-tables"],
    description: "Travertine — the stone of the Roman Colosseum — honed and filled, then mounted on a solid oak trestle. History, brought to the dining table.",
    metadata: {
      fullDescription: "The Prestige Travertine Table references the centuries-old tradition of using travertine for grand architectural surfaces — and brings that material into the dining room. The travertine top is honed (not polished) for a matte, mineral surface that is less reflective than marble and more forgiving in daily use. The voids in the travertine are filled with a matching resin before surface treatment, creating a smooth surface while preserving the stone's characteristic texture.",
      features: [
        "Honed and void-filled travertine top — 3 cm thick",
        "Solid oak trestle base — mortise-and-tenon",
        "210 cm — seats 8–10",
        "Travertine care kit included",
        "Available 180 cm and 210 cm",
        "Two stone and wood combinations",
        "10-year structural guarantee",
      ],
      care: "Wipe spills immediately. Use trivets for heat. Re-seal every 12 months. Oil oak base annually.",
      warranty: "10-year structural. 1-year stone sealing.",
      rating: 4.8, reviewCount: 47,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Prestige Travertine Dining Table", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Prestige — stone surface texture detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DIN-005", slug: "luxe-oval-dining-table",
    name: "Luxe Oval Walnut Dining Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Atelier Series", price: 368000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut"],
    dimensions: { width: 210, height: 75, depth: 105, unit: "cm" }, weightKg: 102,
    isConfigurable: false, isFeatured: false, stockQty: 6, leadTimeDays: 35,
    seoTitle: "Luxe Oval Solid Walnut Dining Table — Atelier Series Modulas",
    seoDescription: "Oval solid walnut dining table, 210 cm. Seats 8. No sharp corners. Cross-leg trestle base. Atelier Series by Modulas.",
    tags: ["subcategory:dining-tables"],
    description: "The oval resolves the rectangle's sharp corners without losing its generous seating capacity. The Luxe Oval is the dining table that works for families.",
    metadata: {
      fullDescription: "The oval dining table is chosen by families and those who host frequently — its curved ends allow easier movement around the table and remove the risk of sharp corner impacts. The Luxe Oval's 210 cm length seats eight, and its cross-leg trestle base — in the same solid walnut as the top — creates an architectural undercarriage that is as interesting viewed from below as above.",
      features: [
        "Oval form — no sharp corners",
        "210 cm — seats 8",
        "Cross-leg solid walnut trestle base",
        "3.5 cm thick walnut top",
        "Available 180 cm and 210 cm",
        "Custom oval sizes on request",
        "10-year structural guarantee",
      ],
      care: "Oil walnut bi-annually. Use table mats. Wipe with dry cloth after use.",
      warranty: "10-year structural.",
      rating: 4.7, reviewCount: 78,
    },
    images: [
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Luxe Oval Walnut Dining Table", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Luxe Oval — cross-leg trestle detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DIN-006", slug: "barcelona-glass-steel-table",
    name: "Barcelona Glass & Steel Table", categorySlug: "dining", subcategorySlug: "dining-tables",
    brand: "Atelier Series", price: 195000, currency: "INR",
    material: "Tempered Glass & Brushed Steel", finishOptions: ["Clear Glass / Brushed Steel", "Smoked Glass / Matte Black"],
    dimensions: { width: 180, height: 75, depth: 90, unit: "cm" }, weightKg: 68,
    isConfigurable: false, isFeatured: false, stockQty: 12, leadTimeDays: 21,
    seoTitle: "Barcelona Tempered Glass Dining Table — Atelier Series Modulas",
    seoDescription: "180 cm tempered glass dining table on brushed steel base. Clear or smoked glass. Seats 6–8. Contemporary minimalist dining.",
    tags: ["subcategory:dining-tables"],
    description: "A 15 mm tempered glass surface on a powder-coated steel base — the Barcelona is the dining table for rooms that want to keep the floor in view.",
    metadata: {
      fullDescription: "Glass dining tables divide opinion — and the Barcelona is designed for those who believe the glass top is the right choice for their space. The 15 mm toughened glass top (heat-strengthened, not just thermally treated) sits on a welded steel base that is powder-coated in two finishes. Because the top is transparent, the room's flooring becomes part of the composition — a consideration that works particularly well in rooms with statement marble or herringbone oak floors.",
      features: [
        "15 mm heat-strengthened tempered glass top",
        "Welded powder-coated steel base",
        "Clear or smoked glass options",
        "180 cm — seats 6 with arm chairs, 8 without",
        "Glass edge polished — no sharpness",
        "Silicone mounting pads — no visible fixings",
        "10-year structural guarantee",
      ],
      care: "Clean glass with glass cleaner. Avoid abrasive pads. Wipe steel with dry cloth.",
      warranty: "10-year structural. 5-year glass integrity.",
      rating: 4.5, reviewCount: 104,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Barcelona Glass Dining Table — clear glass", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Barcelona — glass edge and steel base", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Dining Chairs (6) ─────────────────────────────────────────
  {
    sku: "MOD-DCH-001", slug: "cleo-velvet-dining-chair",
    name: "Cleo Velvet Dining Chair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Modulas Originals", price: 42000, currency: "INR",
    material: "Velvet & Solid Ash", finishOptions: ["Dusty Rose", "Sage Green", "Ink Blue", "Graphite", "Champagne"],
    dimensions: { width: 52, height: 88, depth: 56, unit: "cm" }, weightKg: 7,
    isConfigurable: false, isFeatured: true, stockQty: 40, leadTimeDays: 14,
    seoTitle: "Cleo Velvet Dining Chair — Modulas Luxury Dining Chairs India",
    seoDescription: "Fully upholstered velvet dining chair in 5 colourways. Solid ash frame. 88 cm height. Sold individually. Pairs with all Modulas dining tables.",
    tags: ["bestseller", "subcategory:dining-chairs"],
    description: "Fully upholstered in velvet — including the inner back and seat — the Cleo turns every dining chair into a statement. Pairs with any Modulas dining table.",
    metadata: {
      fullDescription: "The Cleo Dining Chair is fully upholstered — seat, inside back, outside back, and arms — in 480 gsm velvet. This makes it a richer, softer chair than the industry standard of upholstered seat and back panel only. The solid ash frame (visible at the legs and arm joints) provides the structural contrast that keeps the fully upholstered form from becoming heavy. Five colourways are available — all chosen to work with the walnut and oak tables in the Modulas dining range.",
      features: [
        "Fully upholstered — seat, back, and outer back",
        "480 gsm velvet in 5 colourways",
        "Solid ash frame — visible legs and arm joints",
        "Sprung seat — retains shape after years of use",
        "88 cm height — compatible with standard 75 cm tables",
        "Sold individually — build your set",
        "Stackable — up to 4 chairs",
      ],
      care: "Brush velvet after use. Spot-clean with velvet foam cleaner.",
      warranty: "5-year frame. 2-year fabric.",
      rating: 4.8, reviewCount: 356,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Cleo Velvet Dining Chair in Dusty Rose", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Cleo — fully upholstered back detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DCH-002", slug: "regent-linen-dining-chair",
    name: "Regent Linen Dining Chair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Atelier Series", price: 38000, currency: "INR",
    material: "Belgian Linen & Solid Oak", finishOptions: ["Natural Linen", "Warm Stone", "Sage", "Dusty Pink"],
    dimensions: { width: 50, height: 86, depth: 54, unit: "cm" }, weightKg: 6,
    isConfigurable: false, isFeatured: false, stockQty: 48, leadTimeDays: 14,
    seoTitle: "Regent Belgian Linen Dining Chair — Atelier Series Modulas",
    seoDescription: "Belgian linen dining chair on solid oak frame. 4 colourways. 86 cm. Stackable. Natural and refined — pairs with oak and marble tables.",
    tags: ["subcategory:dining-chairs"],
    description: "Belgian linen on a solid oak frame — the Regent is the dining chair that works without trying, in any room and with any table.",
    metadata: {
      fullDescription: "The Regent is Modulas's most versatile dining chair — a neutral, refined form in Belgian linen that will work with oak tables, marble tables, glass tables, and everything in between. Its solid oak frame has chamfered legs — a detail that catches light differently on each face, making the legs look slimmer than they are. The linen is pre-treated for resistance to food and liquid staining.",
      features: [
        "Belgian linen — stain-treated, 4 colourways",
        "Solid oak chamfered leg frame",
        "Upholstered seat and inner back",
        "86 cm height — standard table compatibility",
        "Stackable — up to 4 chairs",
        "Available with or without arms",
        "Sold individually or in sets of 2, 4, 6",
      ],
      care: "Spot-clean linen with damp cloth and mild cleaner. Dry-clean cushion covers.",
      warranty: "5-year frame. 2-year fabric.",
      rating: 4.7, reviewCount: 228,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Regent Linen Dining Chair in Natural", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Regent — oak leg chamfer detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DCH-003", slug: "windsor-leather-dining-chair",
    name: "Windsor Leather Dining Chair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Heritage Collection", price: 78000, currency: "INR",
    material: "Full-Grain Leather & Solid Walnut", finishOptions: ["Cognac", "Midnight Black", "Tobacco", "Dove Grey"],
    dimensions: { width: 54, height: 92, depth: 58, unit: "cm" }, weightKg: 9,
    isConfigurable: false, isFeatured: false, stockQty: 20, leadTimeDays: 21,
    seoTitle: "Windsor Full-Grain Leather Dining Chair — Heritage Collection Modulas",
    seoDescription: "Full-grain leather dining chair on solid walnut frame. 4 colourways. Heritage Collection — hand-stitched seams. Pairs with marble and walnut tables.",
    tags: ["premium", "subcategory:dining-chairs"],
    description: "Full-grain leather and solid walnut — the Windsor brings the same material rigour as the best sitting room furniture to the dining table.",
    metadata: {
      fullDescription: "The Windsor is Heritage Collection's dining chair — a piece that refuses the compromise of 'bonded leather' or 'walnut-effect' that plagues most dining chairs in this price range. The leather is full-grain, from the same Kanpur tannery that supplies the Chesterfield sofa. The walnut frame uses through-tenon joinery at the back legs, visible from the side — a deliberate display of structural honesty.",
      features: [
        "Full-grain leather — same tannery as Heritage Chesterfield",
        "Through-tenon walnut joinery — visible structural detail",
        "Solid American black walnut frame",
        "Sprung seat — coil spring base",
        "Hand-stitched leather seams",
        "92 cm height — suitable for 75–78 cm tables",
        "Sold individually or as a set",
      ],
      care: "Condition leather monthly. Wipe with dry cloth. Oil walnut legs bi-annually.",
      warranty: "10-year frame. 5-year leather.",
      rating: 4.9, reviewCount: 87,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Windsor Leather Dining Chair in Cognac", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Windsor — through-tenon joint detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DCH-004", slug: "rattan-natural-dining-chair",
    name: "Alma Rattan Dining Chair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Modulas Originals", price: 28000, currency: "INR",
    material: "Natural Rattan & Solid Oak", finishOptions: ["Natural Rattan / Oak", "Whitewashed Rattan / Oak", "Black Rattan / Oak"],
    dimensions: { width: 48, height: 84, depth: 52, unit: "cm" }, weightKg: 5,
    isConfigurable: false, isFeatured: false, stockQty: 55, leadTimeDays: 10,
    seoTitle: "Alma Rattan Dining Chair in Natural — Modulas",
    seoDescription: "Natural rattan dining chair on solid oak frame. 3 finishes. 84 cm. Lightweight, stackable. Brings warmth to any dining table.",
    tags: ["new", "subcategory:dining-chairs"],
    description: "Woven natural rattan on a solid oak frame — the Alma brings organic texture to the dining table without overwhelming it.",
    metadata: {
      fullDescription: "The Alma Chair is a response to the growing demand for natural materials in the dining room. Hand-woven rattan, wrapped over a solid oak frame, creates a seat and back that is lightweight, breathable, and visually warm. At 5 kg, the Alma is easy to move — an important quality for chairs that are repositioned daily. Available in three finishes: natural, whitewashed, and black-stained.",
      features: [
        "Hand-woven natural rattan — seat and back",
        "Solid oak frame",
        "5 kg — lightweight and easy to move",
        "Stackable — up to 6 chairs",
        "3 finish options",
        "Indoor and covered outdoor use",
        "Sold individually or in sets of 2, 4, 6",
      ],
      care: "Wipe rattan with a barely damp cloth. Air dry. Oil oak legs annually. Do not saturate rattan with water.",
      warranty: "3-year structural.",
      rating: 4.6, reviewCount: 184,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Alma Rattan Dining Chair in Natural", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Alma — rattan weave detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DCH-005", slug: "oxford-upholstered-armchair-dining",
    name: "Oxford Carver Armchair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Atelier Series", price: 55000, currency: "INR",
    material: "Boucle Fabric & Solid Oak", finishOptions: ["Oatmeal", "Sage", "Slate", "Warm Sand"],
    dimensions: { width: 60, height: 90, depth: 58, unit: "cm" }, weightKg: 9,
    isConfigurable: false, isFeatured: false, stockQty: 28, leadTimeDays: 14,
    seoTitle: "Oxford Carver Boucle Dining Armchair — Atelier Series Modulas",
    seoDescription: "Fully upholstered boucle carver dining armchair. 60 cm wide. Use at table ends for a mixed-chair dining setup. 4 colourways.",
    tags: ["subcategory:dining-chairs"],
    description: "The carver chair — used at the heads of the table — elevated to a fully upholstered boucle armchair with solid oak arms.",
    metadata: {
      fullDescription: "The Oxford Carver is designed to be used at the ends of a rectangular dining table, creating the classic 'carver and side chair' pairing that gives a formal dining room its distinction. The wider 60 cm frame provides the presence appropriate for the head positions, while the boucle upholstery and solid oak arms bring warmth and comfort to a role that is traditionally more decorative than functional.",
      features: [
        "60 cm width — proportioned for table head positions",
        "Boucle upholstery — seat, back, and arms",
        "Solid oak arm rests and legs",
        "90 cm height — suitable for 75 cm tables",
        "4 boucle colourways",
        "Sold individually or in pairs",
        "Pairs with Regent or Cleo side chairs",
      ],
      care: "Vacuum boucle with soft brush. Spot-clean with foam cleaner. Oil oak arms annually.",
      warranty: "5-year frame. 2-year fabric.",
      rating: 4.7, reviewCount: 112,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Oxford Carver Chair in Oatmeal Boucle", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Oxford — boucle arm and oak leg detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-DCH-006", slug: "imperiale-high-back-chair",
    name: "Imperiale High-Back Dining Chair", categorySlug: "dining", subcategorySlug: "dining-chairs",
    brand: "Heritage Collection", price: 68000, currency: "INR",
    material: "Full-Grain Leather & Solid Walnut", finishOptions: ["Oxblood", "Forest Green", "Midnight Navy", "Cognac"],
    dimensions: { width: 52, height: 105, depth: 56, unit: "cm" }, weightKg: 10,
    isConfigurable: false, isFeatured: false, stockQty: 16, leadTimeDays: 21,
    seoTitle: "Imperiale High-Back Leather Dining Chair — Heritage Collection Modulas",
    seoDescription: "105 cm high-back dining chair in full-grain leather. Solid walnut frame, brass nailhead. Heritage Collection. Dramatic table presence.",
    tags: ["premium", "subcategory:dining-chairs"],
    description: "A 105 cm high back in full-grain leather — the Imperiale is the dining chair that transforms a meal into an occasion.",
    metadata: {
      fullDescription: "High-back dining chairs create a visual enclosure that turns a dining table into a private room within the room — an effect that has been used in grand dining halls and private clubs for centuries. The Imperiale carries this tradition into the contemporary home, with a 105 cm leather-upholstered back that provides genuine lumbar and shoulder support for extended dining. Brass nailhead trim around the back perimeter references the tailoring tradition of English club chairs.",
      features: [
        "105 cm high back — shoulder support for extended dining",
        "Full-grain leather — 4 deep colourways",
        "Brass nailhead trim around back perimeter",
        "Solid walnut frame",
        "Coil-sprung seat",
        "Sold individually — create a mixed-height table setting",
        "Heritage Collection — hand-built at Jaipur Atelier",
      ],
      care: "Condition leather monthly. Wipe nailhead with dry cloth. Oil walnut legs bi-annually.",
      warranty: "10-year frame. 5-year leather.",
      rating: 4.9, reviewCount: 44,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Imperiale High-Back Chair in Oxblood Leather", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Imperiale — nailhead back detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Extendable Tables (4) ──────────────────────────────────────
  {
    sku: "MOD-EXT-001", slug: "savoy-walnut-extendable-table",
    name: "Savoy Walnut Extendable Table", categorySlug: "dining", subcategorySlug: "extendable-tables",
    brand: "Modulas Originals", price: 365000, compareAtPrice: 425000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut"],
    dimensions: { width: 180, height: 75, depth: 95, unit: "cm" }, weightKg: 104,
    isConfigurable: true, isFeatured: true, stockQty: 6, leadTimeDays: 35,
    seoTitle: "Savoy Solid Walnut Extendable Dining Table — Modulas",
    seoDescription: "Solid walnut extendable dining table. 180 cm extends to 260 cm. Self-storing leaf. Seats 6 to 10. Ships in 35 days.",
    tags: ["bestseller", "sale", "subcategory:extendable-tables"],
    description: "180 cm compact, 260 cm when extended — the Savoy seats six on a Tuesday and ten on a Sunday without any compromise in material or finish.",
    metadata: {
      fullDescription: "The Savoy Extendable Table uses a self-storing butterfly leaf mechanism — the 80 cm extension leaf folds and stores within the table's own structure, beneath the surface, so it is always present and never needs a separate storage location. Extending the table takes 30 seconds and requires no lifting. The table is entirely solid walnut — the extension leaf is cut from the same timber as the main surface, ensuring grain and colour continuity when extended.",
      features: [
        "Self-storing butterfly leaf — no separate storage",
        "30-second extension — no lifting",
        "Extension leaf cut from same timber — continuous grain",
        "Solid walnut — 3.5 cm thick surface",
        "180 cm compact / 260 cm extended",
        "Seats 6 compact, 10 extended",
        "10-year structural and mechanism guarantee",
      ],
      care: "Oil surface twice per year. Wipe spills immediately. Lubricate extension mechanism with wax annually.",
      warranty: "10-year structural and mechanism.",
      rating: 4.9, reviewCount: 134,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Savoy Walnut Extendable Table — compact", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Savoy — fully extended seating view", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-EXT-002", slug: "onyx-marble-extendable-table",
    name: "Onyx Marble Extendable Table", categorySlug: "dining", subcategorySlug: "extendable-tables",
    brand: "Atelier Series", price: 545000, currency: "INR",
    material: "Marble & Lacquered MDF", finishOptions: ["Calacatta / White Lacquer", "Grey Marble / Graphite Lacquer"],
    dimensions: { width: 160, height: 75, depth: 90, unit: "cm" }, weightKg: 122,
    isConfigurable: false, isFeatured: false, stockQty: 3, leadTimeDays: 42,
    seoTitle: "Onyx Marble Extendable Dining Table — Atelier Series Modulas",
    seoDescription: "Marble-top extendable table. 160 cm extends to 240 cm. Hidden extension mechanism. Marble leaf matches main top. Seats 6 to 8.",
    tags: ["premium", "subcategory:extendable-tables"],
    description: "A marble dining table that extends — the Onyx solves the challenge of hosting more guests without sacrificing the material integrity of the top.",
    metadata: {
      fullDescription: "Extending a stone-top table presents unique challenges — stone cannot flex, so the extension mechanism must be entirely housed in the base structure. The Onyx uses a synchronized pull-out mechanism that extends both sides of the table evenly by 40 cm each, revealing a lacquered MDF extension panel that, while not stone, is colour-matched to the marble and visually minimal. The marble top halves are thick enough not to rock when extended.",
      features: [
        "Marble top — 2.5 cm thick Calacatta or grey",
        "Synchronized pull-out extension — both sides",
        "Colour-matched lacquered extension panel",
        "160 cm compact / 240 cm extended",
        "Seats 6 compact, 8–10 extended",
        "Marble care kit included",
        "10-year structural and mechanism guarantee",
      ],
      care: "Wipe marble immediately. Re-seal every 6 months. Lubricate extension mechanism with furniture wax annually.",
      warranty: "10-year structural. 5-year mechanism. 1-year marble sealing.",
      rating: 4.7, reviewCount: 38,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Onyx Marble Extendable Table — compact", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Onyx — marble surface and base detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-EXT-003", slug: "cascade-oak-extendable-table",
    name: "Cascade Oak Extendable Table", categorySlug: "dining", subcategorySlug: "extendable-tables",
    brand: "Modulas Originals", price: 295000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural", "Whitened", "Smoked"],
    dimensions: { width: 160, height: 75, depth: 90, unit: "cm" }, weightKg: 88,
    isConfigurable: true, isFeatured: false, stockQty: 8, leadTimeDays: 28,
    seoTitle: "Cascade Solid Oak Extendable Dining Table — Modulas",
    seoDescription: "Solid oak extendable table. 160 cm to 240 cm. Seats 6 to 8. 3 finishes. Ships in 28 days. White-glove delivery.",
    tags: ["subcategory:extendable-tables"],
    description: "The Cascade extends from 160 cm to 240 cm in a single pull — solid oak, three finishes, and an extension leaf that is cut from the same board as the top.",
    metadata: {
      fullDescription: "The Cascade Oak Extendable is the workhorse of the Modulas dining range — the table that hosts the family without ceremony and expands for guests without drama. The extension mechanism is a pull-apart system: the two halves of the table pull apart to reveal the extension leaf stored within the base structure. Total extension time is under 30 seconds.",
      features: [
        "Pull-apart extension — single motion, under 30 seconds",
        "Extension leaf from same board as top — continuous grain",
        "Solid oak throughout — 3.5 cm thick",
        "160 cm compact / 240 cm extended",
        "Seats 6 compact, 8 extended",
        "3 finishes — natural, whitened, smoked",
        "10-year structural and mechanism guarantee",
      ],
      care: "Oil surface twice yearly. Wipe with dry cloth. Wax mechanism annually.",
      warranty: "10-year structural and mechanism.",
      rating: 4.7, reviewCount: 116,
    },
    images: [
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Cascade Oak Table — compact", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Cascade — extended and styled", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-EXT-004", slug: "elm-round-extendable-table",
    name: "Elm Round Extendable Table", categorySlug: "dining", subcategorySlug: "extendable-tables",
    brand: "Atelier Series", price: 318000, currency: "INR",
    material: "Solid Elm", finishOptions: ["Natural Elm", "Oiled Elm"],
    dimensions: { width: 120, height: 75, depth: 120, unit: "cm" }, weightKg: 78,
    isConfigurable: false, isFeatured: false, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Elm Round Extendable Dining Table — Atelier Series Modulas",
    seoDescription: "Round solid elm extendable table. 120 cm extends to 180 cm oval. Pedestal base. Seats 4 round, 6 oval. Unique grain character.",
    tags: ["new", "subcategory:extendable-tables"],
    description: "A round table that becomes oval when extended — the Elm transitions from a 4-seat intimate setting to a 6-seat gathering without leaving its round character behind.",
    metadata: {
      fullDescription: "Elm is one of the most characterful furniture timbers — its grain is wild, swirling, and impossible to predict, making every piece genuinely unique. The Elm Round Extendable Table is 120 cm in diameter when compact (seats 4), and extends to a 180 cm oval (seats 6) via a central extension leaf stored within the pedestal base. The pedestal base means no legs impede the seated occupants in either configuration.",
      features: [
        "Solid elm — each piece unique grain character",
        "Round (120 cm) extends to oval (180 cm)",
        "Central leaf stored in pedestal base",
        "Pedestal base — no leg interference",
        "Seats 4 round, 6 oval",
        "Natural or oiled elm finish",
        "10-year structural and mechanism guarantee",
      ],
      care: "Oil elm twice per year — the open grain benefits from regular feeding. Wipe spills immediately.",
      warranty: "10-year structural.",
      rating: 4.8, reviewCount: 52,
    },
    images: [
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Elm Round Extendable Table — compact round", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?w=900&q=85", altText: "Elm Table — extended oval with chairs", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Sideboards (4) ────────────────────────────────────────────
  {
    sku: "MOD-SDB-001", slug: "grand-walnut-sideboard",
    name: "Grand Walnut Sideboard", categorySlug: "dining", subcategorySlug: "sideboards",
    brand: "Modulas Originals", price: 298000, currency: "INR",
    material: "Solid Walnut", finishOptions: ["Natural Walnut", "Dark Walnut", "Ebonised"],
    dimensions: { width: 185, height: 78, depth: 48, unit: "cm" }, weightKg: 88,
    isConfigurable: false, isFeatured: true, stockQty: 6, leadTimeDays: 35,
    seoTitle: "Grand Solid Walnut Sideboard — Modulas Luxury Dining Storage",
    seoDescription: "185 cm solid walnut sideboard. 4 doors, 2 drawers. Adjustable interior shelves. 78 cm surface height — ideal for service and display.",
    tags: ["bestseller", "subcategory:sideboards"],
    description: "A 185 cm solid walnut sideboard with four doors and two drawers — and a 78 cm surface height that makes it the natural partner for dining service.",
    metadata: {
      fullDescription: "The Grand Walnut Sideboard is designed to serve the dining room in its fullest sense — as storage for dining accessories, a service surface during meals, and a display platform when not in use. Its 78 cm surface height is the same as a standard kitchen countertop, making it genuinely useful for carving, serving, and setting out dishes. Inside, adjustable shelves behind push-to-open doors allow configuration around crockery and glassware of any size.",
      features: [
        "185 cm width — generous dining storage",
        "4 push-to-open doors, 2 soft-close drawers",
        "Adjustable interior shelves",
        "78 cm surface height — service-friendly",
        "Solid walnut throughout",
        "Dovetail drawer joinery",
        "Optional interior LED lighting",
      ],
      care: "Oil walnut surfaces twice per year. Wipe with dry cloth. Clean interior shelves seasonally.",
      warranty: "10-year structural. 5-year mechanism.",
      rating: 4.8, reviewCount: 108,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Grand Walnut Sideboard — natural finish", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Grand Sideboard — interior shelf detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SDB-002", slug: "arte-cane-buffet-cabinet",
    name: "Arte Cane-Front Buffet", categorySlug: "dining", subcategorySlug: "sideboards",
    brand: "Atelier Series", price: 218000, currency: "INR",
    material: "Solid Oak & Cane", finishOptions: ["Natural Oak", "Whitened Oak"],
    dimensions: { width: 155, height: 72, depth: 45, unit: "cm" }, weightKg: 64,
    isConfigurable: false, isFeatured: false, stockQty: 9, leadTimeDays: 28,
    seoTitle: "Arte Cane-Front Buffet Sideboard in Oak — Atelier Series Modulas",
    seoDescription: "Solid oak buffet with cane-weave door fronts. 155 cm wide. 2 drawers, 3 interior zones. Rattan detail adds natural texture.",
    tags: ["new", "subcategory:sideboards"],
    description: "Cane-weave fronts on a solid oak body — the Arte Buffet adds natural texture and visual transparency to dining room storage.",
    metadata: {
      fullDescription: "The Arte Buffet's cane-weave door fronts — woven over solid oak frames — create the same visual reveal as a glass-front cabinet without the reflective properties of glass. The cane allows the interior of the cabinet to be visible in silhouette while keeping the contents soft-focused. The solid oak body has dovetail-joinery drawers and an adjustable interior shelf configuration.",
      features: [
        "Cane-weave door fronts — natural, woven over oak frames",
        "Solid oak frame and body",
        "2 soft-close drawers with dovetail joinery",
        "3 interior storage zones with adjustable shelves",
        "Push-to-open door mechanism — no handles",
        "155 cm width — suitable for medium dining rooms",
        "Matches Arte dining chair",
      ],
      care: "Clean cane fronts with a soft dry brush. Oil oak annually. Wipe interior shelves monthly.",
      warranty: "8-year structural. 3-year mechanism.",
      rating: 4.7, reviewCount: 76,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Arte Cane Buffet in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Arte — cane weave door detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SDB-003", slug: "opus-marble-top-sideboard",
    name: "Opus Marble-Top Sideboard", categorySlug: "dining", subcategorySlug: "sideboards",
    brand: "Heritage Collection", price: 395000, currency: "INR",
    material: "Marble & Solid Walnut", finishOptions: ["Calacatta / Walnut", "Grey Marble / Walnut"],
    dimensions: { width: 165, height: 85, depth: 50, unit: "cm" }, weightKg: 112,
    isConfigurable: false, isFeatured: false, stockQty: 3, leadTimeDays: 42,
    seoTitle: "Opus Marble-Top Sideboard in Walnut — Heritage Collection Modulas",
    seoDescription: "Honed marble-top sideboard on solid walnut base. 165 cm. Heritage Collection — limited production. Marble care kit included.",
    tags: ["premium", "limited", "subcategory:sideboards"],
    description: "A honed marble surface above a solid walnut body — the Opus Sideboard brings the dining table's material language to the room's perimeter.",
    metadata: {
      fullDescription: "When the dining table is marble, the sideboard should answer in kind. The Opus Marble-Top Sideboard pairs the same Calacatta Bianco or Bardiglio grey marble as the Calacatta Grand dining table with a solid walnut base — ensuring the two pieces are in material conversation across the room. The walnut base has four push-to-open doors (two on each side of a central fixed section) and a single drawer.",
      features: [
        "Honed marble top — same material as Calacatta dining table",
        "Solid walnut base — coordinates with walnut dining range",
        "4 push-to-open doors, 1 central drawer",
        "Adjustable internal shelves",
        "85 cm surface height — statement display surface",
        "Marble care kit included",
        "Heritage Collection — limited production",
      ],
      care: "Wipe marble immediately after use. Re-seal every 6 months. Oil walnut base annually.",
      warranty: "Lifetime structural. 1-year marble sealing.",
      rating: 4.9, reviewCount: 27,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Opus Marble Sideboard — Calacatta/Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Opus — marble edge and walnut door detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-SDB-004", slug: "celeste-narrow-sideboard",
    name: "Celeste Narrow Sideboard", categorySlug: "dining", subcategorySlug: "sideboards",
    brand: "Modulas Originals", price: 158000, currency: "INR",
    material: "Solid Oak", finishOptions: ["Natural Oak", "Whitened", "Smoked"],
    dimensions: { width: 120, height: 72, depth: 38, unit: "cm" }, weightKg: 48,
    isConfigurable: false, isFeatured: false, stockQty: 14, leadTimeDays: 21,
    seoTitle: "Celeste Narrow Solid Oak Sideboard — Modulas Dining Room",
    seoDescription: "Compact 120 cm solid oak sideboard. 38 cm depth — fits narrow dining rooms. 2 doors, 2 drawers. 3 finishes. Ships in 21 days.",
    tags: ["subcategory:sideboards"],
    description: "At 38 cm deep, the Celeste fits where standard sideboards cannot — in narrow dining rooms, behind sofa backs, and along passage walls.",
    metadata: {
      fullDescription: "The Celeste Narrow Sideboard was designed for the realities of Indian apartment dining rooms, where wall depth is frequently limited to 35–40 cm along the main dining wall. At 38 cm, it slides into these spaces while providing two storage zones behind push-to-open doors and two soft-close drawers. The solid oak construction and three finish options ensure it integrates naturally with the Orion or Cascade dining tables.",
      features: [
        "38 cm depth — fits narrow dining room walls",
        "2 push-to-open doors, 2 soft-close drawers",
        "Adjustable interior shelf",
        "Solid oak throughout",
        "3 finishes coordinate with dining table range",
        "120 cm width — suitable for compact spaces",
        "8-year structural guarantee",
      ],
      care: "Oil oak annually. Wipe with dry cloth. Clean interior quarterly.",
      warranty: "8-year structural. 3-year mechanism.",
      rating: 4.6, reviewCount: 143,
    },
    images: [
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Celeste Narrow Sideboard in Natural Oak", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Celeste — slim profile side view", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Bar Stools (3) ───────────────────────────────────────────
  {
    sku: "MOD-BST-001", slug: "metro-counter-stool-velvet",
    name: "Metro Velvet Counter Stool", categorySlug: "dining", subcategorySlug: "bar-stools",
    brand: "Modulas Originals", price: 32000, currency: "INR",
    material: "Velvet & Solid Steel", finishOptions: ["Sage", "Dusty Pink", "Graphite", "Champagne"],
    dimensions: { width: 42, height: 90, depth: 42, unit: "cm" }, weightKg: 6,
    isConfigurable: false, isFeatured: false, stockQty: 35, leadTimeDays: 10,
    seoTitle: "Metro Velvet Counter Bar Stool — Modulas Luxury Dining Accessories",
    seoDescription: "Counter-height velvet bar stool on powder-coated steel frame. 65 cm seat height. 4 colourways. Footrest rail. Ships in 10 days.",
    tags: ["bestseller", "subcategory:bar-stools"],
    description: "A velvet counter stool on a powder-coated steel frame — the Metro brings dining chair quality to the kitchen island or breakfast bar.",
    metadata: {
      fullDescription: "The Metro Counter Stool is designed for kitchen islands and breakfast bars at the standard counter height of 90–95 cm. Its seat height is 65 cm — the correct ergonomic height for these surfaces — and its velvet upholstery brings the quality expected of a dining chair to a stool format. The powder-coated steel frame is available in three finishes: brushed brass, matte black, and polished chrome.",
      features: [
        "65 cm seat height — counter-height compatible",
        "Velvet upholstery in 4 colourways",
        "Powder-coated steel frame — 3 metal finishes",
        "Integrated footrest rail — chrome bar",
        "Swivel seat — 360° rotation",
        "Non-marking floor protectors",
        "Sold individually or in sets of 2",
      ],
      care: "Brush velvet seat with soft brush. Wipe steel frame with dry cloth.",
      warranty: "3-year structural.",
      rating: 4.7, reviewCount: 224,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Metro Velvet Counter Stool in Sage", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Metro — footrest and seat detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BST-002", slug: "noble-rattan-bar-stool",
    name: "Noble Rattan Bar Stool", categorySlug: "dining", subcategorySlug: "bar-stools",
    brand: "Atelier Series", price: 24000, currency: "INR",
    material: "Natural Rattan & Solid Ash", finishOptions: ["Natural Rattan", "Whitewashed", "Black Stained"],
    dimensions: { width: 42, height: 95, depth: 42, unit: "cm" }, weightKg: 4,
    isConfigurable: false, isFeatured: false, stockQty: 42, leadTimeDays: 10,
    seoTitle: "Noble Rattan Bar Stool — Atelier Series Modulas",
    seoDescription: "Hand-woven rattan bar stool on solid ash frame. 75 cm seat height (bar height). Stackable. 3 finishes. Natural warmth for any bar or island.",
    tags: ["subcategory:bar-stools"],
    description: "Hand-woven rattan on a solid ash frame — the Noble is the bar stool that brings natural material warmth to the kitchen island without formality.",
    metadata: {
      fullDescription: "The Noble Rattan Bar Stool is the casual, natural-material option in the Modulas bar stool range — suited to kitchens and breakfast bars that want warmth and texture over refinement. At 4 kg, it is easy to move, and its rattan seat is breathable in a way that upholstered stools cannot match in Indian summer conditions. The ash frame is available in three stained finishes.",
      features: [
        "Hand-woven natural rattan seat",
        "Solid ash frame — 3 stained finishes",
        "75 cm seat height — standard bar height",
        "4 kg — easy to move and reposition",
        "Stackable — up to 5 stools",
        "Non-marking floor protectors",
        "Available as a counter-height variant (65 cm)",
      ],
      care: "Wipe rattan with barely damp cloth. Air dry. Oil ash legs annually.",
      warranty: "3-year structural.",
      rating: 4.6, reviewCount: 187,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Noble Rattan Bar Stool in Natural", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Noble — rattan weave seat detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BST-003", slug: "alta-leather-bar-stool",
    name: "Alta Leather Bar Stool", categorySlug: "dining", subcategorySlug: "bar-stools",
    brand: "Heritage Collection", price: 55000, currency: "INR",
    material: "Full-Grain Leather & Solid Walnut", finishOptions: ["Cognac", "Black", "Tan"],
    dimensions: { width: 45, height: 110, depth: 48, unit: "cm" }, weightKg: 8,
    isConfigurable: false, isFeatured: false, stockQty: 16, leadTimeDays: 21,
    seoTitle: "Alta Full-Grain Leather Bar Stool — Heritage Collection Modulas",
    seoDescription: "Full-grain leather bar stool with backrest on solid walnut frame. 75 cm seat. Heritage Collection. For home bars and premium kitchen islands.",
    tags: ["premium", "subcategory:bar-stools"],
    description: "A full-grain leather bar stool with a backrest — the Alta brings Heritage Collection standards to the kitchen island and home bar.",
    metadata: {
      fullDescription: "The Alta Leather Bar Stool is designed for home bars and premium kitchen islands where the bar stool is on full display and needs to carry the same material quality as the surrounding furniture. Its full-grain leather seat and back — secured with hand-stitched seams — are mounted on a solid walnut frame with a through-tenon joint at the top rail, visible from the back as a deliberate structural detail.",
      features: [
        "Full-grain leather seat and back",
        "Hand-stitched leather seams",
        "Solid walnut frame — through-tenon back rail",
        "75 cm seat height — standard bar height",
        "Non-swivel — stable and secure",
        "Footrest rail — solid walnut",
        "Sold individually or as a set of 2",
      ],
      care: "Condition leather monthly. Wipe walnut with dry cloth. Oil bi-annually.",
      warranty: "5-year frame. 3-year leather.",
      rating: 4.8, reviewCount: 58,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=900&q=85", altText: "Alta Leather Bar Stool in Cognac", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Alta — leather back and walnut frame detail", isPrimary: false, sortOrder: 1 },
    ],
  },

  // ── Bar Cabinets (3) ─────────────────────────────────────────
  {
    sku: "MOD-BAR-001", slug: "crystal-bar-cabinet",
    name: "Crystal Lead-Glass Bar Cabinet", categorySlug: "dining", subcategorySlug: "bar-cabinets",
    brand: "Heritage Collection", price: 348000, currency: "INR",
    material: "Solid Walnut & Lead Glass", finishOptions: ["Dark Walnut", "Natural Walnut"],
    dimensions: { width: 90, height: 125, depth: 42, unit: "cm" }, weightKg: 68,
    isConfigurable: false, isFeatured: true, stockQty: 4, leadTimeDays: 42,
    seoTitle: "Crystal Lead-Glass Bar Cabinet in Walnut — Heritage Collection Modulas",
    seoDescription: "Solid walnut bar cabinet with lead-glass front panels. Velvet-lined interior. 90 cm wide. Holds 24 bottles. Heritage Collection.",
    tags: ["premium", "subcategory:bar-cabinets"],
    description: "Lead glass panels over a solid walnut body — the Crystal Bar Cabinet displays a drinks collection with the reverence it deserves.",
    metadata: {
      fullDescription: "The Crystal Bar Cabinet is designed around the principle that a well-curated drinks collection deserves to be visible. Its upper section has two lead-glass panel doors — the geometric pattern of the leading creating a period detail in a contemporary form — that reveal the bottle display inside. The interior is velvet-lined on the back and sides, with adjustable bottle racks, a pull-out mixing surface, and a lower solid-door section for glassware and accessories.",
      features: [
        "Lead-glass upper door panels — geometric leading pattern",
        "Velvet-lined interior — back and side panels",
        "Adjustable bottle racks — holds 24 standard bottles",
        "Pull-out mixing surface — 40 cm deep",
        "Lower section — solid doors for glassware",
        "Solid walnut throughout",
        "Key lock on upper doors",
      ],
      care: "Clean glass panels with glass cleaner. Oil walnut bi-annually. Wipe velvet interior with a dry soft cloth.",
      warranty: "10-year structural. 5-year mechanism.",
      rating: 4.9, reviewCount: 38,
    },
    images: [
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Crystal Bar Cabinet in Dark Walnut", isPrimary: true, sortOrder: 0 },
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Crystal — lead glass and velvet interior detail", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BAR-002", slug: "velvet-bar-drinks-cabinet",
    name: "Velvet Bar Drinks Cabinet", categorySlug: "dining", subcategorySlug: "bar-cabinets",
    brand: "Atelier Series", price: 195000, currency: "INR",
    material: "Lacquered MDF & Velvet Lining", finishOptions: ["Midnight Blue / Gold", "Forest Green / Brass", "Graphite / Chrome"],
    dimensions: { width: 75, height: 110, depth: 40, unit: "cm" }, weightKg: 48,
    isConfigurable: false, isFeatured: false, stockQty: 7, leadTimeDays: 28,
    seoTitle: "Velvet-Lined Bar Drinks Cabinet — Atelier Series Modulas",
    seoDescription: "Bar drinks cabinet with velvet interior and metal door handles. 3 dramatic exterior colourways. Holds 18 bottles. Ships in 28 days.",
    tags: ["new", "subcategory:bar-cabinets"],
    description: "A bold exterior — deep colour lacquer with brass or chrome hardware — over a velvet-lined interior that handles every bottle with care.",
    metadata: {
      fullDescription: "The Velvet Bar Cabinet is the most decorative piece in the Modulas drinks storage range — a lacquered cabinet in three dramatic exterior colours (midnight blue, forest green, graphite), each with a contrasting metal handle finish. The interior is fully velvet-lined: dark charcoal velvet on the back and side walls, and a velvet-covered pull-out base tray for mixing. The two-door cabinet holds 18 bottles in adjustable racks, with a lower drawer for accessories.",
      features: [
        "Lacquered exterior — 3 dramatic colourways",
        "Full velvet interior — charcoal lining",
        "Adjustable bottle racks — 18 bottles",
        "Pull-out velvet base tray for mixing",
        "1 lower drawer for bar accessories",
        "Brass or chrome hardware depending on colourway",
        "Anti-tip wall anchor included",
      ],
      care: "Wipe lacquered exterior with damp cloth and dry immediately. Polish hardware with metal cloth. Vacuum velvet interior with soft brush.",
      warranty: "5-year structural. 3-year mechanism.",
      rating: 4.7, reviewCount: 63,
    },
    images: [
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Velvet Bar Cabinet in Midnight Blue/Gold", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Velvet Bar Cabinet — interior velvet lining", isPrimary: false, sortOrder: 1 },
    ],
  },
  {
    sku: "MOD-BAR-003", slug: "heritage-globe-bar-cabinet",
    name: "Heritage Globe Bar Cabinet", categorySlug: "dining", subcategorySlug: "bar-cabinets",
    brand: "Heritage Collection", price: 265000, currency: "INR",
    material: "Solid Walnut & Polished Brass", finishOptions: ["Dark Walnut / Brass"],
    dimensions: { width: 80, height: 95, depth: 45, unit: "cm" }, weightKg: 52,
    isConfigurable: false, isFeatured: false, stockQty: 5, leadTimeDays: 35,
    seoTitle: "Heritage Globe Bar Cabinet in Walnut and Brass — Modulas",
    seoDescription: "Walnut and brass bar cabinet with globe-door fronts. Interior bar fittings — holds 12 bottles and 12 glasses. Heritage Collection.",
    tags: ["premium", "limited", "subcategory:bar-cabinets"],
    description: "Curved globe door panels in solid walnut with polished brass hinges and handle — the Heritage Globe is a bar cabinet that doubles as a sculpture.",
    metadata: {
      fullDescription: "The Heritage Globe Bar Cabinet takes its visual cue from the globe-front cocktail cabinets of the mid-20th century — a design period that treated the home bar as an object of theatre. Its two curved doors (formed from steam-bent solid walnut) open wide to reveal a fully fitted interior: a mirrored back panel, brass bottle rails, a pull-out leather mixing mat, and six crystal glass holders on the inside of each door.",
      features: [
        "Steam-bent solid walnut globe door panels",
        "Polished brass hinges and cup handle",
        "Mirrored interior back panel",
        "Brass bottle rails — 12 bottles",
        "Pull-out leather mixing mat",
        "6 crystal glass holders per door (12 total)",
        "Heritage Collection — limited production",
      ],
      care: "Oil walnut doors twice per year. Polish brass with brass cloth. Wipe mirror with glass cleaner.",
      warranty: "Lifetime structural. 5-year mechanism.",
      rating: 4.9, reviewCount: 22,
    },
    images: [
      { url: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=900", altText: "Heritage Globe Bar Cabinet — open view", isPrimary: true, sortOrder: 0 },
      { url: "https://images.unsplash.com/photo-1595347097560-69238724e7ad?w=900&q=85", altText: "Heritage Globe — brass hinge and walnut detail", isPrimary: false, sortOrder: 1 },
    ],
  },
];
